# Generated by Django 6.1.1 on 2026-09-17 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('construction', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ada_no', models.CharField(max_length=50, verbose_name='Ada No')),
                ('mahalle', models.CharField(blank=True, max_length=150, verbose_name='Mahalle')),
                ('ilce', models.CharField(blank=True, max_length=150, verbose_name='İlçe')),
                ('il', models.CharField(blank=True, max_length=150, verbose_name='İl')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Ada',
                'verbose_name_plural': 'Adalar',
                'ordering': ['il', 'ilce', 'mahalle', 'ada_no'],
            },
        ),
        migrations.CreateModel(
            name='KatKarsiligiSenaryo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senaryo_adi', models.CharField(max_length=150, verbose_name='Senaryo Adı')),
                ('arsa_pay_orani', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Arsa Pay Oranı (%)')),
                ('kat_karsiligi_orani', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Kat Karşılığı Oranı (%)')),
                ('bagimsiz_bolum_m2', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Bağımsız Bölüm Alanı (m²)')),
                ('toplam_birim_sayisi', models.PositiveIntegerField(default=0, verbose_name='Toplam Birim Sayısı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Kat Karşılığı Senaryosu',
                'verbose_name_plural': 'Kat Karşılığı Senaryoları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MalikMutabakati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('malik_adi', models.CharField(max_length=200, verbose_name='Malik Adı')),
                ('pay_orani', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Pay Oranı (%)')),
                ('oy_durumu', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('kabul', 'Kabul'), ('red', 'Red'), ('bilinmiyor', 'Bilinmiyor')], default='bekliyor', max_length=20, verbose_name='Oy Durumu')),
                ('notlar', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('senaryo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='malik_mutabakatlari', to='real_estate.katkarsiligisenaryo', verbose_name='Senaryo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Malik Mutabakati',
                'verbose_name_plural': 'Malik Mutabakatları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Parsel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parsel_no', models.CharField(max_length=50, verbose_name='Parsel No')),
                ('pafta', models.CharField(blank=True, max_length=50, verbose_name='Pafta')),
                ('alan_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Alan (m²)')),
                ('imar_durumu', models.CharField(choices=[('imara_uygun', 'İmara Uygun'), ('imarli', 'İmarlı'), ('imar_hakki_verilmis', 'İmar Hakkı Verilmiş'), ('plan_degisikligi', 'Plan Değişikliği'), ('belirsiz', 'Belirsiz')], default='belirsiz', max_length=30, verbose_name='İmar Durumu')),
                ('kat_karsiligi_orani', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Kat Karşılığı Oranı (%)')),
                ('malik_sayisi', models.PositiveIntegerField(default=1, verbose_name='Malik Sayısı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('ada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parseller', to='real_estate.ada', verbose_name='Ada')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Parsel',
                'verbose_name_plural': 'Parseller',
                'ordering': ['ada__ada_no', 'parsel_no'],
            },
        ),
        migrations.AddField(
            model_name='katkarsiligisenaryo',
            name='parsel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kat_karsiligi_senaryolari', to='real_estate.parsel', verbose_name='Parsel'),
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(blank=True, max_length=200, verbose_name='Gayrimenkul Adı')),
                ('blok', models.CharField(blank=True, max_length=50, verbose_name='Blok')),
                ('kat', models.CharField(blank=True, max_length=50, verbose_name='Kat')),
                ('daire_no', models.CharField(blank=True, max_length=50, verbose_name='Daire No')),
                ('brut_m2', models.DecimalField(blank=True, decimal_places=2, help_text='Decimal — float kullanılmaz (01-GELISTIRME-KURALLARI.md §4).', max_digits=9, null=True, verbose_name='Brüt Alan (m²)')),
                ('durum', models.CharField(choices=[('available', 'Müsait'), ('rented', 'Kirada'), ('sold', 'Satıldı'), ('reserved', 'Rezerve'), ('maintenance', 'Bakımda')], default='available', max_length=20, verbose_name='Durum')),
                ('tapu_adi', models.CharField(blank=True, max_length=200, verbose_name='Tapu Adı Bilgisi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('ada', models.ForeignKey(blank=True, help_text='Ada ilişkili gayrimenkul (Faz 3: Kentsel Dönüşüm)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='realestates', to='real_estate.ada', verbose_name='Ada')),
                ('proje', models.ForeignKey(blank=True, help_text='Proje ↔ Gayrimenkul ilişkisi (roadmap Faz 1).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gayrimenkuller', to='construction.proje', verbose_name='İnşaat Projesi')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Gayrimenkul',
                'verbose_name_plural': 'Gayrimenkuller',
                'ordering': ['blok', 'kat', 'daire_no'],
            },
        ),
        migrations.AddConstraint(
            model_name='ada',
            constraint=models.UniqueConstraint(fields=('tenant', 'ada_no'), name='uniq_ada_no_tenant'),
        ),
        migrations.AddConstraint(
            model_name='malikmutabakati',
            constraint=models.UniqueConstraint(fields=('tenant', 'senaryo', 'malik_adi'), name='uniq_malik_senaryo_tenant'),
        ),
        migrations.AddConstraint(
            model_name='parsel',
            constraint=models.UniqueConstraint(fields=('tenant', 'ada', 'parsel_no'), name='uniq_parsel_ada_tenant'),
        ),
        migrations.AddConstraint(
            model_name='katkarsiligisenaryo',
            constraint=models.UniqueConstraint(fields=('tenant', 'parsel', 'senaryo_adi'), name='uniq_senaryo_parsel_tenant'),
        ),
        migrations.AddConstraint(
            model_name='realestate',
            constraint=models.UniqueConstraint(fields=('tenant', 'blok', 'kat', 'daire_no'), name='uniq_gayrimenkul_konum_tenant'),
        ),
    ]
