# Generated by Django 6.1.1 on 2026-09-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginDenemesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanici_adi', models.CharField(max_length=150, unique=True, verbose_name='Kullanıcı Adı (küçük harf)')),
                ('basarisiz_sayisi', models.PositiveIntegerField(default=0, verbose_name='Başarısız Sayısı')),
                ('kilit_bitis', models.DateTimeField(blank=True, null=True, verbose_name='Kilit Bitişi')),
                ('guncellendi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
            ],
            options={
                'verbose_name': 'Login Denemesi',
                'verbose_name_plural': 'Login Denemeleri',
            },
        ),
    ]
