<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import KayitModal from '@/components/KayitModal.vue'
import VeriTablosu from '@/components/VeriTablosu.vue'
import { hataMesaji } from '@/services/apiClient'
import { insaatApi, tumunuGetir } from '@/services/insaatApi'
import { useAuthStore } from '@/stores/auth'
import { EKB_DURUMLARI, EKB_ENERJI_SINIFLARI, type EKB, type EKBDurumu, type EKBEnerjiSinifi, type Proje } from '@/types/insaat'
import { yazabilirMi } from '@/utils/yetki'

const auth = useAuthStore()
const yazabilir = computed(() => yazabilirMi(auth.kullanici?.role))
const kayitlar = ref<EKB[]>([])
const projeler = ref<Proje[]>([])
const ozet = ref({ toplam: 0, onayli: 0, suresi_dolan: 0, otuz_gun_icinde: 0 })
const arama = ref(''); const projeFiltre = ref<number | ''>(''); const durumFiltre = ref<EKBDurumu | ''>('')
const sinifFiltre = ref<EKBEnerjiSinifi | ''>(''); const arsivFiltre = ref(false); const expiryFiltre = ref('')
const siralama = ref<'expiry' | 'project' | 'status'>('expiry')
const yukleniyor = ref(false); const hata = ref(''); const modalAcik = ref(false); const detay = ref<EKB | null>(null)
const formHata = ref(''); const kaydediliyor = ref(false); const duzenlenen = ref<EKB | null>(null)
const form = ref({ proje: 0, belge_no: '', durum: 'taslak' as EKBDurumu, enerji_sinifi: '' as EKBEnerjiSinifi | '', duzenlenme_tarihi: '', gecerlilik_tarihi: '', duzenleyen: '', notlar: '', dokuman_referansi: '' })

const filtreli = computed(() => kayitlar.value.filter((x) => {
  const metin = `${x.belge_no} ${x.duzenleyen} ${x.proje_kodu || ''} ${x.proje_adi || ''}`.toLocaleLowerCase('tr-TR')
  return (!arama.value || metin.includes(arama.value.toLocaleLowerCase('tr-TR'))) &&
    (!projeFiltre.value || x.proje === projeFiltre.value) && (!durumFiltre.value || x.durum === durumFiltre.value) &&
    (!sinifFiltre.value || x.enerji_sinifi === sinifFiltre.value) && (!arsivFiltre.value || !x.is_active) &&
    (!expiryFiltre.value || (expiryFiltre.value === 'expired' ? x.gecerlilik_durumu === 'suresi_doldu' : x.kalan_gun !== null && x.kalan_gun !== undefined && x.kalan_gun >= 0 && x.kalan_gun <= Number(expiryFiltre.value)))
}).sort((a, b) => siralama.value === 'project' ? (a.proje_kodu || '').localeCompare(b.proje_kodu || '') : siralama.value === 'status' ? a.durum.localeCompare(b.durum) : (a.kalan_gun ?? 99999) - (b.kalan_gun ?? 99999)))

function gunMetni(x: EKB): string { return x.kalan_gun === undefined || x.kalan_gun === null ? 'Tarih yok' : x.kalan_gun < 0 ? `${Math.abs(x.kalan_gun)} gün önce doldu` : `${x.kalan_gun} gün kaldı` }
function uyari(x: EKB): string { return x.gecerlilik_durumu === 'suresi_doldu' ? 'text-red-700 font-semibold' : x.gecerlilik_durumu === 'yaklasiyor' ? 'text-amber-700 font-semibold' : '' }
function projeAdi(id: number): string { return projeler.value.find((x) => x.id === id)?.ad || `Proje #${id}` }
function sifirla(): void { arama.value = ''; projeFiltre.value = ''; durumFiltre.value = ''; sinifFiltre.value = ''; arsivFiltre.value = false; expiryFiltre.value = '' }
function yeni(): void { duzenlenen.value = null; detay.value = null; formHata.value = ''; form.value = { proje: projeler.value[0]?.id || 0, belge_no: '', durum: 'taslak', enerji_sinifi: '', duzenlenme_tarihi: '', gecerlilik_tarihi: '', duzenleyen: '', notlar: '', dokuman_referansi: '' }; modalAcik.value = true }
function duzenle(x: EKB): void { duzenlenen.value = x; detay.value = null; formHata.value = ''; form.value = { proje: x.proje, belge_no: x.belge_no, durum: x.durum, enerji_sinifi: x.enerji_sinifi, duzenlenme_tarihi: x.duzenlenme_tarihi || '', gecerlilik_tarihi: x.gecerlilik_tarihi || '', duzenleyen: x.duzenleyen, notlar: x.notlar, dokuman_referansi: x.dokuman_referansi }; modalAcik.value = true }
async function yukle(): Promise<void> { yukleniyor.value = true; hata.value = ''; try { const [ekb, proje, kpi] = await Promise.all([tumunuGetir(insaatApi.ekb.liste, arsivFiltre.value ? { is_active: false } : {}), tumunuGetir(insaatApi.projeler.liste), insaatApi.ekb.ozet(arsivFiltre.value ? { is_active: false } : {})]); kayitlar.value = ekb; projeler.value = proje; ozet.value = kpi } catch (e) { hata.value = hataMesaji(e) } finally { yukleniyor.value = false } }
async function arsivle(x: EKB): Promise<void> { if (!confirm(`${x.belge_no} arşivlensin mi?`)) return; try { await insaatApi.ekb.sil(x.id); await yukle() } catch (e) { hata.value = hataMesaji(e) } }
async function geriAl(x: EKB): Promise<void> { try { await insaatApi.ekb.arsivdenCikar(x.id); await yukle() } catch (e) { hata.value = hataMesaji(e) } }
async function kaydet(): Promise<void> { formHata.value = ''; if (!form.value.proje || !form.value.belge_no.trim()) { formHata.value = 'Proje ve belge numarası zorunludur.'; return }; if (form.value.duzenlenme_tarihi && form.value.gecerlilik_tarihi && form.value.gecerlilik_tarihi <= form.value.duzenlenme_tarihi) { formHata.value = 'Geçerlilik tarihi düzenlenme tarihinden sonra olmalıdır.'; return }; kaydediliyor.value = true; try { const veri = { ...form.value, belge_no: form.value.belge_no.trim(), duzenlenme_tarihi: form.value.duzenlenme_tarihi || null, gecerlilik_tarihi: form.value.gecerlilik_tarihi || null, enerji_sinifi: form.value.enerji_sinifi || '' }; if (duzenlenen.value) await insaatApi.ekb.guncelle(duzenlenen.value.id, veri); else await insaatApi.ekb.olustur(veri); if (form.value.gecerlilik_tarihi) window.dispatchEvent(new CustomEvent('hatirlatma-onerisi', { detail: { tarih: form.value.gecerlilik_tarihi, baslik: 'EKB geçerliliği için hatırlatma kurmak ister misiniz?', payload: { ilgili_app: 'construction', ilgili_model: 'EKB' } } })); modalAcik.value = false; await yukle() } catch (e) { formHata.value = hataMesaji(e) } finally { kaydediliyor.value = false } }
onMounted(yukle)
</script>

<template>
  <main class="mx-auto max-w-7xl">
    <header class="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p class="text-sm font-medium text-primary-700">İnşaat / Uygunluk</p><h1 class="font-heading text-2xl font-bold text-surface-900">EKB Süreç Takibi</h1><p class="mt-1 text-sm text-surface-500">Belgelerin geçerliliğini ve yenileme ihtiyacını tek ekrandan yönetin.</p></div><button v-if="yazabilir" class="birincil-dugme" type="button" @click="yeni">+ Yeni EKB</button></header>
    <div class="mb-6 grid grid-cols-2 gap-3 md:grid-cols-4"><button class="rounded-xl border bg-white p-4 text-left shadow-sm" @click="sifirla"><span class="text-xs text-surface-500">Aktif belge</span><strong class="mt-1 block text-2xl">{{ ozet.toplam }}</strong></button><button class="rounded-xl border bg-white p-4 text-left shadow-sm" @click="durumFiltre = 'onaylandi'"><span class="text-xs text-surface-500">Onaylı</span><strong class="mt-1 block text-2xl text-emerald-700">{{ ozet.onayli }}</strong></button><button class="rounded-xl border bg-white p-4 text-left shadow-sm" @click="expiryFiltre = '30'"><span class="text-xs text-surface-500">30 gün içinde</span><strong class="mt-1 block text-2xl text-amber-700">{{ ozet.otuz_gun_icinde }}</strong></button><button class="rounded-xl border bg-white p-4 text-left shadow-sm" @click="expiryFiltre = 'expired'"><span class="text-xs text-surface-500">Süresi dolan</span><strong class="mt-1 block text-2xl text-red-700">{{ ozet.suresi_dolan }}</strong></button></div>
    <p v-if="hata" class="hata-kutusu mb-4" role="alert">{{ hata }}</p>
    <section class="mb-4 flex flex-wrap gap-2" aria-label="EKB filtreleri"><input v-model="arama" class="alan min-w-56 flex-1" type="search" placeholder="Belge no, proje veya düzenleyen ara…" aria-label="Ara" /><select v-model="projeFiltre" class="alan" aria-label="Proje"><option value="">Tüm projeler</option><option v-for="x in projeler" :key="x.id" :value="x.id">{{ x.proje_kodu }} — {{ x.ad }}</option></select><select v-model="durumFiltre" class="alan" aria-label="Durum"><option value="">Tüm durumlar</option><option v-for="(e, k) in EKB_DURUMLARI" :key="k" :value="k">{{ e }}</option></select><select v-model="sinifFiltre" class="alan" aria-label="Enerji sınıfı"><option value="">Tüm sınıflar</option><option v-for="(e, k) in EKB_ENERJI_SINIFLARI" :key="k" :value="k">{{ e }}</option></select><select v-model="expiryFiltre" class="alan" aria-label="Geçerlilik"><option value="">Tüm tarihler</option><option value="30">30 gün içinde</option><option value="90">90 gün içinde</option><option value="expired">Süresi dolan</option></select><select v-model="siralama" class="alan" aria-label="Sıralama"><option value="expiry">Geçerlilik</option><option value="project">Proje</option><option value="status">Durum</option></select><label class="flex items-center gap-2 px-2 text-sm"><input v-model="arsivFiltre" type="checkbox" @change="yukle" /> Arşiv</label><button class="ikincil-dugme" type="button" @click="sifirla">Temizle</button><button class="ikincil-dugme" type="button" :disabled="yukleniyor" @click="yukle">{{ yukleniyor ? 'Yükleniyor…' : 'Yenile' }}</button></section>
    <div v-if="yukleniyor" class="rounded-xl border bg-white p-10 text-center text-surface-500">Belgeler yükleniyor…</div>
    <VeriTablosu v-else :basliklar="['Belge No','Proje','Durum','Enerji sınıfı','Geçerlilik','İşlemler']" :bos-mu="!filtreli.length" :bos-mesaj="kayitlar.length ? 'Filtrelerle eşleşen belge yok.' : 'Henüz EKB kaydı bulunmuyor.'"><tr v-for="x in filtreli" :key="x.id" class="hover:bg-primary-50/40"><td class="px-4 py-3 font-semibold"><button class="text-left text-primary-700 hover:underline" @click="detay = x">{{ x.belge_no }}</button></td><td class="px-4 py-3">{{ x.proje_kodu || projeAdi(x.proje) }}</td><td class="px-4 py-3">{{ EKB_DURUMLARI[x.durum] }}</td><td class="px-4 py-3 font-semibold">{{ x.enerji_sinifi || '—' }}</td><td class="px-4 py-3" :class="uyari(x)">{{ x.gecerlilik_tarihi || '—' }}<span class="block text-xs">{{ gunMetni(x) }}</span></td><td class="space-x-2 px-4 py-3 text-sm"><button @click="detay = x">Detay</button><button v-if="yazabilir && x.is_active" class="text-primary-700" @click="duzenle(x)">Düzenle</button><button v-if="yazabilir && x.is_active" class="text-red-700" @click="arsivle(x)">Arşivle</button><button v-if="yazabilir && !x.is_active" class="text-emerald-700" @click="geriAl(x)">Geri al</button></td></tr></VeriTablosu>
    <KayitModal v-if="detay" baslik="EKB ayrıntıları" @kapat="detay = null"><dl class="grid gap-3 text-sm md:grid-cols-2"><div><dt class="text-surface-500">Belge no</dt><dd class="font-semibold">{{ detay.belge_no }}</dd></div><div><dt class="text-surface-500">Durum</dt><dd>{{ EKB_DURUMLARI[detay.durum] }}</dd></div><div><dt class="text-surface-500">Proje</dt><dd>{{ detay.proje_kodu || projeAdi(detay.proje) }}</dd></div><div><dt class="text-surface-500">Enerji sınıfı</dt><dd>{{ detay.enerji_sinifi || '—' }}</dd></div><div class="md:col-span-2"><dt class="text-surface-500">Notlar</dt><dd class="whitespace-pre-wrap">{{ detay.notlar || '—' }}</dd></div></dl><div class="mt-5 flex justify-end"><button class="ikincil-dugme" @click="detay = null">Kapat</button></div></KayitModal>
    <KayitModal v-if="modalAcik" :baslik="duzenlenen ? 'EKB Düzenle' : 'Yeni EKB'" @kapat="modalAcik = false"><form class="flex flex-col gap-4" @submit.prevent="kaydet"><div class="grid gap-4 md:grid-cols-2"><label class="etiket">Proje *<select v-model.number="form.proje" class="alan" required><option v-for="x in projeler" :key="x.id" :value="x.id">{{ x.proje_kodu }} — {{ x.ad }}</option></select></label><label class="etiket">Belge No *<input v-model="form.belge_no" class="alan" maxlength="100" required /></label></div><div class="grid gap-4 md:grid-cols-2"><label class="etiket">Durum<select v-model="form.durum" class="alan"><option v-for="(e, k) in EKB_DURUMLARI" :key="k" :value="k">{{ e }}</option></select></label><label class="etiket">Enerji sınıfı<select v-model="form.enerji_sinifi" class="alan"><option value="">—</option><option v-for="(e, k) in EKB_ENERJI_SINIFLARI" :key="k" :value="k">{{ e }}</option></select></label></div><div class="grid gap-4 md:grid-cols-2"><label class="etiket">Düzenlenme tarihi<input v-model="form.duzenlenme_tarihi" type="date" class="alan" /></label><label class="etiket">Geçerlilik tarihi<input v-model="form.gecerlilik_tarihi" type="date" class="alan" /></label></div><label class="etiket">Düzenleyen<input v-model="form.duzenleyen" class="alan" maxlength="255" /></label><label class="etiket">Doküman referansı<input v-model="form.dokuman_referansi" class="alan" maxlength="500" /></label><label class="etiket">Notlar<textarea v-model="form.notlar" class="alan" rows="3" maxlength="5000" /></label><p v-if="formHata" class="hata-kutusu" role="alert">{{ formHata }}</p><div class="flex justify-end gap-2"><button type="button" class="ikincil-dugme" @click="modalAcik = false">Vazgeç</button><button class="birincil-dugme" type="submit" :disabled="kaydediliyor">{{ kaydediliyor ? 'Kaydediliyor…' : 'Kaydet' }}</button></div></form></KayitModal>
  </main>
</template>
