# Generated by Django 6.1.1 on 2026-09-17 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255, verbose_name='Ad / Unvan')),
                ('tip', models.CharField(choices=[('kiraci', 'Kiracı'), ('malik', 'Malik'), ('tedarikci', 'Tedarikçi'), ('taseron', 'Taşeron'), ('diger', 'Diğer')], default='diger', max_length=20, verbose_name='Cari Tipi')),
                ('tur', models.CharField(choices=[('bireysel', 'Bireysel'), ('kurumsal', 'Kurumsal')], default='bireysel', max_length=20, verbose_name='Bireysel / Kurumsal')),
                ('vergi_no', models.CharField(blank=True, max_length=10, verbose_name='Vergi Kimlik No')),
                ('vergi_dairesi', models.CharField(blank=True, max_length=150, verbose_name='Vergi Dairesi')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('adres', models.TextField(blank=True, verbose_name='Adres')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Cari',
                'verbose_name_plural': 'Cariler',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='CariHareket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yon', models.CharField(choices=[('borc', 'Borç'), ('alacak', 'Alacak')], max_length=10, verbose_name='Yön')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Tutar (₺)')),
                ('aciklama', models.CharField(blank=True, max_length=255, verbose_name='Açıklama')),
                ('islem_tarihi', models.DateField(verbose_name='İşlem Tarihi')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='İptal Edildi')),
                ('iptal_nedeni', models.CharField(blank=True, max_length=255, verbose_name='İptal Nedeni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('cari', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hareketler', to='cari.cari', verbose_name='Cari')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Cari Hareket',
                'verbose_name_plural': 'Cari Hareketler',
                'ordering': ['-islem_tarihi', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='cari',
            constraint=models.UniqueConstraint(fields=('tenant', 'ad'), name='uniq_cari_tenant_ad'),
        ),
    ]
