# Generated by Django 6.1 on 2026-09-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cari", "0003_cari_kart_genisletme"),
    ]

    operations = [
        migrations.AddField(
            model_name="cari",
            name="eski_adres",
            field=models.TextField(blank=True, verbose_name="Eski Adres"),
        ),
        migrations.AddField(
            model_name="cari",
            name="epostalar",
            field=models.JSONField(blank=True, default=list, verbose_name="E-postalar"),
        ),
        migrations.AddField(
            model_name="cari",
            name="cep_telefonlari",
            field=models.JSONField(blank=True, default=list, verbose_name="Cep Telefonları"),
        ),
        migrations.AddField(
            model_name="cari",
            name="telefonlar",
            field=models.JSONField(blank=True, default=list, verbose_name="Telefonlar"),
        ),
        migrations.AddField(
            model_name="cari",
            name="ulke",
            field=models.CharField(blank=True, default="Türkiye", max_length=100, verbose_name="Ülke"),
        ),
        migrations.AddField(
            model_name="cari",
            name="yetkili_kisiler",
            field=models.JSONField(blank=True, default=list, verbose_name="Yetkili Kişiler"),
        ),
    ]
