# Generated by Django 6.1.1 on 2026-09-18 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_100_smoke_kasa_hesabi'),
        ('cari', '0004_cari_iletisim_adres'),
    ]

    operations = [
        migrations.AddField(
            model_name='carihareket',
            name='muhasebe_fisi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cari_hareketleri', to='accounting.muhasebefisi', verbose_name='Muhasebe Fişi'),
        ),
    ]
