# Generated by Django 6.1.1.1 on 2026-09-01-01 00:00
# Reconciliation migration to fix missing fatura_id column in cari_carihareket table
# This migration is idempotent and safe to run multiple times

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cari', '0005_carihareket_muhasebe_fisi'),
        ('finance', '0013_finansal_olay_cekirdegi'),  # Same dependency as 0002
    ]

    operations = [
        # Add fatura_id column if it doesn't exist (idempotent)
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = 'cari_carihareket' AND column_name = 'fatura_id'
                ) THEN
                    ALTER TABLE cari_carihareket ADD COLUMN fatura_id BIGINT NULL;
                END IF;
            END $$;
            """,
            reverse_sql="""
            -- This is intentionally not reversible in production as data may exist
            -- To reverse: ALTER TABLE cari_carihareket DROP COLUMN fatura_id;
            """,
            elidable=True
        ),
        
        # Add foreign key constraint if it doesn't exist (idempotent)
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.table_constraints 
                    WHERE table_name = 'cari_carihareket' 
                    AND constraint_name = 'cari_carihareket_fatura_id_finance_fatura_id_fk'
                ) THEN
                    ALTER TABLE cari_carihareket 
                    ADD CONSTRAINT cari_carihareket_fatura_id_finance_fatura_id_fk
                    FOREIGN KEY (fatura_id) REFERENCES finance_fatura(id);
                END IF;
            END $$;
            """,
            reverse_sql="""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM information_schema.table_constraints 
                    WHERE table_name = 'cari_carihareket' 
                    AND constraint_name = 'cari_carihareket_fatura_id_finance_fatura_id_fk'
                ) THEN
                    ALTER TABLE cari_carihareket 
                    DROP CONSTRAINT cari_carihareket_fatura_id_finance_fatura_id_fk;
                END IF;
            END $$;
            """,
            elidable=True
        ),
        
        # Add unique partial index if it doesn't exist (idempotent)
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_indexes 
                    WHERE tablename = 'cari_carihareket' AND indexname = 'uniq_cari_hareket_fatura'
                ) THEN
                    CREATE UNIQUE INDEX uniq_cari_hareket_fatura 
                    ON cari_carihareket (fatura_id) 
                    WHERE fatura_id IS NOT NULL;
                END IF;
            END $$;
            """,
            reverse_sql="""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM pg_indexes 
                    WHERE tablename = 'cari_carihareket' AND indexname = 'uniq_cari_hareket_fatura'
                ) THEN
                    DROP INDEX IF EXISTS uniq_cari_hareket_fatura;
                END IF;
            END $$;
            """,
            elidable=True
        ),
    ]