# Generated by Django 6.1.1 on 2026-09-22 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_100_smoke_kasa_hesabi'),
        ('cari', '0006_reconcile_carihareket_fatura_schema'),
        ('finance', '0016_alter_fatura_fatura_turu'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carihareket',
            name='finansal_islem',
            field=models.ForeignKey(blank=True, help_text='Ödeme iptali ters hareket bağlantısı (FAZ 6B).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cari_hareketleri', to='finance.finansalislem', verbose_name='Kaynak Finansal İşlem'),
        ),
        migrations.AddConstraint(
            model_name='carihareket',
            constraint=models.UniqueConstraint(condition=models.Q(('finansal_islem__isnull', False)), fields=('finansal_islem',), name='uniq_cari_hareket_finansal_islem'),
        ),
    ]
