# Generated by Django 6.1.1 on 2026-09-17 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cari', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KasaBankaHesabi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=20, verbose_name='Hesap Kodu')),
                ('ad', models.CharField(max_length=200, verbose_name='Hesap Adı')),
                ('tip', models.CharField(choices=[('kasa', 'Kasa'), ('banka', 'Banka'), ('kredi_karti', 'Kredi Kartı'), ('cek', 'Çek')], default='kasa', max_length=15, verbose_name='Hesap Tipi')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('para_birimi', models.CharField(default='TRY', max_length=3, verbose_name='Para Birimi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Kasa / Banka Hesabı',
                'verbose_name_plural': 'Kasa / Banka Hesapları',
                'ordering': ['kod'],
            },
        ),
        migrations.CreateModel(
            name='FinansalIslem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yon', models.CharField(choices=[('gelir', 'Gelir'), ('gider', 'Gider'), ('transfer', 'Transfer')], max_length=10, verbose_name='Yön')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Tutar (₺)')),
                ('islem_tarihi', models.DateField(verbose_name='İşlem Tarihi')),
                ('aciklama', models.CharField(blank=True, max_length=255, verbose_name='Açıklama')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='İptal Edildi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('cari', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finans_islemleri', to='cari.cari', verbose_name='Cari')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant')),
                ('hesap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='islemler', to='finance.kasabankahesabi', verbose_name='Hesap')),
            ],
            options={
                'verbose_name': 'Finansal İşlem',
                'verbose_name_plural': 'Finansal İşlemler',
                'ordering': ['-islem_tarihi', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='kasabankahesabi',
            constraint=models.UniqueConstraint(fields=('tenant', 'kod'), name='uniq_kasa_tenant_kod'),
        ),
    ]
