# Generated by Django 6.1.1 on 2026-09-18 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cari', '0001_initial'),
        ('finance', '0002_faturakalemi'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('mizan', 'Mizan'), ('cari_ozet', 'Cari Özet'), ('finansal_toplam', 'Finansal Toplam'), ('poz_planı', 'Poz Planı (S-eğrisi)')], default='mizan', max_length=30, verbose_name='Rapor Tipi')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('filtreleme_verisi', models.JSONField(blank=True, default=dict, verbose_name='Filtreleme Verisi')),
                ('sonuc_verisi', models.JSONField(blank=True, default=dict, verbose_name='Sonuç Verisi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('cari', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raporlar', to='cari.cari', verbose_name='Cari')),
                ('kasa_banka_hesabi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raporlar', to='finance.kasabankahesabi', verbose_name='Kasa/Banka Hesabı')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Rapor',
                'verbose_name_plural': 'Raporlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ayar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anahtar', models.CharField(choices=[('site_adi', 'Site Adı'), ('vergi_no', 'Vergi Numarası'), ('telefon', 'Telefon'), ('eposta', 'E-posta'), ('para_birimi_default', 'Varsayılan Para Birimi')], max_length=50, verbose_name='Anahtar')),
                ('deger', models.CharField(max_length=255, verbose_name='Değer')),
                ('aciklama', models.CharField(blank=True, max_length=255, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Ayar',
                'verbose_name_plural': 'Ayarlar',
                'ordering': ['anahtar'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'anahtar'), name='uniq_ayar_tenant_anahtar')],
            },
        ),
    ]
