from django.db import migrations, models
from decimal import Decimal


class Migration(migrations.Migration):
    dependencies = [("finance", "0005_alter_ceksenet_tenant")]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE TABLE IF NOT EXISTS finance_faturakalemi (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    aciklama varchar(255) NOT NULL,
                    miktar numeric(14, 4) NOT NULL,
                    birim varchar(20) NOT NULL DEFAULT 'ADET',
                    birim_fiyat numeric(15, 2) NOT NULL,
                    kdv_orani numeric(5, 2) NOT NULL DEFAULT 20,
                    tevkifat_orani numeric(5, 2) NOT NULL DEFAULT 0,
                    fatura_id bigint NOT NULL REFERENCES finance_fatura(id) DEFERRABLE INITIALLY DEFERRED
                );
                CREATE INDEX IF NOT EXISTS finance_faturakalemi_fatura_id_idx
                    ON finance_faturakalemi (fatura_id);
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name="faturakalemi",
            name="stopaj_orani",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=5,
                verbose_name="Stopaj (%)",
            ),
        ),
    ]
