# Generated by Django 6.1.1 on 2026-09-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_outboxevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatura',
            name='fatura_turu',
            field=models.CharField(choices=[('satis', 'Satış'), ('kira', 'Kira'), ('hakedis', 'Hakediş'), ('iade', 'İade'), ('aidat', 'Aidat'), ('hizmet', 'Hizmet'), ('proforma', 'Proforma'), ('alis', 'Alış')], default='satis', max_length=20, verbose_name='Fatura Türü'),
        ),
    ]
