# Generated by Django 6.1.1 on 2026-09-22 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_alter_fatura_fatura_turu'),
        ('purchasing', '0003_stokhesapesleme'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturakalemi',
            name='kaynak_kabul_kalemi',
            field=models.ForeignKey(blank=True, help_text='Satın alma/iade faturasında KDV ve fiyat snapshot kaynağı (FAZ 6B).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fatura_kalemleri', to='purchasing.malkabulkalemi', verbose_name='Kaynak Kabul Kalemi'),
        ),
    ]
