# Generated by Django 6.1.1 on 2026-09-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Firma Adı')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Kısa Ad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('max_users', models.PositiveIntegerField(default=5, verbose_name='Maksimum Kullanıcı')),
                ('max_projects', models.PositiveIntegerField(default=1, verbose_name='Maksimum Proje')),
                ('max_storage_gb', models.PositiveIntegerField(default=5, verbose_name='Maksimum Depolama (GB)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenantlar',
                'ordering': ['name'],
            },
        ),
    ]
