# Generated by Django 6.1.1 on 2026-09-17 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tenants', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('islem_türü', models.CharField(choices=[('CREATE', 'Yaratma'), ('UPDATE', 'Güncelleme'), ('DELETE', 'Fiziksel Silme (iptal deseni)'), ('REVERSE', 'Ters Kayıt'), ('CORRECTION', 'Düzeltme'), ('LOGIN', 'Giriş'), ('LOGOUT', 'Çıkış')], max_length=20, verbose_name='İşlem Türü')),
                ('nesne_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nesne ID')),
                ('eski_değer', models.TextField(blank=True, verbose_name='Eski Değer')),
                ('yeni_değer', models.TextField(blank=True, verbose_name='Yeni Değer')),
                ('ip_adresi', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('oturum_kişi', models.CharField(blank=True, max_length=100, verbose_name='Oturum/Kişi Bilgisi')),
                ('sebep', models.CharField(blank=True, max_length=255, verbose_name='Sebep/Açıklama')),
                ('içerik_türü', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='İçerik Türü')),
                ('kullanıcı', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logları',
                'ordering': ['-tarih'],
                'indexes': [models.Index(fields=['islem_türü', 'tarih'], name='audit_audit_islem_t_e4cdb5_idx'), models.Index(fields=['içerik_türü', 'nesne_id'], name='audit_audit_içerik__90d01a_idx'), models.Index(fields=['kullanıcı', 'tarih'], name='audit_audit_kullanı_339539_idx')],
            },
        ),
    ]
