# Generated by Django 6.1.1 on 2026-09-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='correlation_id',
            field=models.CharField(blank=True, help_text='İstek zincirini loglarla ilişkilendirir (FAZ 6F-2).', max_length=64, null=True, verbose_name='Korelasyon ID'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='islem_türü',
            field=models.CharField(choices=[('CREATE', 'Yaratma'), ('UPDATE', 'Güncelleme'), ('DELETE', 'Fiziksel Silme (iptal deseni)'), ('REVERSE', 'Ters Kayıt'), ('CORRECTION', 'Düzeltme'), ('LOGIN', 'Giriş'), ('LOGOUT', 'Çıkış'), ('REJECTED', 'Reddedilen İşlem')], max_length=20, verbose_name='İşlem Türü'),
        ),
    ]
