--
-- PostgreSQL database dump
--

\restrict q1Gw8tsOQeY6Dag9v5dEpNt8xzcw2yyshzaCW3fPCIGNbNk2NvPxC5tUr7nUThR

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: app_mevcut_tenant(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.app_mevcut_tenant() RETURNS bigint
    LANGUAGE sql STABLE
    AS $$
    SELECT NULLIF(current_setting('app.current_tenant', true), '')::bigint;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounting_fissatiri; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounting_fissatiri (
    id bigint NOT NULL,
    fis_id bigint NOT NULL,
    hesap_id bigint NOT NULL,
    borc numeric(15,2) NOT NULL,
    alacak numeric(15,2) NOT NULL,
    aciklama character varying(255) NOT NULL
);


--
-- Name: accounting_fissatiri_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounting_fissatiri ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounting_fissatiri_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounting_hesapplani; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounting_hesapplani (
    id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    kod character varying(20) NOT NULL,
    ad character varying(200) NOT NULL,
    tip character varying(10) NOT NULL,
    is_active boolean NOT NULL
);


--
-- Name: accounting_hesapplani_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounting_hesapplani ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounting_hesapplani_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounting_muhasebefisi; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounting_muhasebefisi (
    id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    fis_no character varying(30) NOT NULL,
    fis_tarihi date NOT NULL,
    aciklama character varying(255) NOT NULL,
    durum character varying(10) NOT NULL,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: accounting_muhasebefisi_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounting_muhasebefisi ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounting_muhasebefisi_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cari_cari; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cari_cari (
    id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    ad character varying(255) NOT NULL,
    tip character varying(20) NOT NULL,
    tur character varying(20) NOT NULL,
    vergi_no character varying(10) NOT NULL,
    vergi_dairesi character varying(150) NOT NULL,
    telefon character varying(20) NOT NULL,
    iban character varying(34) NOT NULL,
    adres text NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: cari_cari_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cari_cari ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cari_cari_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cari_carihareket; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cari_carihareket (
    id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    cari_id bigint NOT NULL,
    yon character varying(10) NOT NULL,
    tutar numeric(15,2) NOT NULL,
    aciklama character varying(255) NOT NULL,
    islem_tarihi date NOT NULL,
    is_cancelled boolean NOT NULL,
    iptal_nedeni character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: cari_carihareket_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cari_carihareket ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cari_carihareket_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: construction_hakedis; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.construction_hakedis (
    id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    proje_id bigint NOT NULL,
    donem character varying(7) NOT NULL,
    cari_id bigint,
    durum character varying(10) NOT NULL,
    aciklama text NOT NULL,
    cari_hareket_id bigint,
    muhasebe_fisi_id bigint,
    onaylayan_id bigint,
    onay_tarihi timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: construction_hakedis_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.construction_hakedis ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.construction_hakedis_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: construction_hakedissatiri; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.construction_hakedissatiri (
    id bigint NOT NULL,
    hakedis_id bigint NOT NULL,
    poz_id bigint NOT NULL,
    miktar numeric(14,4) NOT NULL,
    birim_fiyat numeric(14,2) NOT NULL
);


--
-- Name: construction_hakedissatiri_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.construction_hakedissatiri ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.construction_hakedissatiri_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: construction_kalitekontrol; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.construction_kalitekontrol (
    id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    proje_id bigint NOT NULL,
    poz_id bigint,
    tarih date NOT NULL,
    kontrol_turu character varying(100) NOT NULL,
    kriter character varying(255) NOT NULL,
    sonuc character varying(20) NOT NULL,
    aciklama text NOT NULL,
    duzeltici_faaliyet text NOT NULL,
    created_by_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: construction_kalitekontrol_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.construction_kalitekontrol ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.construction_kalitekontrol_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: construction_malzeme; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.construction_malzeme (
    id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    malzeme_kodu character varying(30) NOT NULL,
    ad character varying(255) NOT NULL,
    birim character varying(20) NOT NULL,
    ts_no character varying(100) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: construction_malzeme_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.construction_malzeme ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.construction_malzeme_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: construction_poz; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.construction_poz (
    id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    poz_no character varying(30) NOT NULL,
    ad character varying(255) NOT NULL,
    birim character varying(20) NOT NULL,
    grup_id bigint NOT NULL,
    tip character varying(20) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: construction_poz_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.construction_poz ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.construction_poz_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: construction_pozfiyat; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.construction_pozfiyat (
    id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    poz_id bigint NOT NULL,
    yil smallint NOT NULL,
    donem character varying(20) NULL,
    birim_fiyat numeric(14,2) NOT NULL,
    kaynak_url character varying(250) NULL,
    yayin_tarihi date NULL,
    gecerlilik_tarihi date NULL,
    ice_aktarma_tarihi timestamp with time zone NOT NULL DEFAULT now(),
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT construction_pozfiyat_yil_check CHECK ((yil >= 0)),
    CONSTRAINT uniq_poz_fiyat_yil_donem UNIQUE (tenant_id, poz_id, yil, donem)
);


--
-- Name: construction_pozfiyat_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.construction_pozfiyat ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.construction_pozfiyat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: construction_pozgrubu; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.construction_pozgrubu (
    id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    kod character varying(20) NOT NULL,
    ad character varying(200) NOT NULL,
    ust_grup_id bigint,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: construction_pozgrubu_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.construction_pozgrubu ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.construction_pozgrubu_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: construction_pozmalzemeiliskisi; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.construction_pozmalzemeiliskisi (
    id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    poz_id bigint NOT NULL,
    malzeme_id bigint NOT NULL,
    miktar numeric(14,4) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT check_poz_malzeme_miktar_pozitif CHECK ((miktar > (0)::numeric))
);


--
-- Name: construction_pozmalzemeiliskisi_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.construction_pozmalzemeiliskisi ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.construction_pozmalzemeiliskisi_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: construction_pozplan; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.construction_pozplan (
    id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    proje_id bigint NOT NULL,
    poz_id bigint NOT NULL,
    yil smallint NOT NULL,
    planlanan_miktar numeric(14,4) NOT NULL,
    gercek_miktar numeric(14,4) NOT NULL,
    birim_fiyat_snapshot numeric(14,2) NOT NULL,
    aciklama text NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    planlanan_baslangic date,
    planlanan_bitis date,
    CONSTRAINT check_poz_plan_gercek_pozitif CHECK ((gercek_miktar >= (0)::numeric)),
    CONSTRAINT check_poz_plan_tarih_sirasi CHECK (((planlanan_baslangic IS NULL) OR (planlanan_bitis IS NULL) OR (planlanan_bitis >= planlanan_baslangic))),
    CONSTRAINT construction_pozplan_yil_check CHECK ((yil >= 0))
);


--
-- Name: construction_pozplan_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.construction_pozplan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.construction_pozplan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: construction_proje; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.construction_proje (
    id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    proje_kodu character varying(30) NOT NULL,
    ad character varying(255) NOT NULL,
    yapisinif_maliyet_id bigint,
    durum character varying(20) NOT NULL,
    baslangic date,
    bitis date,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: construction_proje_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.construction_proje ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.construction_proje_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: construction_santiyegunlugu; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.construction_santiyegunlugu (
    id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    proje_id bigint NOT NULL,
    tarih date NOT NULL,
    hava_durumu character varying(100) NOT NULL,
    ekip character varying(255) NOT NULL,
    yapilan_is text NOT NULL,
    sorunlar text NOT NULL,
    notlar text NOT NULL,
    created_by_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: construction_santiyegunlugu_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.construction_santiyegunlugu ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.construction_santiyegunlugu_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: construction_yapisinifibirimmaliyet; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.construction_yapisinifibirimmaliyet (
    id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    sinif_kodu character varying(10) NOT NULL,
    yil smallint NOT NULL,
    birim_maliyet numeric(15,2) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT construction_yapisinifibirimmaliyet_yil_check CHECK ((yil >= 0))
);


--
-- Name: construction_yapisinifibirimmaliyet_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.construction_yapisinifibirimmaliyet ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.construction_yapisinifibirimmaliyet_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: finance_finansalislem; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.finance_finansalislem (
    id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    hesap_id bigint NOT NULL,
    cari_id bigint,
    yon character varying(10) NOT NULL,
    tutar numeric(15,2) NOT NULL,
    islem_tarihi date NOT NULL,
    aciklama character varying(255) NOT NULL,
    is_cancelled boolean NOT NULL,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: finance_finansalislem_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.finance_finansalislem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.finance_finansalislem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: finance_kasabankahesabi; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.finance_kasabankahesabi (
    id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    kod character varying(20) NOT NULL,
    ad character varying(200) NOT NULL,
    tip character varying(15) NOT NULL,
    iban character varying(34) NOT NULL,
    para_birimi character varying(3) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: finance_kasabankahesabi_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.finance_kasabankahesabi ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.finance_kasabankahesabi_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: real_estate_realestate; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.real_estate_realestate (
    id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    ad character varying(200) NOT NULL,
    proje_id bigint,
    blok character varying(50) NOT NULL,
    kat character varying(50) NOT NULL,
    daire_no character varying(50) NOT NULL,
    brut_m2 numeric(9,2),
    durum character varying(20) NOT NULL,
    tapu_adi character varying(200) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: real_estate_realestate_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.real_estate_realestate ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.real_estate_realestate_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tenants_tenant; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tenants_tenant (
    id bigint NOT NULL,
    name character varying(150) NOT NULL,
    slug character varying(100) NOT NULL,
    is_active boolean NOT NULL,
    max_users integer NOT NULL,
    max_projects integer NOT NULL,
    max_storage_gb integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT tenants_tenant_max_projects_check CHECK ((max_projects >= 0)),
    CONSTRAINT tenants_tenant_max_storage_gb_check CHECK ((max_storage_gb >= 0)),
    CONSTRAINT tenants_tenant_max_users_check CHECK ((max_users >= 0))
);


--
-- Name: tenants_tenant_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tenants_tenant ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tenants_tenant_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    role character varying(30) NOT NULL,
    email character varying(254) NOT NULL,
    tenant_id bigint
);


--
-- Name: users_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: users_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: users_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounting_fissatiri accounting_fissatiri_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounting_fissatiri
    ADD CONSTRAINT accounting_fissatiri_pkey PRIMARY KEY (id);


--
-- Name: accounting_hesapplani accounting_hesapplani_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounting_hesapplani
    ADD CONSTRAINT accounting_hesapplani_pkey PRIMARY KEY (id);


--
-- Name: accounting_muhasebefisi accounting_muhasebefisi_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounting_muhasebefisi
    ADD CONSTRAINT accounting_muhasebefisi_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: cari_cari cari_cari_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cari_cari
    ADD CONSTRAINT cari_cari_pkey PRIMARY KEY (id);


--
-- Name: cari_carihareket cari_carihareket_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cari_carihareket
    ADD CONSTRAINT cari_carihareket_pkey PRIMARY KEY (id);


--
-- Name: construction_hakedis construction_hakedis_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_hakedis
    ADD CONSTRAINT construction_hakedis_pkey PRIMARY KEY (id);


--
-- Name: construction_hakedissatiri construction_hakedissatiri_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_hakedissatiri
    ADD CONSTRAINT construction_hakedissatiri_pkey PRIMARY KEY (id);


--
-- Name: construction_kalitekontrol construction_kalitekontrol_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_kalitekontrol
    ADD CONSTRAINT construction_kalitekontrol_pkey PRIMARY KEY (id);


--
-- Name: construction_malzeme construction_malzeme_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_malzeme
    ADD CONSTRAINT construction_malzeme_pkey PRIMARY KEY (id);


--
-- Name: construction_poz construction_poz_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_poz
    ADD CONSTRAINT construction_poz_pkey PRIMARY KEY (id);


--
-- Name: construction_pozfiyat construction_pozfiyat_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_pozfiyat
    ADD CONSTRAINT construction_pozfiyat_pkey PRIMARY KEY (id);


--
-- Name: construction_pozgrubu construction_pozgrubu_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_pozgrubu
    ADD CONSTRAINT construction_pozgrubu_pkey PRIMARY KEY (id);


--
-- Name: construction_pozmalzemeiliskisi construction_pozmalzemeiliskisi_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_pozmalzemeiliskisi
    ADD CONSTRAINT construction_pozmalzemeiliskisi_pkey PRIMARY KEY (id);


--
-- Name: construction_pozplan construction_pozplan_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_pozplan
    ADD CONSTRAINT construction_pozplan_pkey PRIMARY KEY (id);


--
-- Name: construction_proje construction_proje_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_proje
    ADD CONSTRAINT construction_proje_pkey PRIMARY KEY (id);


--
-- Name: construction_santiyegunlugu construction_santiyegunlugu_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_santiyegunlugu
    ADD CONSTRAINT construction_santiyegunlugu_pkey PRIMARY KEY (id);


--
-- Name: construction_yapisinifibirimmaliyet construction_yapisinifibirimmaliyet_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_yapisinifibirimmaliyet
    ADD CONSTRAINT construction_yapisinifibirimmaliyet_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: finance_finansalislem finance_finansalislem_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.finance_finansalislem
    ADD CONSTRAINT finance_finansalislem_pkey PRIMARY KEY (id);


--
-- Name: finance_kasabankahesabi finance_kasabankahesabi_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.finance_kasabankahesabi
    ADD CONSTRAINT finance_kasabankahesabi_pkey PRIMARY KEY (id);


--
-- Name: real_estate_realestate real_estate_realestate_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.real_estate_realestate
    ADD CONSTRAINT real_estate_realestate_pkey PRIMARY KEY (id);


--
-- Name: tenants_tenant tenants_tenant_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenants_tenant
    ADD CONSTRAINT tenants_tenant_pkey PRIMARY KEY (id);


--
-- Name: tenants_tenant tenants_tenant_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenants_tenant
    ADD CONSTRAINT tenants_tenant_slug_key UNIQUE (slug);


--
-- Name: cari_cari uniq_cari_tenant_ad; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cari_cari
    ADD CONSTRAINT uniq_cari_tenant_ad UNIQUE (tenant_id, ad);


--
-- Name: accounting_muhasebefisi uniq_fis_tenant_no; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounting_muhasebefisi
    ADD CONSTRAINT uniq_fis_tenant_no UNIQUE (tenant_id, fis_no);


--
-- Name: real_estate_realestate uniq_gayrimenkul_konum_tenant; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.real_estate_realestate
    ADD CONSTRAINT uniq_gayrimenkul_konum_tenant UNIQUE (tenant_id, blok, kat, daire_no);


--
-- Name: construction_santiyegunlugu uniq_gunluk_tenant_proje_tarih; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_santiyegunlugu
    ADD CONSTRAINT uniq_gunluk_tenant_proje_tarih UNIQUE (tenant_id, proje_id, tarih);


--
-- Name: construction_hakedissatiri uniq_hakedis_satir_hakedis_poz; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_hakedissatiri
    ADD CONSTRAINT uniq_hakedis_satir_hakedis_poz UNIQUE (hakedis_id, poz_id);


--
-- Name: construction_hakedis uniq_hakedis_tenant_proje_donem; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_hakedis
    ADD CONSTRAINT uniq_hakedis_tenant_proje_donem UNIQUE (tenant_id, proje_id, donem);


--
-- Name: accounting_hesapplani uniq_hesap_tenant_kod; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounting_hesapplani
    ADD CONSTRAINT uniq_hesap_tenant_kod UNIQUE (tenant_id, kod);


--
-- Name: finance_kasabankahesabi uniq_kasa_tenant_kod; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.finance_kasabankahesabi
    ADD CONSTRAINT uniq_kasa_tenant_kod UNIQUE (tenant_id, kod);


--
-- Name: construction_malzeme uniq_malzeme_tenant_kod; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_malzeme
    ADD CONSTRAINT uniq_malzeme_tenant_kod UNIQUE (tenant_id, malzeme_kodu);


--
-- Name: construction_pozfiyat uniq_poz_fiyat_yil; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_pozfiyat
    ADD CONSTRAINT uniq_poz_fiyat_yil UNIQUE (tenant_id, poz_id, yil);


--
-- Name: construction_pozmalzemeiliskisi uniq_poz_malzeme_tenant; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_pozmalzemeiliskisi
    ADD CONSTRAINT uniq_poz_malzeme_tenant UNIQUE (tenant_id, poz_id, malzeme_id);


--
-- Name: construction_pozplan uniq_poz_plan_tenant_proje_poz_yil; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_pozplan
    ADD CONSTRAINT uniq_poz_plan_tenant_proje_poz_yil UNIQUE (tenant_id, proje_id, poz_id, yil);


--
-- Name: construction_poz uniq_poz_tenant_no; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_poz
    ADD CONSTRAINT uniq_poz_tenant_no UNIQUE (tenant_id, poz_no);


--
-- Name: construction_pozgrubu uniq_pozgrubu_tenant_kod; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_pozgrubu
    ADD CONSTRAINT uniq_pozgrubu_tenant_kod UNIQUE (tenant_id, kod);


--
-- Name: construction_proje uniq_proje_tenant_kod; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_proje
    ADD CONSTRAINT uniq_proje_tenant_kod UNIQUE (tenant_id, proje_kodu);


--
-- Name: construction_yapisinifibirimmaliyet uniq_yapi_sinifi_yil_tenant; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_yapisinifibirimmaliyet
    ADD CONSTRAINT uniq_yapi_sinifi_yil_tenant UNIQUE (tenant_id, sinif_kodu, yil);


--
-- Name: users_user users_user_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_email_key UNIQUE (email);


--
-- Name: users_user_groups users_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_pkey PRIMARY KEY (id);


--
-- Name: users_user_groups users_user_groups_user_id_group_id_b88eab82_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_group_id_b88eab82_uniq UNIQUE (user_id, group_id);


--
-- Name: users_user users_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_pkey PRIMARY KEY (id);


--
-- Name: users_user_user_permissions users_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_permission_id_43338c45_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_permission_id_43338c45_uniq UNIQUE (user_id, permission_id);


--
-- Name: users_user users_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_username_key UNIQUE (username);


--
-- Name: accounting_fissatiri_fis_id_c9a9c0c3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounting_fissatiri_fis_id_c9a9c0c3 ON public.accounting_fissatiri USING btree (fis_id);


--
-- Name: accounting_fissatiri_hesap_id_cd5f25b3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounting_fissatiri_hesap_id_cd5f25b3 ON public.accounting_fissatiri USING btree (hesap_id);


--
-- Name: accounting_hesapplani_tenant_id_a5a7a651; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounting_hesapplani_tenant_id_a5a7a651 ON public.accounting_hesapplani USING btree (tenant_id);


--
-- Name: accounting_muhasebefisi_tenant_id_3ea15cfa; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounting_muhasebefisi_tenant_id_3ea15cfa ON public.accounting_muhasebefisi USING btree (tenant_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: cari_cari_tenant_id_a04a1d1c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX cari_cari_tenant_id_a04a1d1c ON public.cari_cari USING btree (tenant_id);


--
-- Name: cari_carihareket_cari_id_9eec71ec; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX cari_carihareket_cari_id_9eec71ec ON public.cari_carihareket USING btree (cari_id);


--
-- Name: cari_carihareket_tenant_id_1d97ab75; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX cari_carihareket_tenant_id_1d97ab75 ON public.cari_carihareket USING btree (tenant_id);


--
-- Name: construction_hakedis_cari_hareket_id_aaa8a890; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX construction_hakedis_cari_hareket_id_aaa8a890 ON public.construction_hakedis USING btree (cari_hareket_id);


--
-- Name: construction_hakedis_cari_id_dd3b9933; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX construction_hakedis_cari_id_dd3b9933 ON public.construction_hakedis USING btree (cari_id);


--
-- Name: construction_hakedis_muhasebe_fisi_id_18346f5c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX construction_hakedis_muhasebe_fisi_id_18346f5c ON public.construction_hakedis USING btree (muhasebe_fisi_id);


--
-- Name: construction_hakedis_onaylayan_id_e5b344eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX construction_hakedis_onaylayan_id_e5b344eb ON public.construction_hakedis USING btree (onaylayan_id);


--
-- Name: construction_hakedis_proje_id_34b61dd8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX construction_hakedis_proje_id_34b61dd8 ON public.construction_hakedis USING btree (proje_id);


--
-- Name: construction_hakedis_tenant_id_8cebe69d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX construction_hakedis_tenant_id_8cebe69d ON public.construction_hakedis USING btree (tenant_id);


--
-- Name: construction_hakedissatiri_hakedis_id_c1f568e7; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX construction_hakedissatiri_hakedis_id_c1f568e7 ON public.construction_hakedissatiri USING btree (hakedis_id);


--
-- Name: construction_hakedissatiri_poz_id_7095c6ab; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX construction_hakedissatiri_poz_id_7095c6ab ON public.construction_hakedissatiri USING btree (poz_id);


--
-- Name: construction_kalitekontrol_created_by_id_b5db2c43; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX construction_kalitekontrol_created_by_id_b5db2c43 ON public.construction_kalitekontrol USING btree (created_by_id);


--
-- Name: construction_kalitekontrol_poz_id_8d0121c9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX construction_kalitekontrol_poz_id_8d0121c9 ON public.construction_kalitekontrol USING btree (poz_id);


--
-- Name: construction_kalitekontrol_proje_id_ffb26eef; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX construction_kalitekontrol_proje_id_ffb26eef ON public.construction_kalitekontrol USING btree (proje_id);


--
-- Name: construction_kalitekontrol_tenant_id_04301bfd; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX construction_kalitekontrol_tenant_id_04301bfd ON public.construction_kalitekontrol USING btree (tenant_id);


--
-- Name: construction_malzeme_tenant_id_a5e97cb6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX construction_malzeme_tenant_id_a5e97cb6 ON public.construction_malzeme USING btree (tenant_id);


--
-- Name: construction_poz_grup_id_c2c1a88a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX construction_poz_grup_id_c2c1a88a ON public.construction_poz USING btree (grup_id);


--
-- Name: construction_poz_tenant_id_23dc934d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX construction_poz_tenant_id_23dc934d ON public.construction_poz USING btree (tenant_id);


--
-- Name: construction_pozfiyat_poz_id_ce491450; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX construction_pozfiyat_poz_id_ce491450 ON public.construction_pozfiyat USING btree (poz_id);


--
-- Name: construction_pozfiyat_tenant_id_2e03aaa5; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX construction_pozfiyat_tenant_id_2e03aaa5 ON public.construction_pozfiyat USING btree (tenant_id);


--
-- Name: construction_pozgrubu_tenant_id_7fb25fb0; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX construction_pozgrubu_tenant_id_7fb25fb0 ON public.construction_pozgrubu USING btree (tenant_id);


--
-- Name: construction_pozgrubu_ust_grup_id_79db60a2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX construction_pozgrubu_ust_grup_id_79db60a2 ON public.construction_pozgrubu USING btree (ust_grup_id);


--
-- Name: construction_pozmalzemeiliskisi_malzeme_id_d96ada32; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX construction_pozmalzemeiliskisi_malzeme_id_d96ada32 ON public.construction_pozmalzemeiliskisi USING btree (malzeme_id);


--
-- Name: construction_pozmalzemeiliskisi_poz_id_d6dfe714; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX construction_pozmalzemeiliskisi_poz_id_d6dfe714 ON public.construction_pozmalzemeiliskisi USING btree (poz_id);


--
-- Name: construction_pozmalzemeiliskisi_tenant_id_e57adb32; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX construction_pozmalzemeiliskisi_tenant_id_e57adb32 ON public.construction_pozmalzemeiliskisi USING btree (tenant_id);


--
-- Name: construction_pozplan_poz_id_9357e1bf; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX construction_pozplan_poz_id_9357e1bf ON public.construction_pozplan USING btree (poz_id);


--
-- Name: construction_pozplan_proje_id_f43852d8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX construction_pozplan_proje_id_f43852d8 ON public.construction_pozplan USING btree (proje_id);


--
-- Name: construction_pozplan_tenant_id_95383360; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX construction_pozplan_tenant_id_95383360 ON public.construction_pozplan USING btree (tenant_id);


--
-- Name: construction_proje_tenant_id_0406273c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX construction_proje_tenant_id_0406273c ON public.construction_proje USING btree (tenant_id);


--
-- Name: construction_proje_yapisinif_maliyet_id_63381836; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX construction_proje_yapisinif_maliyet_id_63381836 ON public.construction_proje USING btree (yapisinif_maliyet_id);


--
-- Name: construction_santiyegunlugu_created_by_id_e22ac6c0; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX construction_santiyegunlugu_created_by_id_e22ac6c0 ON public.construction_santiyegunlugu USING btree (created_by_id);


--
-- Name: construction_santiyegunlugu_proje_id_bd99cf89; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX construction_santiyegunlugu_proje_id_bd99cf89 ON public.construction_santiyegunlugu USING btree (proje_id);


--
-- Name: construction_santiyegunlugu_tenant_id_165b5c20; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX construction_santiyegunlugu_tenant_id_165b5c20 ON public.construction_santiyegunlugu USING btree (tenant_id);


--
-- Name: construction_yapisinifibirimmaliyet_tenant_id_761d6d88; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX construction_yapisinifibirimmaliyet_tenant_id_761d6d88 ON public.construction_yapisinifibirimmaliyet USING btree (tenant_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: finance_finansalislem_cari_id_5a7b4645; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX finance_finansalislem_cari_id_5a7b4645 ON public.finance_finansalislem USING btree (cari_id);


--
-- Name: finance_finansalislem_hesap_id_d78931b7; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX finance_finansalislem_hesap_id_d78931b7 ON public.finance_finansalislem USING btree (hesap_id);


--
-- Name: finance_finansalislem_tenant_id_7a5447b3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX finance_finansalislem_tenant_id_7a5447b3 ON public.finance_finansalislem USING btree (tenant_id);


--
-- Name: finance_kasabankahesabi_tenant_id_342f1b6e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX finance_kasabankahesabi_tenant_id_342f1b6e ON public.finance_kasabankahesabi USING btree (tenant_id);


--
-- Name: real_estate_realestate_proje_id_aac9098b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX real_estate_realestate_proje_id_aac9098b ON public.real_estate_realestate USING btree (proje_id);


--
-- Name: real_estate_realestate_tenant_id_77c90299; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX real_estate_realestate_tenant_id_77c90299 ON public.real_estate_realestate USING btree (tenant_id);


--
-- Name: tenants_tenant_slug_0a9b71e6_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tenants_tenant_slug_0a9b71e6_like ON public.tenants_tenant USING btree (slug varchar_pattern_ops);


--
-- Name: users_user_email_243f6e77_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_email_243f6e77_like ON public.users_user USING btree (email varchar_pattern_ops);


--
-- Name: users_user_groups_group_id_9afc8d0e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_groups_group_id_9afc8d0e ON public.users_user_groups USING btree (group_id);


--
-- Name: users_user_groups_user_id_5f6f5a90; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_groups_user_id_5f6f5a90 ON public.users_user_groups USING btree (user_id);


--
-- Name: users_user_tenant_id_3b8bb614; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_tenant_id_3b8bb614 ON public.users_user USING btree (tenant_id);


--
-- Name: users_user_user_permissions_permission_id_0b93982e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_user_permissions_permission_id_0b93982e ON public.users_user_user_permissions USING btree (permission_id);


--
-- Name: users_user_user_permissions_user_id_20aca447; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_user_permissions_user_id_20aca447 ON public.users_user_user_permissions USING btree (user_id);


--
-- Name: users_user_username_06e46fe6_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_username_06e46fe6_like ON public.users_user USING btree (username varchar_pattern_ops);


--
-- Name: accounting_fissatiri accounting_fissatiri_fis_id_c9a9c0c3_fk_accountin; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounting_fissatiri
    ADD CONSTRAINT accounting_fissatiri_fis_id_c9a9c0c3_fk_accountin FOREIGN KEY (fis_id) REFERENCES public.accounting_muhasebefisi(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounting_fissatiri accounting_fissatiri_hesap_id_cd5f25b3_fk_accountin; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounting_fissatiri
    ADD CONSTRAINT accounting_fissatiri_hesap_id_cd5f25b3_fk_accountin FOREIGN KEY (hesap_id) REFERENCES public.accounting_hesapplani(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounting_hesapplani accounting_hesapplani_tenant_id_a5a7a651_fk_tenants_tenant_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounting_hesapplani
    ADD CONSTRAINT accounting_hesapplani_tenant_id_a5a7a651_fk_tenants_tenant_id FOREIGN KEY (tenant_id) REFERENCES public.tenants_tenant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounting_muhasebefisi accounting_muhasebefisi_tenant_id_3ea15cfa_fk_tenants_tenant_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounting_muhasebefisi
    ADD CONSTRAINT accounting_muhasebefisi_tenant_id_3ea15cfa_fk_tenants_tenant_id FOREIGN KEY (tenant_id) REFERENCES public.tenants_tenant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cari_cari cari_cari_tenant_id_a04a1d1c_fk_tenants_tenant_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cari_cari
    ADD CONSTRAINT cari_cari_tenant_id_a04a1d1c_fk_tenants_tenant_id FOREIGN KEY (tenant_id) REFERENCES public.tenants_tenant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cari_carihareket cari_carihareket_cari_id_9eec71ec_fk_cari_cari_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cari_carihareket
    ADD CONSTRAINT cari_carihareket_cari_id_9eec71ec_fk_cari_cari_id FOREIGN KEY (cari_id) REFERENCES public.cari_cari(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cari_carihareket cari_carihareket_tenant_id_1d97ab75_fk_tenants_tenant_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cari_carihareket
    ADD CONSTRAINT cari_carihareket_tenant_id_1d97ab75_fk_tenants_tenant_id FOREIGN KEY (tenant_id) REFERENCES public.tenants_tenant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: construction_hakedis construction_hakedis_cari_hareket_id_aaa8a890_fk_cari_cari; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_hakedis
    ADD CONSTRAINT construction_hakedis_cari_hareket_id_aaa8a890_fk_cari_cari FOREIGN KEY (cari_hareket_id) REFERENCES public.cari_carihareket(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: construction_hakedis construction_hakedis_cari_id_dd3b9933_fk_cari_cari_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_hakedis
    ADD CONSTRAINT construction_hakedis_cari_id_dd3b9933_fk_cari_cari_id FOREIGN KEY (cari_id) REFERENCES public.cari_cari(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: construction_hakedissatiri construction_hakedis_hakedis_id_c1f568e7_fk_construct; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_hakedissatiri
    ADD CONSTRAINT construction_hakedis_hakedis_id_c1f568e7_fk_construct FOREIGN KEY (hakedis_id) REFERENCES public.construction_hakedis(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: construction_hakedis construction_hakedis_muhasebe_fisi_id_18346f5c_fk_accountin; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_hakedis
    ADD CONSTRAINT construction_hakedis_muhasebe_fisi_id_18346f5c_fk_accountin FOREIGN KEY (muhasebe_fisi_id) REFERENCES public.accounting_muhasebefisi(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: construction_hakedis construction_hakedis_onaylayan_id_e5b344eb_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_hakedis
    ADD CONSTRAINT construction_hakedis_onaylayan_id_e5b344eb_fk_users_user_id FOREIGN KEY (onaylayan_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: construction_hakedissatiri construction_hakedis_poz_id_7095c6ab_fk_construct; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_hakedissatiri
    ADD CONSTRAINT construction_hakedis_poz_id_7095c6ab_fk_construct FOREIGN KEY (poz_id) REFERENCES public.construction_poz(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: construction_hakedis construction_hakedis_proje_id_34b61dd8_fk_construction_proje_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_hakedis
    ADD CONSTRAINT construction_hakedis_proje_id_34b61dd8_fk_construction_proje_id FOREIGN KEY (proje_id) REFERENCES public.construction_proje(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: construction_hakedis construction_hakedis_tenant_id_8cebe69d_fk_tenants_tenant_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_hakedis
    ADD CONSTRAINT construction_hakedis_tenant_id_8cebe69d_fk_tenants_tenant_id FOREIGN KEY (tenant_id) REFERENCES public.tenants_tenant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: construction_kalitekontrol construction_kalitek_created_by_id_b5db2c43_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_kalitekontrol
    ADD CONSTRAINT construction_kalitek_created_by_id_b5db2c43_fk_users_use FOREIGN KEY (created_by_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: construction_kalitekontrol construction_kalitek_poz_id_8d0121c9_fk_construct; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_kalitekontrol
    ADD CONSTRAINT construction_kalitek_poz_id_8d0121c9_fk_construct FOREIGN KEY (poz_id) REFERENCES public.construction_poz(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: construction_kalitekontrol construction_kalitek_proje_id_ffb26eef_fk_construct; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_kalitekontrol
    ADD CONSTRAINT construction_kalitek_proje_id_ffb26eef_fk_construct FOREIGN KEY (proje_id) REFERENCES public.construction_proje(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: construction_kalitekontrol construction_kalitek_tenant_id_04301bfd_fk_tenants_t; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_kalitekontrol
    ADD CONSTRAINT construction_kalitek_tenant_id_04301bfd_fk_tenants_t FOREIGN KEY (tenant_id) REFERENCES public.tenants_tenant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: construction_malzeme construction_malzeme_tenant_id_a5e97cb6_fk_tenants_tenant_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_malzeme
    ADD CONSTRAINT construction_malzeme_tenant_id_a5e97cb6_fk_tenants_tenant_id FOREIGN KEY (tenant_id) REFERENCES public.tenants_tenant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: construction_poz construction_poz_grup_id_c2c1a88a_fk_construction_pozgrubu_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_poz
    ADD CONSTRAINT construction_poz_grup_id_c2c1a88a_fk_construction_pozgrubu_id FOREIGN KEY (grup_id) REFERENCES public.construction_pozgrubu(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: construction_poz construction_poz_tenant_id_23dc934d_fk_tenants_tenant_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_poz
    ADD CONSTRAINT construction_poz_tenant_id_23dc934d_fk_tenants_tenant_id FOREIGN KEY (tenant_id) REFERENCES public.tenants_tenant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: construction_pozfiyat construction_pozfiyat_poz_id_ce491450_fk_construction_poz_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_pozfiyat
    ADD CONSTRAINT construction_pozfiyat_poz_id_ce491450_fk_construction_poz_id FOREIGN KEY (poz_id) REFERENCES public.construction_poz(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: construction_pozfiyat construction_pozfiyat_tenant_id_2e03aaa5_fk_tenants_tenant_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_pozfiyat
    ADD CONSTRAINT construction_pozfiyat_tenant_id_2e03aaa5_fk_tenants_tenant_id FOREIGN KEY (tenant_id) REFERENCES public.tenants_tenant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: construction_pozgrubu construction_pozgrub_ust_grup_id_79db60a2_fk_construct; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_pozgrubu
    ADD CONSTRAINT construction_pozgrub_ust_grup_id_79db60a2_fk_construct FOREIGN KEY (ust_grup_id) REFERENCES public.construction_pozgrubu(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: construction_pozgrubu construction_pozgrubu_tenant_id_7fb25fb0_fk_tenants_tenant_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_pozgrubu
    ADD CONSTRAINT construction_pozgrubu_tenant_id_7fb25fb0_fk_tenants_tenant_id FOREIGN KEY (tenant_id) REFERENCES public.tenants_tenant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: construction_pozmalzemeiliskisi construction_pozmalz_malzeme_id_d96ada32_fk_construct; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_pozmalzemeiliskisi
    ADD CONSTRAINT construction_pozmalz_malzeme_id_d96ada32_fk_construct FOREIGN KEY (malzeme_id) REFERENCES public.construction_malzeme(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: construction_pozmalzemeiliskisi construction_pozmalz_poz_id_d6dfe714_fk_construct; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_pozmalzemeiliskisi
    ADD CONSTRAINT construction_pozmalz_poz_id_d6dfe714_fk_construct FOREIGN KEY (poz_id) REFERENCES public.construction_poz(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: construction_pozmalzemeiliskisi construction_pozmalz_tenant_id_e57adb32_fk_tenants_t; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_pozmalzemeiliskisi
    ADD CONSTRAINT construction_pozmalz_tenant_id_e57adb32_fk_tenants_t FOREIGN KEY (tenant_id) REFERENCES public.tenants_tenant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: construction_pozplan construction_pozplan_poz_id_9357e1bf_fk_construction_poz_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_pozplan
    ADD CONSTRAINT construction_pozplan_poz_id_9357e1bf_fk_construction_poz_id FOREIGN KEY (poz_id) REFERENCES public.construction_poz(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: construction_pozplan construction_pozplan_proje_id_f43852d8_fk_construction_proje_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_pozplan
    ADD CONSTRAINT construction_pozplan_proje_id_f43852d8_fk_construction_proje_id FOREIGN KEY (proje_id) REFERENCES public.construction_proje(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: construction_pozplan construction_pozplan_tenant_id_95383360_fk_tenants_tenant_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_pozplan
    ADD CONSTRAINT construction_pozplan_tenant_id_95383360_fk_tenants_tenant_id FOREIGN KEY (tenant_id) REFERENCES public.tenants_tenant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: construction_proje construction_proje_tenant_id_0406273c_fk_tenants_tenant_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_proje
    ADD CONSTRAINT construction_proje_tenant_id_0406273c_fk_tenants_tenant_id FOREIGN KEY (tenant_id) REFERENCES public.tenants_tenant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: construction_proje construction_proje_yapisinif_maliyet_id_63381836_fk_construct; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_proje
    ADD CONSTRAINT construction_proje_yapisinif_maliyet_id_63381836_fk_construct FOREIGN KEY (yapisinif_maliyet_id) REFERENCES public.construction_yapisinifibirimmaliyet(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: construction_santiyegunlugu construction_santiye_created_by_id_e22ac6c0_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_santiyegunlugu
    ADD CONSTRAINT construction_santiye_created_by_id_e22ac6c0_fk_users_use FOREIGN KEY (created_by_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: construction_santiyegunlugu construction_santiye_proje_id_bd99cf89_fk_construct; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_santiyegunlugu
    ADD CONSTRAINT construction_santiye_proje_id_bd99cf89_fk_construct FOREIGN KEY (proje_id) REFERENCES public.construction_proje(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: construction_santiyegunlugu construction_santiye_tenant_id_165b5c20_fk_tenants_t; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_santiyegunlugu
    ADD CONSTRAINT construction_santiye_tenant_id_165b5c20_fk_tenants_t FOREIGN KEY (tenant_id) REFERENCES public.tenants_tenant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: construction_yapisinifibirimmaliyet construction_yapisin_tenant_id_761d6d88_fk_tenants_t; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.construction_yapisinifibirimmaliyet
    ADD CONSTRAINT construction_yapisin_tenant_id_761d6d88_fk_tenants_t FOREIGN KEY (tenant_id) REFERENCES public.tenants_tenant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finance_finansalislem finance_finansalisle_hesap_id_d78931b7_fk_finance_k; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.finance_finansalislem
    ADD CONSTRAINT finance_finansalisle_hesap_id_d78931b7_fk_finance_k FOREIGN KEY (hesap_id) REFERENCES public.finance_kasabankahesabi(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finance_finansalislem finance_finansalislem_cari_id_5a7b4645_fk_cari_cari_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.finance_finansalislem
    ADD CONSTRAINT finance_finansalislem_cari_id_5a7b4645_fk_cari_cari_id FOREIGN KEY (cari_id) REFERENCES public.cari_cari(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finance_finansalislem finance_finansalislem_tenant_id_7a5447b3_fk_tenants_tenant_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.finance_finansalislem
    ADD CONSTRAINT finance_finansalislem_tenant_id_7a5447b3_fk_tenants_tenant_id FOREIGN KEY (tenant_id) REFERENCES public.tenants_tenant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finance_kasabankahesabi finance_kasabankahesabi_tenant_id_342f1b6e_fk_tenants_tenant_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.finance_kasabankahesabi
    ADD CONSTRAINT finance_kasabankahesabi_tenant_id_342f1b6e_fk_tenants_tenant_id FOREIGN KEY (tenant_id) REFERENCES public.tenants_tenant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: real_estate_realestate real_estate_realesta_proje_id_aac9098b_fk_construct; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.real_estate_realestate
    ADD CONSTRAINT real_estate_realesta_proje_id_aac9098b_fk_construct FOREIGN KEY (proje_id) REFERENCES public.construction_proje(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: real_estate_realestate real_estate_realestate_tenant_id_77c90299_fk_tenants_tenant_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.real_estate_realestate
    ADD CONSTRAINT real_estate_realestate_tenant_id_77c90299_fk_tenants_tenant_id FOREIGN KEY (tenant_id) REFERENCES public.tenants_tenant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_groups users_user_groups_group_id_9afc8d0e_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_group_id_9afc8d0e_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_groups users_user_groups_user_id_5f6f5a90_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_5f6f5a90_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user users_user_tenant_id_3b8bb614_fk_tenants_tenant_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_tenant_id_3b8bb614_fk_tenants_tenant_id FOREIGN KEY (tenant_id) REFERENCES public.tenants_tenant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_user_permissions users_user_user_perm_permission_id_0b93982e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_perm_permission_id_0b93982e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_20aca447_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_20aca447_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounting_fissatiri; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.accounting_fissatiri ENABLE ROW LEVEL SECURITY;

--
-- Name: accounting_hesapplani; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.accounting_hesapplani ENABLE ROW LEVEL SECURITY;

--
-- Name: accounting_muhasebefisi; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.accounting_muhasebefisi ENABLE ROW LEVEL SECURITY;

--
-- Name: cari_cari; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.cari_cari ENABLE ROW LEVEL SECURITY;

--
-- Name: cari_carihareket; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.cari_carihareket ENABLE ROW LEVEL SECURITY;

--
-- Name: construction_hakedis; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.construction_hakedis ENABLE ROW LEVEL SECURITY;

--
-- Name: construction_hakedissatiri; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.construction_hakedissatiri ENABLE ROW LEVEL SECURITY;

--
-- Name: construction_kalitekontrol; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.construction_kalitekontrol ENABLE ROW LEVEL SECURITY;

--
-- Name: construction_malzeme; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.construction_malzeme ENABLE ROW LEVEL SECURITY;

--
-- Name: construction_poz; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.construction_poz ENABLE ROW LEVEL SECURITY;

--
-- Name: construction_pozfiyat; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.construction_pozfiyat ENABLE ROW LEVEL SECURITY;

--
-- Name: construction_pozgrubu; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.construction_pozgrubu ENABLE ROW LEVEL SECURITY;

--
-- Name: construction_pozmalzemeiliskisi; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.construction_pozmalzemeiliskisi ENABLE ROW LEVEL SECURITY;

--
-- Name: construction_pozplan; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.construction_pozplan ENABLE ROW LEVEL SECURITY;

--
-- Name: construction_proje; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.construction_proje ENABLE ROW LEVEL SECURITY;

--
-- Name: construction_santiyegunlugu; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.construction_santiyegunlugu ENABLE ROW LEVEL SECURITY;

--
-- Name: construction_yapisinifibirimmaliyet; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.construction_yapisinifibirimmaliyet ENABLE ROW LEVEL SECURITY;

--
-- Name: finance_finansalislem; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.finance_finansalislem ENABLE ROW LEVEL SECURITY;

--
-- Name: finance_kasabankahesabi; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.finance_kasabankahesabi ENABLE ROW LEVEL SECURITY;

--
-- Name: real_estate_realestate; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.real_estate_realestate ENABLE ROW LEVEL SECURITY;

--
-- Name: accounting_fissatiri rls_tenant_izolasyon; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY rls_tenant_izolasyon ON public.accounting_fissatiri USING ((EXISTS ( SELECT 1
   FROM public.accounting_muhasebefisi f
  WHERE ((f.id = accounting_fissatiri.fis_id) AND (f.tenant_id = public.app_mevcut_tenant()))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM public.accounting_muhasebefisi f
  WHERE ((f.id = accounting_fissatiri.fis_id) AND (f.tenant_id = public.app_mevcut_tenant())))));


--
-- Name: accounting_hesapplani rls_tenant_izolasyon; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY rls_tenant_izolasyon ON public.accounting_hesapplani USING ((tenant_id = public.app_mevcut_tenant())) WITH CHECK ((tenant_id = public.app_mevcut_tenant()));


--
-- Name: accounting_muhasebefisi rls_tenant_izolasyon; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY rls_tenant_izolasyon ON public.accounting_muhasebefisi USING ((tenant_id = public.app_mevcut_tenant())) WITH CHECK ((tenant_id = public.app_mevcut_tenant()));


--
-- Name: cari_cari rls_tenant_izolasyon; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY rls_tenant_izolasyon ON public.cari_cari USING ((tenant_id = public.app_mevcut_tenant())) WITH CHECK ((tenant_id = public.app_mevcut_tenant()));


--
-- Name: cari_carihareket rls_tenant_izolasyon; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY rls_tenant_izolasyon ON public.cari_carihareket USING ((tenant_id = public.app_mevcut_tenant())) WITH CHECK ((tenant_id = public.app_mevcut_tenant()));


--
-- Name: construction_hakedis rls_tenant_izolasyon; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY rls_tenant_izolasyon ON public.construction_hakedis USING ((tenant_id = public.app_mevcut_tenant())) WITH CHECK ((tenant_id = public.app_mevcut_tenant()));


--
-- Name: construction_hakedissatiri rls_tenant_izolasyon; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY rls_tenant_izolasyon ON public.construction_hakedissatiri USING ((EXISTS ( SELECT 1
   FROM public.construction_hakedis h
  WHERE ((h.id = construction_hakedissatiri.hakedis_id) AND (h.tenant_id = public.app_mevcut_tenant()))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM public.construction_hakedis h
  WHERE ((h.id = construction_hakedissatiri.hakedis_id) AND (h.tenant_id = public.app_mevcut_tenant())))));


--
-- Name: construction_kalitekontrol rls_tenant_izolasyon; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY rls_tenant_izolasyon ON public.construction_kalitekontrol USING ((tenant_id = public.app_mevcut_tenant())) WITH CHECK ((tenant_id = public.app_mevcut_tenant()));


--
-- Name: construction_malzeme rls_tenant_izolasyon; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY rls_tenant_izolasyon ON public.construction_malzeme USING ((tenant_id = public.app_mevcut_tenant())) WITH CHECK ((tenant_id = public.app_mevcut_tenant()));


--
-- Name: construction_poz rls_tenant_izolasyon; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY rls_tenant_izolasyon ON public.construction_poz USING ((tenant_id = public.app_mevcut_tenant())) WITH CHECK ((tenant_id = public.app_mevcut_tenant()));


--
-- Name: construction_pozfiyat rls_tenant_izolasyon; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY rls_tenant_izolasyon ON public.construction_pozfiyat USING ((tenant_id = public.app_mevcut_tenant())) WITH CHECK ((tenant_id = public.app_mevcut_tenant()));


--
-- Name: construction_pozgrubu rls_tenant_izolasyon; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY rls_tenant_izolasyon ON public.construction_pozgrubu USING ((tenant_id = public.app_mevcut_tenant())) WITH CHECK ((tenant_id = public.app_mevcut_tenant()));


--
-- Name: construction_pozmalzemeiliskisi rls_tenant_izolasyon; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY rls_tenant_izolasyon ON public.construction_pozmalzemeiliskisi USING ((tenant_id = public.app_mevcut_tenant())) WITH CHECK ((tenant_id = public.app_mevcut_tenant()));


--
-- Name: construction_pozplan rls_tenant_izolasyon; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY rls_tenant_izolasyon ON public.construction_pozplan USING ((tenant_id = public.app_mevcut_tenant())) WITH CHECK ((tenant_id = public.app_mevcut_tenant()));


--
-- Name: construction_proje rls_tenant_izolasyon; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY rls_tenant_izolasyon ON public.construction_proje USING ((tenant_id = public.app_mevcut_tenant())) WITH CHECK ((tenant_id = public.app_mevcut_tenant()));


--
-- Name: construction_santiyegunlugu rls_tenant_izolasyon; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY rls_tenant_izolasyon ON public.construction_santiyegunlugu USING ((tenant_id = public.app_mevcut_tenant())) WITH CHECK ((tenant_id = public.app_mevcut_tenant()));


--
-- Name: construction_yapisinifibirimmaliyet rls_tenant_izolasyon; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY rls_tenant_izolasyon ON public.construction_yapisinifibirimmaliyet USING ((tenant_id = public.app_mevcut_tenant())) WITH CHECK ((tenant_id = public.app_mevcut_tenant()));


--
-- Name: finance_finansalislem rls_tenant_izolasyon; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY rls_tenant_izolasyon ON public.finance_finansalislem USING ((tenant_id = public.app_mevcut_tenant())) WITH CHECK ((tenant_id = public.app_mevcut_tenant()));


--
-- Name: finance_kasabankahesabi rls_tenant_izolasyon; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY rls_tenant_izolasyon ON public.finance_kasabankahesabi USING ((tenant_id = public.app_mevcut_tenant())) WITH CHECK ((tenant_id = public.app_mevcut_tenant()));


--
-- Name: real_estate_realestate rls_tenant_izolasyon; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY rls_tenant_izolasyon ON public.real_estate_realestate USING ((tenant_id = public.app_mevcut_tenant())) WITH CHECK ((tenant_id = public.app_mevcut_tenant()));


--
-- Name: users_user rls_tenant_izolasyon; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY rls_tenant_izolasyon ON public.users_user USING (((tenant_id = public.app_mevcut_tenant()) OR (tenant_id IS NULL))) WITH CHECK (((tenant_id = public.app_mevcut_tenant()) OR (tenant_id IS NULL)));


--
-- Name: users_user; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.users_user ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

\unrestrict q1Gw8tsOQeY6Dag9v5dEpNt8xzcw2yyshzaCW3fPCIGNbNk2NvPxC5tUr7nUThR

