# Generated by Django 6.1.1 on 2026-09-21 23:35

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('construction', '0028_merge_20260922_0206'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SatinAlmaTalebi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talep_no', models.CharField(help_text='Merkezi sayaçtan otomatik üretilir (ST-YYYY-NNNN).', max_length=30, verbose_name='Talep No')),
                ('tarih', models.DateField(default=datetime.date.today, verbose_name='Talep Tarihi')),
                ('durum', models.CharField(choices=[('taslak', 'Taslak'), ('onaya_gonderildi', 'Onaya Gönderildi'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi'), ('siparise_donustu', 'Siparişe Dönüştü'), ('iptal', 'İptal')], default='taslak', max_length=20, verbose_name='Durum')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('proje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='satin_alma_talepleri', to='construction.proje', verbose_name='Proje')),
                ('talep_sahibi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='satin_alma_talepleri', to=settings.AUTH_USER_MODEL, verbose_name='Talep Sahibi')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Satın Alma Talebi',
                'verbose_name_plural': 'Satın Alma Talepleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SatinAlmaSiparisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siparis_no', models.CharField(help_text='Merkezi sayaçtan otomatik üretilir (SS-YYYY-NNNN).', max_length=30, verbose_name='Sipariş No')),
                ('tarih', models.DateField(default=datetime.date.today, verbose_name='Sipariş Tarihi')),
                ('teslim_tarihi', models.DateField(blank=True, null=True, verbose_name='Teslim Tarihi')),
                ('para_birimi', models.CharField(choices=[('TRY', 'Türk Lirası (₺)'), ('USD', 'ABD Doları ($)'), ('EUR', 'Euro (€)')], default='TRY', max_length=3, verbose_name='Para Birimi')),
                ('kur', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Kur')),
                ('durum', models.CharField(choices=[('taslak', 'Taslak'), ('onay_bekliyor', 'Onay Bekliyor'), ('onaylandi', 'Onaylandı'), ('kismi_teslim', 'Kısmi Teslim'), ('tamamlandi', 'Tamamlandı'), ('iptal', 'İptal')], default='taslak', max_length=20, verbose_name='Durum')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('proje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='satin_alma_siparisleri', to='construction.proje', verbose_name='Proje')),
                ('tedarikci', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='satin_alma_siparisleri', to='construction.tedarikci', verbose_name='Tedarikçi')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant')),
                ('kaynak_talep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='siparisler', to='purchasing.satinalmatalebi', verbose_name='Kaynak Talep')),
            ],
            options={
                'verbose_name': 'Satın Alma Siparişi',
                'verbose_name_plural': 'Satın Alma Siparişleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SatinAlmaTalebiKalemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Miktar')),
                ('birim', models.CharField(blank=True, default='', max_length=20, verbose_name='Birim')),
                ('ihtiyac_tarihi', models.DateField(blank=True, null=True, verbose_name='İhtiyaç Tarihi')),
                ('tahmini_birim_fiyat', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Tahmini Birim Fiyat (₺)')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('mahal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='satin_alma_talep_kalemleri', to='construction.mahal', verbose_name='Mahal')),
                ('malzeme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='satin_alma_talep_kalemleri', to='construction.malzeme', verbose_name='Malzeme')),
                ('poz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='satin_alma_talep_kalemleri', to='construction.poz', verbose_name='Poz')),
                ('secili_teklif', models.ForeignKey(blank=True, help_text='Tenant/proje/malzeme uyumu zorunludur.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secili_oldugu_talep_kalemleri', to='construction.tedarikciteklifi', verbose_name='Seçili Teklif')),
                ('talep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalemler', to='purchasing.satinalmatalebi', verbose_name='Talep')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Satın Alma Talep Kalemi',
                'verbose_name_plural': 'Satın Alma Talep Kalemleri',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BelgeNumaraSayaci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belge_tipi', models.CharField(choices=[('talep', 'Satın Alma Talebi'), ('siparis', 'Satın Alma Siparişi')], max_length=20, verbose_name='Belge Tipi')),
                ('yil', models.PositiveSmallIntegerField(verbose_name='Yıl')),
                ('son_no', models.PositiveIntegerField(default=0, verbose_name='Son Numara')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Belge Numara Sayacı',
                'verbose_name_plural': 'Belge Numara Sayaçları',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'belge_tipi', 'yil'), name='uniq_belge_sayac_tenant_tip_yil')],
            },
        ),
        migrations.CreateModel(
            name='SatinAlmaSiparisiKalemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Miktar')),
                ('birim', models.CharField(blank=True, default='', max_length=20, verbose_name='Birim')),
                ('birim_fiyat', models.DecimalField(decimal_places=2, help_text='Sipariş anındaki kesin fiyat; sonradan değişmez.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Birim Fiyat')),
                ('toplam_tutar', models.DecimalField(blank=True, decimal_places=2, help_text='Miktar x birim fiyat; kayıtta otomatik hesaplanır.', max_digits=16, null=True, verbose_name='Toplam Tutar')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('kaynak_teklif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kaynak_oldugu_siparis_kalemleri', to='construction.tedarikciteklifi', verbose_name='Kaynak Teklif')),
                ('mahal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='satin_alma_siparis_kalemleri', to='construction.mahal', verbose_name='Mahal')),
                ('malzeme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='satin_alma_siparis_kalemleri', to='construction.malzeme', verbose_name='Malzeme')),
                ('poz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='satin_alma_siparis_kalemleri', to='construction.poz', verbose_name='Poz')),
                ('siparis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalemler', to='purchasing.satinalmasiparisi', verbose_name='Sipariş')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Satın Alma Sipariş Kalemi',
                'verbose_name_plural': 'Satın Alma Sipariş Kalemleri',
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('miktar__gt', 0)), name='check_siparis_kalem_miktar_pozitif'), models.CheckConstraint(condition=models.Q(('birim_fiyat__gt', 0)), name='check_siparis_kalem_fiyat_pozitif')],
            },
        ),
        migrations.AddConstraint(
            model_name='satinalmatalebi',
            constraint=models.UniqueConstraint(fields=('tenant', 'talep_no'), name='uniq_talep_tenant_no'),
        ),
        migrations.AddConstraint(
            model_name='satinalmasiparisi',
            constraint=models.UniqueConstraint(fields=('tenant', 'siparis_no'), name='uniq_siparis_tenant_no'),
        ),
        migrations.AddConstraint(
            model_name='satinalmatalebikalemi',
            constraint=models.CheckConstraint(condition=models.Q(('miktar__gt', 0)), name='check_talep_kalem_miktar_pozitif'),
        ),
    ]
