# Generated by Django 6.1.1 on 2026-09-22 00:45

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0029_santiyegunlugu_is_active'),
        ('purchasing', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='belgenumarasayaci',
            name='belge_tipi',
            field=models.CharField(choices=[('talep', 'Satın Alma Talebi'), ('siparis', 'Satın Alma Siparişi'), ('mal_kabul', 'Mal Kabul')], max_length=20, verbose_name='Belge Tipi'),
        ),
        migrations.CreateModel(
            name='Depo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=30, verbose_name='Depo Kodu')),
                ('ad', models.CharField(max_length=150, verbose_name='Depo Adı')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Depo',
                'verbose_name_plural': 'Depolar',
                'ordering': ['kod'],
            },
        ),
        migrations.CreateModel(
            name='MalKabul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belge_no', models.CharField(help_text='Merkezi sayaçtan otomatik üretilir (MK-YYYY-NNNN).', max_length=30, verbose_name='Belge No')),
                ('kabul_tarihi', models.DateField(default=datetime.date.today, verbose_name='Kabul Tarihi')),
                ('durum', models.CharField(choices=[('taslak', 'Taslak'), ('onaylandi', 'Onaylandı'), ('kismi_teslim', 'Kısmi Teslim'), ('tamamlandi', 'Tamamlandı'), ('iptal', 'İptal')], default='taslak', max_length=20, verbose_name='Durum')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mal_kabulleri_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('depo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mal_kabulleri', to='purchasing.depo', verbose_name='Depo')),
                ('proje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mal_kabulleri', to='construction.proje', verbose_name='Proje')),
                ('siparis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mal_kabulleri', to='purchasing.satinalmasiparisi', verbose_name='Satın Alma Siparişi')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mal_kabulleri_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Mal Kabul',
                'verbose_name_plural': 'Mal Kabulleri',
                'ordering': ['-kabul_tarihi', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MalKabulKalemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siparis_miktari', models.DecimalField(decimal_places=4, help_text='Sipariş kaleminden kopyalanan miktar (snapshot).', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Sipariş Miktarı')),
                ('kabul_miktari', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Kabul Miktarı')),
                ('red_miktari', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Red Miktarı')),
                ('birim', models.CharField(blank=True, default='', max_length=20, verbose_name='Birim')),
                ('birim_fiyat_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Sipariş kalemindeki birim fiyatın kopyası (mal kabul anında).', max_digits=14, verbose_name='Birim Fiyat Snapshot')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('mal_kabul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalemler', to='purchasing.malkabul', verbose_name='Mal Kabul')),
                ('malzeme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mal_kabul_kalemleri', to='construction.malzeme', verbose_name='Malzeme')),
                ('siparis_kalemi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mal_kabul_kalemleri', to='purchasing.satinalmasiparisikalemi', verbose_name='Sipariş Kalemi')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Mal Kabul Kalemi',
                'verbose_name_plural': 'Mal Kabul Kalemleri',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StokHareketi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hareket_tipi', models.CharField(choices=[('giris', 'Giriş'), ('cikis', 'Çıkış'), ('transfer', 'Transfer'), ('iade', 'İade'), ('fire', 'Fire'), ('sayim', 'Sayım'), ('duzeltme', 'Düzeltme')], max_length=20, verbose_name='Hareket Tipi')),
                ('miktar', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Miktar')),
                ('birim', models.CharField(blank=True, default='', max_length=20, verbose_name='Birim')),
                ('maliyet', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Hareket anındaki birim maliyet (sipariş fiyatı snapshotu; değerleme yok).', max_digits=14, verbose_name='Birim Maliyet')),
                ('tarih', models.DateField(default=datetime.date.today, verbose_name='Hareket Tarihi')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('kaynak_belge_tipi', models.CharField(blank=True, default='', max_length=50, verbose_name='Kaynak Belge Tipi')),
                ('kaynak_belge_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Kaynak Belge ID')),
                ('kaynak_belge_kalem_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Kaynak Belge Kalem ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stok_hareketleri_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('depo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stok_hareketleri', to='purchasing.depo', verbose_name='Depo')),
                ('mahal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stok_hareketleri', to='construction.mahal', verbose_name='Mahal')),
                ('malzeme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stok_hareketleri', to='construction.malzeme', verbose_name='Malzeme')),
                ('poz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stok_hareketleri', to='construction.poz', verbose_name='Poz')),
                ('proje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stok_hareketleri', to='construction.proje', verbose_name='Proje')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Stok Hareketi',
                'verbose_name_plural': 'Stok Hareketleri',
                'ordering': ['-tarih', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='depo',
            constraint=models.UniqueConstraint(fields=('tenant', 'kod'), name='uniq_depo_tenant_kod'),
        ),
        migrations.AddConstraint(
            model_name='malkabul',
            constraint=models.UniqueConstraint(fields=('tenant', 'belge_no'), name='uniq_mal_kabul_tenant_belge_no'),
        ),
        migrations.AddConstraint(
            model_name='malkabul',
            constraint=models.CheckConstraint(condition=models.Q(('durum__in', ['taslak', 'onaylandi', 'kismi_teslim', 'tamamlandi', 'iptal'])), name='check_mal_kabul_durum_gecerli'),
        ),
        migrations.AddConstraint(
            model_name='malkabulkalemi',
            constraint=models.CheckConstraint(condition=models.Q(('kabul_miktari__gte', 0)), name='check_mal_kabul_kalem_kabul_miktar_negatif_olmaz'),
        ),
        migrations.AddConstraint(
            model_name='malkabulkalemi',
            constraint=models.CheckConstraint(condition=models.Q(('red_miktari__gte', 0)), name='check_mal_kabul_kalem_red_miktar_negatif_olmaz'),
        ),
        migrations.AddConstraint(
            model_name='malkabulkalemi',
            constraint=models.CheckConstraint(condition=models.Q(('kabul_miktari__gt', 0), ('red_miktari__gt', 0), _connector='OR'), name='check_mal_kabul_kalem_en_az_bir_miktar'),
        ),
        migrations.AddConstraint(
            model_name='stokhareketi',
            constraint=models.CheckConstraint(condition=models.Q(('miktar__gt', 0)), name='check_stok_hareketi_miktar_pozitif'),
        ),
        migrations.AddConstraint(
            model_name='stokhareketi',
            constraint=models.CheckConstraint(condition=models.Q(('maliyet__gte', 0)), name='check_stok_hareketi_maliyet_negatif_olmaz'),
        ),
        migrations.AddConstraint(
            model_name='stokhareketi',
            constraint=models.UniqueConstraint(condition=models.Q(('kaynak_belge_tipi', 'MalKabul'), ('is_active', True)), fields=('kaynak_belge_tipi', 'kaynak_belge_id', 'kaynak_belge_kalem_id'), name='uniq_stok_hareketi_mal_kabul_kalem'),
        ),
    ]
