# Generated by Django 6.1.1 on 2026-09-22 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_100_smoke_kasa_hesabi'),
        ('construction', '0030_tedarikci_cari'),
        ('purchasing', '0002_alter_belgenumarasayaci_belge_tipi_depo_malkabul_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StokHesapEsleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hesap_turu', models.CharField(choices=[('stok', 'Stok Hesabı'), ('kdv', 'KDV Hesabı')], max_length=10, verbose_name='Hesap Türü')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('hesap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stok_eslemeleri', to='accounting.hesapplani', verbose_name='Hesap')),
                ('malzeme', models.ForeignKey(blank=True, help_text='Boş bırakılırsa tenant varsayılanı olur.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hesap_eslemeleri', to='construction.malzeme', verbose_name='Malzeme')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Stok Hesap Eşlemesi',
                'verbose_name_plural': 'Stok Hesap Eşlemeleri',
                'ordering': ['hesap_turu', 'malzeme__malzeme_kodu'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('malzeme__isnull', True)), fields=('tenant', 'hesap_turu'), name='uniq_stok_hesap_varsayilan'), models.UniqueConstraint(condition=models.Q(('malzeme__isnull', False)), fields=('tenant', 'malzeme', 'hesap_turu'), name='uniq_stok_hesap_malzeme')],
            },
        ),
    ]
