# Generated by Django 6.1.1 on 2026-09-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_stokhesapesleme'),
    ]

    operations = [
        migrations.AddField(
            model_name='malkabulkalemi',
            name='kdv_orani',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kaleme özel KDV oranı (FAZ 6C); boşsa tenant VARSAYILAN profili → %20 uygulanır.', max_digits=5, null=True, verbose_name='KDV (%)'),
        ),
    ]
