import os
views_dir = r"c:\proje\emlakpython\frontend\src\views\insaat\yfk"
f = open(os.path.join(views_dir, "YillikPozGuncelle.vue"), "a", encoding="utf-8")
f.write("\n<script setup>\n")
f.write("import { ref, reactive, computed, onMounted } from 'vue'\n")
f.write("import { useInsaatStore } from '@/stores/insaat'\n")
f.write("import { useToast } from '@/composables/useToast'\n")
f.write("import LoadingSpinner from '@/components/ui/LoadingSpinner.vue'\n")
f.write("\nconst insaatStore = useInsaatStore()\n")
f.write("const toast = useToast()\n")
f.write("\nconst loading = ref(false)\n")
f.write("const importForm = reactive({\n")
f.write("  yil: new Date().getFullYear(),\n")
f.write("  kaynak: '',\n")
f.write("  kaynak_url: '',\n")
f.write("  yayin_tarihi: '',\n")
f.write("})\n")
f.write("const selectedFile = ref(null)\n")
f.write("const importResult = ref(null)\n")
f.write("\nconst pozList = ref([])\n")
f.write("const searchQuery = ref('')\n")
f.write("const filterYil = ref('')\n")
f.write("const selectedPoz = ref(null)\n")
f.write("const availableYears = ref([])\n")
f.write("const pagination = reactive({ page: 1, pageSize: 20, total: 0 })\n")
f.write("\nconst filteredPozList = computed(() => {\n")
f.write("  let result = pozList.value\n")
f.write("  if (searchQuery.value) {\n")
f.write("    const q = searchQuery.value.toLowerCase()\n")
f.write("    result = result.filter(p => p.poz_no.toLowerCase().includes(q) || p.ad.toLowerCase().includes(q) || p.grup_kodu.toLowerCase().includes(q))\n")
f.write("  }\n")
f.write("  if (filterYil.value) {\n")
f.write("    result = result.filter(p => p.yil == filterYil.value)\n")
f.write("  }\n")
f.write("  return result\n")
f.write("})\n")
f.write("\nconst degisiklikTuruClass = (tur) => {\n")
f.write("  const map = { YENI: 'badge-primary', GUNCELLENDI: 'badge-warning', SILINDI: 'badge-danger', DEGISIKLIK_YOK: 'badge-secondary' }\n")
f.write("  return map[tur] || 'badge-secondary'\n")
f.write("}\n")
f.write("\nconst formatCurrency = (val) => {\n")
f.write("  if (!val) return '-'\n")
f.write("  return new Intl.NumberFormat('tr-TR', { style: 'currency', currency: 'TRY', minimumFractionDigits: 2 }).format(val)\n")
f.write("}\n")
f.write("\nconst formatStatKey = (key) => {\n")
f.write("  const map = { created: 'Oluşturulan', updated: 'Güncellenen', skipped: 'Atlanan', errors: 'Hatalı' }\n")
f.write("  return map[key] || key\n")
f.write("}\n")
f.write("\nonMounted(async () => {\n")
f.write("  await loadPozList()\n")
f.write("  await loadAvailableYears()\n")
f.write("})\n")
f.write("\nasync function loadPozList() {\n")
f.write("  loading.value = true\n")
f.write("  try {\n")
f.write("    const res = await insaatStore.fetchYfkYillikPozlar({ page: pagination.page, page_size: pagination.pageSize, yil: filterYil.value || undefined, search: searchQuery.value || undefined })\n")
f.write("    pozList.value = res.results || res\n")
f.write("    pagination.total = res.count || res.length\n")
f.write("  } catch (e) {\n")
f.write("    toast.error('Poz listesi yüklenemedi')\n")
f.write("  } finally {\n")
f.write("    loading.value = false\n")
f.write("  }\n")
f.write("}\n")
f.write("\nasync function loadAvailableYears() {\n")
f.write("  try {\n")
f.write("    const res = await insaatStore.fetchYfkYillikPozlar({ page_size: 1000 })\n")
f.write("    const years = [...new Set((res.results || res).map(p => p.yil).filter(Boolean))].sort((a, b) => b - a)\n")
f.write("    availableYears.value = years\n")
f.write("  } catch (e) {}\n")
f.write("}\n")
f.write("\nasync function onFileSelect(e) {\n")
f.write("  selectedFile.value = e.target.files[0]\n")
f.write("}\n")
f.write("\nasync function handleImport() {\n")
f.write("  if (!selectedFile.value) { toast.error('CSV dosyası seçin'); return }\n")
f.write("  loading.value = true\n")
f.write("  importResult.value = null\n")
f.write("  try {\n")
f.write("    const formData = new FormData()\n")
f.write("    formData.append('file', selectedFile.value)\n")
f.write("    formData.append('yil', importForm.yil)\n")
f.write("    formData.append('kaynak', importForm.kaynak)\n")
f.write("    formData.append('kaynak_url', importForm.kaynak_url)\n")
f.write("    formData.append('yayin_tarihi', importForm.yayin_tarihi)\n")
f.write("    const res = await insaatStore.importYfkYillikPoz(formData)\n")
f.write("    importResult.value = { success: true, stats: res, errors: [] }\n")
f.write("    toast.success('İçe aktarma tamamlandı')\n")
f.write("    await loadPozList()\n")
f.write("    await loadAvailableYears()\n")
f.write("    selectedFile.value = null\n")
f.write("    importForm.kaynak = ''\n")
f.write("    importForm.kaynak_url = ''\n")
f.write("    importForm.yayin_tarihi = ''\n")
f.write("  } catch (e) {\n")
f.write("    importResult.value = { success: false, stats: {}, errors: [e.response?.data?.detail || e.message || 'Bilinmeyen hata'] }\n")
f.write("    toast.error('İçe aktarma başarısız')\n")
f.write("  } finally {\n")
f.write("    loading.value = false\n")
f.write("  }\n")
f.write("}\n")
f.write("\nasync function downloadTemplate() {\n")
f.write("  try {\n")
f.write("    const blob = await insaatStore.downloadYfkYillikTemplate()\n")
f.write("    const url = window.URL.createObjectURL(blob)\n")
f.write("    const a = document.createElement('a')\n")
f.write("    a.href = url\n")
f.write("    a.download = 'yfk_yillik_poz_template.csv'\n")
f.write("    a.click()\n")
f.write("    window.URL.revokeObjectURL(url)\n")
f.write("  } catch (e) { toast.error('Şablon indirilemedi') }\n")
f.write("}\n")
f.write("\nasync function showPozDetail(poz) {\n")
f.write("  loading.value = true\n")
f.write("  try {\n")
f.write("    const detail = await insaatStore.fetchYfkYillikPozDetail(poz.id)\n")
f.write("    selectedPoz.value = detail\n")
f.write("  } catch (e) { toast.error('Detay yüklenemedi') }\n")
f.write("  finally { loading.value = false }\n")
f.write("}\n")
f.write("\nconst Math = window.Math\n")
f.write("</script>\n")
f.close()
print("Script section done")