import os
views_dir = r"c:\proje\emlakpython\frontend\src\views\insaat\yfk"
f = open(os.path.join(views_dir, "AnalizGuncelle.vue"), "w", encoding="utf-8")
f.write("<template>\n")
f.write("  <div class=\"p-4\">\n")
f.write("    <div class=\"mb-6\">\n")
f.write("      <h2 class=\"text-xl font-bold mb-2\">Analiz (Islem) Guncelleme</h2>\n")
f.write("      <p class=\"text-gray-600\">YFK analiz/islem verilerini ice aktar veya guncelleyin.</p>\n")
f.write("    </div>\n")
f.write("    <div class=\"card mb-6\">\n")
f.write("      <div class=\"card-header\"><h3 class=\"card-title\">Analiz Verisi Yukle</h3></div>\n")
f.write("      <div class=\"card-body\">\n")
f.write("        <form @submit.prevent=\"handleImport\">\n")
f.write("          <div class=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-4\">\n")
f.write("            <div><label class=\"block text-sm font-medium mb-1\">Yil *</label><input v-model.number=\"importForm.yil\" type=\"number\" min=\"2020\" max=\"2030\" class=\"input w-full\" required /></div>\n")
f.write("            <div><label class=\"block text-sm font-medium mb-1\">Donem (Ay)</label><select v-model.number=\"importForm.donem\" class=\"input w-full\"><option value=\"\">Yillik</option><option v-for=\"n in 12\" :key=\"n\" :value=\"n\">{{ n }}</option></select></div>\n")
f.write("            <div><label class=\"block text-sm font-medium mb-1\">Kaynak</label><input v-model=\"importForm.kaynak\" type=\"text\" placeholder=\"Orn. YFK 2026 Analiz Tebligi\" class=\"input w-full\" /></div>\n")
f.write("            <div><label class=\"block text-sm font-medium mb-1\">Kaynak URL</label><input v-model=\"importForm.kaynak_url\" type=\"url\" placeholder=\"https://...\" class=\"input w-full\" /></div>\n")
f.write("          </div>\n")
f.close()
print("Part 1 done")