import os
views_dir = r"c:\proje\emlakpython\frontend\src\views\insaat\yfk"
f = open(os.path.join(views_dir, "AylikFiyatGuncelle.vue"), "a", encoding="utf-8")
f.write("\n<script setup>\n")
f.write("import { ref, reactive, computed, onMounted } from 'vue'\n")
f.write("import { useInsaatStore } from '@/stores/insaat'\n")
f.write("import { useToast } from '@/composables/useToast'\n")
f.write("import LoadingSpinner from '@/components/ui/LoadingSpinner.vue'\n\n")
f.write("const insaatStore = useInsaatStore()\n")
f.write("const toast = useToast()\n\n")
f.write("const loading = ref(false)\n")
f.write("const importForm = reactive({\n")
f.write("  yil: new Date().getFullYear(),\n")
f.write("  donem: new Date().getMonth() + 1,\n")
f.write("  kaynak: '',\n")
f.write("  kaynak_url: '',\n")
f.write("})\n")
f.write("const selectedFile = ref(null)\n")
f.write("const importResult = ref(null)\n\n")
f.write("const fiyatList = ref([])\n")
f.write("const searchQuery = ref('')\n")
f.write("const filterYil = ref('')\n")
f.write("const filterDonem = ref('')\n")
f.write("const selectedFiyat = ref(null)\n")
f.write("const availableYears = ref([])\n")
f.write("const pagination = reactive({ page: 1, pageSize: 20, total: 0 })\n\n")
f.write("const filteredFiyatList = computed(() => {\n")
f.write("  let result = fiyatList.value\n")
f.write("  if (searchQuery.value) {\n")
f.write("    const q = searchQuery.value.toLowerCase()\n")
f.write("    result = result.filter(f => f.poz_no.toLowerCase().includes(q) || f.ad.toLowerCase().includes(q) || f.grup_kodu.toLowerCase().includes(q))\n")
f.write("  }\n")
f.write("  if (filterYil.value) result = result.filter(f => f.yil == filterYil.value)\n")
f.write("  if (filterDonem.value) result = result.filter(f => f.donem == filterDonem.value)\n")
f.write("  return result\n")
f.write("})\n\n")
f.write("const formatCurrency = (val) => {\n")
f.write("  if (!val) return '-'\n")
f.write("  return new Intl.NumberFormat('tr-TR', { style: 'currency', currency: 'TRY', minimumFractionDigits: 2 }).format(val)\n")
f.write("}\n")
f.write("const formatStatKey = (key) => {\n")
f.write("  const map = { created: 'Olusturulan', updated: 'Guncellenen', skipped: 'Atlanan', errors: 'Hatali' }\n")
f.write("  return map[key] || key\n")
f.write("}\n\n")
f.write("onMounted(async () => {\n")
f.write("  await loadFiyatList()\n")
f.write("  await loadAvailableYears()\n")
f.write("})\n\n")
f.write("async function loadFiyatList() {\n")
f.write("  loading.value = true\n")
f.write("  try {\n")
f.write("    const res = await insaatStore.fetchYfkFiyatlar({ page: pagination.page, page_size: pagination.pageSize, yil: filterYil.value || undefined, donem: filterDonem.value || undefined, search: searchQuery.value || undefined })\n")
f.write("    fiyatList.value = res.results || res\n")
f.write("    pagination.total = res.count || res.length\n")
f.write("  } catch (e) {\n")
f.write("    toast.error('Fiyat listesi yuklenemedi')\n")
f.write("  } finally {\n")
f.write("    loading.value = false\n")
f.write("  }\n")
f.write("}\n\n")
f.write("async function loadAvailableYears() {\n")
f.write("  try {\n")
f.write("    const res = await insaatStore.fetchYfkFiyatlar({ page_size: 1000 })\n")
f.write("    const years = [...new Set((res.results || res).map(f => f.yil).filter(Boolean))].sort((a, b) => b - a)\n")
f.write("    availableYears.value = years\n")
f.write("  } catch (e) {}\n")
f.write("}\n\n")
f.write("async function onFileSelect(e) {\n")
f.write("  selectedFile.value = e.target.files[0]\n")
f.write("}\n\n")
f.write("async function handleImport() {\n")
f.write("  if (!selectedFile.value) { toast.error('CSV dosyasi secin'); return }\n")
f.write("  loading.value = true\n")
f.write("  importResult.value = null\n")
f.write("  try {\n")
f.write("    const formData = new FormData()\n")
f.write("    formData.append('file', selectedFile.value)\n")
f.write("    formData.append('yil', importForm.yil)\n")
f.write("    formData.append('donem', importForm.donem)\n")
f.write("    formData.append('kaynak', importForm.kaynak)\n")
f.write("    formData.append('kaynak_url', importForm.kaynak_url)\n")
f.write("    const res = await insaatStore.importYfkAylikFiyat(formData)\n")
f.write("    importResult.value = { success: true, stats: res, errors: [] }\n")
f.write("    toast.success('Ice aktarma tamamlandi')\n")
f.write("    await loadFiyatList()\n")
f.write("    await loadAvailableYears()\n")
f.write("    selectedFile.value = null\n")
f.write("    importForm.kaynak = ''\n")
f.write("    importForm.kaynak_url = ''\n")
f.write("  } catch (e) {\n")
f.write("    importResult.value = { success: false, stats: {}, errors: [e.response?.data?.detail || e.message || 'Bilinmeyen hata'] }\n")
f.write("    toast.error('Ice aktarma basarisiz')\n")
f.write("  } finally {\n")
f.write("    loading.value = false\n")
f.write("  }\n")
f.write("}\n\n")
f.write("async function downloadTemplate() {\n")
f.write("  try {\n")
f.write("    const blob = await insaatStore.downloadYfkAylikFiyatTemplate()\n")
f.write("    const url = window.URL.createObjectURL(blob)\n")
f.write("    const a = document.createElement('a')\n")
f.write("    a.href = url\n")
f.write("    a.download = 'yfk_aylik_fiyat_template.csv'\n")
f.write("    a.click()\n")
f.write("    window.URL.revokeObjectURL(url)\n")
f.write("  } catch (e) { toast.error('Sablon indirilemedi') }\n")
f.write("}\n\n")
f.write("async function showFiyatDetail(fiyat) {\n")
f.write("  loading.value = true\n")
f.write("  try {\n")
f.write("    const detail = await insaatStore.fetchYfkFiyatDetail(fiyat.id)\n")
f.write("    selectedFiyat.value = detail\n")
f.write("  } catch (e) { toast.error('Detay yuklenemedi') }\n")
f.write("  finally { loading.value = false }\n")
f.write("}\n\n")
f.write("const Math = window.Math\n")
f.write("</script>\n")
f.close()
print("Script section done")