import os

views_dir = r"c:\proje\emlakpython\frontend\src\views\insaat\yfk"

# Write the template content
with open(os.path.join(views_dir, "YillikPozGuncelle.vue"), "w", encoding="utf-8") as f:
    f.write("<template>\n")
    f.write("  <div class=\"p-4\">\n")
    f.write("    <div class=\"mb-6\">\n")
    f.write("      <h2 class=\"text-xl font-bold mb-2\">Yıllık Poz Güncelleme</h2>\n")
    f.write("      <p class=\"text-gray-600\">YFK yıllık poz verilerini içe aktar veya güncelleyin.</p>\n")
    f.write("    </div>\n\n")
    f.write("    <div class=\"card mb-6\">\n")
    f.write("      <div class=\"card-header\">\n")
    f.write("        <h3 class=\"card-title\">Yıllık Poz Verisi Yükle</h3>\n")
    f.write("      </div>\n")
    f.write("      <div class=\"card-body\">\n")
    f.write("        <form @submit.prevent=\"handleImport\">\n")
    f.write("          <div class=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-4\">\n")
    f.write("            <div><label class=\"block text-sm font-medium mb-1\">Yıl *</label><input v-model.number=\"importForm.yil\" type=\"number\" min=\"2020\" max=\"2030\" class=\"input w-full\" required /></div>\n")
    f.write("            <div><label class=\"block text-sm font-medium mb-1\">Kaynak</label><input v-model=\"importForm.kaynak\" type=\"text\" placeholder=\"Örn. YFK 2026 Tebliği\" class=\"input w-full\" /></div>\n")
    f.write("            <div><label class=\"block text-sm font-medium mb-1\">Kaynak URL</label><input v-model=\"importForm.kaynak_url\" type=\"url\" placeholder=\"https://...\" class=\"input w-full\" /></div>\n")
    f.write("            <div><label class=\"block text-sm font-medium mb-1\">Yayın Tarihi</label><input v-model=\"importForm.yayin_tarihi\" type=\"date\" class=\"input w-full\" /></div>\n")
    f.write("          </div>\n\n")
    f.write("          <div class=\"mb-4\">\n")
    f.write("            <label class=\"block text-sm font-medium mb-1\">CSV Dosyası *</label>\n")
    f.write("            <input ref=\"fileInput\" type=\"file\" accept=\".csv\" @change=\"onFileSelect\" class=\"input w-full\" required />\n")
    f.write("            <p class=\"text-sm text-gray-500 mt-1\">CSV sütunları: poz_no, ad, birim, grup_kodu, grup_adi, aciklama, birim_fiyat, kaynak, kaynak_url, yayin_tarihi, gecerlilik_baslangic, gecerlilik_bitis</p>\n")
    f.write("          </div>\n\n")
    f.write("          <div class=\"flex gap-2\">\n")
    f.write("            <button type=\"submit\" :disabled=\"loading\" class=\"btn btn-primary\"><LoadingSpinner v-if=\"loading\" class=\"mr-2 h-4 w-4\" />{{ loading ? 'İçe Aktarılıyor...' : 'CSV İçe Aktar' }}</button>\n")
    f.write("            <button type=\"button\" @click=\"downloadTemplate\" class=\"btn btn-secondary\">Şablon İndir</button>\n")
    f.write("          </div>\n")
    f.write("        </form>\n\n")
    f.write("        <div v-if=\"importResult\" class=\"mt-4 p-4 rounded\" :class=\"importResult.success ? 'bg-green-50 border border-green-200' : 'bg-red-50 border border-red-200'\">\n")
    f.write("          <h4 class=\"font-medium\" :class=\"importResult.success ? 'text-green-800' : 'text-red-800'\">{{ importResult.success ? '✓ İçe Aktarma Başarılı' : '✗ İçe Aktarma Başarısız' }}</h4>\n")
    f.write("          <ul class=\"mt-2 text-sm space-y-1\">\n")
    f.write("            <li v-for=\"(value, key) in importResult.stats\" :key=\"key\"><strong>{{ formatStatKey(key) }}:</strong> {{ value }}</li>\n")
    f.write("            <li v-if=\"importResult.errors && importResult.errors.length\"><strong>Hatalar:</strong><ul class=\"ml-4 list-disc\"><li v-for=\"(err, idx) in importResult.errors\" :key=\"idx\" class=\"text-red-600\">{{ err }}</li></ul></li>\n")
    f.write("          </ul>\n")
    f.write("        </div>\n")
    f.write("      </div>\n")
    f.write("    </div>\n")
print("Part 1 done")