import os
views_dir = r"c:\proje\emlakpython\frontend\src\views\insaat\yfk"
f = open(os.path.join(views_dir, "DegisenPozlar.vue"), "a", encoding="utf-8")
f.write("\n<script setup>\n")
f.write("import { ref, reactive, computed, onMounted } from 'vue'\n")
f.write("import { useInsaatStore } from '@/stores/insaat'\n")
f.write("import { useToast } from '@/composables/useToast'\n")
f.write("import LoadingSpinner from '@/components/ui/LoadingSpinner.vue'\n\n")
f.write("const insaatStore = useInsaatStore()\n")
f.write("const toast = useToast()\n\n")
f.write("const loading = ref(false)\n")
f.write("const pozList = ref([])\n")
f.write("const searchQuery = ref('')\n")
f.write("const filterYil = ref('')\n")
f.write("const filterTip = ref('')\n")
f.write("const selectedPoz = ref(null)\n")
f.write("const availableYears = ref([])\n")
f.write("const pagination = reactive({ page: 1, pageSize: 20, total: 0 })\n\n")
f.write("const filteredPozList = computed(() => {\n")
f.write("  let result = pozList.value\n")
f.write("  if (searchQuery.value) {\n")
f.write("    const q = searchQuery.value.toLowerCase()\n")
f.write("    result = result.filter(p => p.poz_no.toLowerCase().includes(q) || p.ad.toLowerCase().includes(q) || p.degisim_turu.toLowerCase().includes(q))\n")
f.write("  }\n")
f.write("  if (filterYil.value) result = result.filter(p => p.yil == filterYil.value)\n")
f.write("  if (filterTip.value) result = result.filter(p => p.degisim_turu == filterTip.value)\n")
f.write("  return result\n")
f.write("})\n\n")
f.write("const degisimClass = (tur) => {\n")
f.write("  const map = { YENI: 'badge-success', SILINEN: 'badge-error', FIYAT_DEGISIKLIGI: 'badge-warning', DIGER: 'badge-info' }\n")
f.write("  return map[tur] || 'badge-secondary'\n")
f.write("}\n")
f.write("const formatCurrency = (val) => {\n")
f.write("  if (!val) return '-'\n")
f.write("  return new Intl.NumberFormat('tr-TR', { style: 'currency', currency: 'TRY', minimumFractionDigits: 2 }).format(val)\n")
f.write("}\n\n")
f.write("onMounted(async () => {\n")
f.write("  await loadPozList()\n")
f.write("  await loadAvailableYears()\n")
f.write("})\n\n")
f.write("async function loadPozList() {\n")
f.write("  loading.value = true\n")
f.write("  try {\n")
f.write("    const res = await insaatStore.fetchYfkDegisenPozlar({ page: pagination.page, page_size: pagination.pageSize, yil: filterYil.value || undefined, degisim_turu: filterTip.value || undefined, search: searchQuery.value || undefined })\n")
f.write("    pozList.value = res.results || res\n")
f.write("    pagination.total = res.count || res.length\n")
f.write("  } catch (e) {\n")
f.write("    toast.error('Degisen pozlar yuklenemedi')\n")
f.write("  } finally {\n")
f.write("    loading.value = false\n")
f.write("  }\n")
f.write("}\n\n")
f.write("async function loadAvailableYears() {\n")
f.write("  try {\n")
f.write("    const res = await insaatStore.fetchYfkDegisenPozlar({ page_size: 1000 })\n")
f.write("    const years = [...new Set((res.results || res).map(p => p.yil).filter(Boolean))].sort((a, b) => b - a)\n")
f.write("    availableYears.value = years\n")
f.write("  } catch (e) {}\n")
f.write("}\n\n")
f.write("async function showPozDetail(poz) {\n")
f.write("  loading.value = true\n")
f.write("  try {\n")
f.write("    const detail = await insaatStore.fetchYfkDegisenPozDetail(poz.id)\n")
f.write("    selectedPoz.value = detail\n")
f.write("  } catch (e) { toast.error('Detay yuklenemedi') }\n")
f.write("  finally { loading.value = false }\n")
f.write("}\n\n")
f.write("const Math = window.Math\n")
f.write("</script>\n")
f.close()
print("Script section done")