import os
views_dir = r"c:\proje\emlakpython\frontend\src\views\insaat\yfk"
f = open(os.path.join(views_dir, "AnalizGuncelle.vue"), "a", encoding="utf-8")
f.write("async function onFileSelect(e) {\n")
f.write("  selectedFile.value = e.target.files[0]\n")
f.write("}\n\n")
f.write("async function handleImport() {\n")
f.write("  if (!selectedFile.value) { toast.error('CSV dosyasi secin'); return }\n")
f.write("  loading.value = true\n")
f.write("  importResult.value = null\n")
f.write("  try {\n")
f.write("    const formData = new FormData()\n")
f.write("    formData.append('file', selectedFile.value)\n")
f.write("    formData.append('yil', importForm.yil)\n")
f.write("    if (importForm.donem) formData.append('donem', importForm.donem)\n")
f.write("    formData.append('kaynak', importForm.kaynak)\n")
f.write("    formData.append('kaynak_url', importForm.kaynak_url)\n")
f.write("    const res = await insaatStore.importYfkAnaliz(formData)\n")
f.write("    importResult.value = { success: true, stats: res, errors: [] }\n")
f.write("    toast.success('Ice aktarma tamamlandi')\n")
f.write("    await loadAnalizList()\n")
f.write("    await loadAvailableYears()\n")
f.write("    selectedFile.value = null\n")
f.write("    importForm.kaynak = ''\n")
f.write("    importForm.kaynak_url = ''\n")
f.write("    importForm.donem = null\n")
f.write("  } catch (e) {\n")
f.write("    importResult.value = { success: false, stats: {}, errors: [e.response?.data?.detail || e.message || 'Bilinmeyen hata'] }\n")
f.write("    toast.error('Ice aktarma basarisiz')\n")
f.write("  } finally {\n")
f.write("    loading.value = false\n")
f.write("  }\n")
f.write("}\n\n")
f.write("async function downloadTemplate() {\n")
f.write("  try {\n")
f.write("    const blob = await insaatStore.downloadYfkAnalizTemplate()\n")
f.write("    const url = window.URL.createObjectURL(blob)\n")
f.write("    const a = document.createElement('a')\n")
f.write("    a.href = url\n")
f.write("    a.download = 'yfk_analiz_template.csv'\n")
f.write("    a.click()\n")
f.write("    window.URL.revokeObjectURL(url)\n")
f.write("  } catch (e) { toast.error('Sablon indirilemedi') }\n")
f.write("}\n\n")
f.write("async function showAnalizDetail(analiz) {\n")
f.write("  loading.value = true\n")
f.write("  try {\n")
f.write("    const detail = await insaatStore.fetchYfkAnalizDetail(analiz.id)\n")
f.write("    selectedAnaliz.value = detail\n")
f.write("  } catch (e) { toast.error('Detay yuklenemedi') }\n")
f.write("  finally { loading.value = false }\n")
f.write("}\n\n")
f.write("const Math = window.Math\n")
f.write("</script>\n")
f.close()
print("Script part 3 done")