import os
views_dir = r"c:\proje\emlakpython\frontend\src\views\insaat\yfk"
f = open(os.path.join(views_dir, "AnalizGuncelle.vue"), "a", encoding="utf-8")
f.write("      <div class=\"card-body p-0\">\n")
f.write("        <div class=\"overflow-x-auto\"><table class=\"table w-full\"><thead><tr><th>Poz No</th><th>Tip</th><th>Malzeme Kodu</th><th>Malzeme Adi</th><th>Birim</th><th>Miktar</th><th>Birim Fiyat</th><th>Toplam</th><th>Yil</th><th>Donem</th><th>Kaynak</th><th>Gecerlilik</th><th>Islemler</th></tr></thead><tbody>\n")
f.write("          <tr v-for=\"a in filteredAnalizList\" :key=\"a.id\"><td class=\"font-mono\">{{ a.poz_no }}</td><td><span class=\"badge\" :class=\"tipClass(a.malzeme_tipi)\">{{ a.malzeme_tipi }}</span></td><td>{{ a.malzeme_kodu }}</td><td>{{ a.malzeme_adi }}</td><td>{{ a.birim }}</td><td class=\"font-mono\">{{ a.miktar }}</td><td class=\"font-mono\">{{ formatCurrency(a.birim_fiyat) }}</td><td class=\"font-mono\">{{ formatCurrency(a.miktar * a.birim_fiyat) }}</td><td>{{ a.yil or '-' }}</td><td>{{ a.donem or 'Yillik' }}</td><td>{{ a.kaynak }}</td><td>{{ a.gecerlilik_tarihi or '-' }}</td><td><button @click=\"showAnalizDetail(a)\" class=\"btn btn-sm btn-ghost\">Detay</button></td></tr>\n")
f.write("          <tr v-if=\"filteredAnalizList.length === 0\"><td colspan=\"13\" class=\"text-center py-8 text-gray-500\">Kayit bulunamadi</td></tr>\n")
f.write("        </tbody></table></div>\n")
f.write("        <div class=\"p-4 border-t flex justify-between items-center\" v-if=\"pagination.total > 0\"><p class=\"text-sm text-gray-600\"> {{ (pagination.page - 1) * pagination.pageSize + 1 }} - {{ Math.min(pagination.page * pagination.pageSize, pagination.total) }} / {{ pagination.total }} kayit</p><div class=\"flex gap-2\"><button @click=\"pagination.page > 1 and (pagination.page--, loadAnalizList())\" :disabled=\"pagination.page <= 1\" class=\"btn btn-sm btn-ghost\">Onceki</button><button @click=\"pagination.page * pagination.pageSize < pagination.total and (pagination.page++, loadAnalizList())\" :disabled=\"pagination.page * pagination.pageSize >= pagination.total\" class=\"btn btn-sm btn-ghost\">Sonraki</button></div></div>\n")
f.write("      </div>\n")
f.write("    </div>\n")
f.write("    <div v-if=\"selectedAnaliz\" class=\"fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4\">\n")
f.write("      <div class=\"bg-white rounded-lg max-w-2xl w-full max-h-[90vh] overflow-hidden\">\n")
f.write("        <div class=\"p-4 border-b flex justify-between items-center\"><h3 class=\"text-lg font-bold\">{{ selectedAnaliz.poz_no }} - {{ selectedAnaliz.malzeme_adi }} ({{ selectedAnaliz.malzeme_tipi }})</h3><button @click=\"selectedAnaliz = null\" class=\"text-gray-500 hover:text-gray-700\">X</button></div>\n")
f.write("        <div class=\"p-4 overflow-y-auto max-h-[70vh]\">\n")
f.write("          <div class=\"grid grid-cols-1 md:grid-cols-2 gap-4 mb-4\"><div><strong>Poz No:</strong> {{ selectedAnaliz.poz_no }}</div><div><strong>Malzeme Tipi:</strong> {{ selectedAnaliz.malzeme_tipi }}</div><div><strong>Malzeme Kodu:</strong> {{ selectedAnaliz.malzeme_kodu }}</div><div><strong>Malzeme Adi:</strong> {{ selectedAnaliz.malzeme_adi }}</div><div><strong>Birim:</strong> {{ selectedAnaliz.birim }}</div><div><strong>Miktar:</strong> {{ selectedAnaliz.miktar }}</div><div><strong>Birim Fiyat:</strong> {{ formatCurrency(selectedAnaliz.birim_fiyat) }}</div><div><strong>Toplam:</strong> {{ formatCurrency(selectedAnaliz.miktar * selectedAnaliz.birim_fiyat) }}</div><div><strong>Yil:</strong> {{ selectedAnaliz.yil or '-' }}</div><div><strong>Donem:</strong> {{ selectedAnaliz.donem or 'Yillik' }}</div><div><strong>Kaynak:</strong> {{ selectedAnaliz.kaynak }}</div><div><strong>Yayin Tarihi:</strong> {{ selectedAnaliz.yayin_tarihi or '-' }}</div><div><strong>Gecerlilik:</strong> {{ selectedAnaliz.gecerlilik_tarihi or '-' }}</div></div>\n")
f.write("        </div>\n")
f.write("      </div>\n")
f.write("    </div>\n")
f.write("  </div>\n")
f.write("</template>\n")
f.close()
print("Part 3 done")