import os
views_dir = r"c:\proje\emlakpython\frontend\src\views\insaat\yfk"
f = open(os.path.join(views_dir, "DegisenPozlar.vue"), "a", encoding="utf-8")
f.write("        <div class=\"overflow-x-auto\"><table class=\"table w-full\"><thead><tr><th>Poz No</th><th>Ad</th><th>Grup</th><th>Birim</th><th>Eski Fiyat</th><th>Yeni Fiyat</th><th>Fark</th><th>Fark %</th><th>Degisim Turu</th><th>Yil</th><th>Kaynak</th><th>Islemler</th></tr></thead><tbody>\n")
f.write("          <tr v-for=\"p in filteredPozList\" :key=\"p.id\"><td class=\"font-mono\">{{ p.poz_no }}</td><td>{{ p.ad }}</td><td>{{ p.grup_kodu }} - {{ p.grup_adi }}</td><td>{{ p.birim }}</td><td class=\"font-mono\">{{ formatCurrency(p.eski_birim_fiyat) }}</td><td class=\"font-mono\">{{ formatCurrency(p.yeni_birim_fiyat) }}</td><td class=\"font-mono\" :class=\"p.fark > 0 ? 'text-red-600' : p.fark < 0 ? 'text-green-600' : ''\">{{ formatCurrency(p.fark) }}</td><td :class=\"p.fark_yuzde > 0 ? 'text-red-600' : p.fark_yuzde < 0 ? 'text-green-600' : ''\">{{ p.fark_yuzde }}%</td><td><span class=\"badge\" :class=\"degisimClass(p.degisim_turu)\">{{ p.degisim_turu }}</span></td><td>{{ p.yil }}</td><td>{{ p.kaynak }}</td><td><button @click=\"showPozDetail(p)\" class=\"btn btn-sm btn-ghost\">Detay</button></td></tr>\n")
f.write("          <tr v-if=\"filteredPozList.length === 0\"><td colspan=\"12\" class=\"text-center py-8 text-gray-500\">Kayit bulunamadi</td></tr>\n")
f.write("        </tbody></table></div>\n")
f.write("        <div class=\"p-4 border-t flex justify-between items-center\" v-if=\"pagination.total > 0\"><p class=\"text-sm text-gray-600\"> {{ (pagination.page - 1) * pagination.pageSize + 1 }} - {{ Math.min(pagination.page * pagination.pageSize, pagination.total) }} / {{ pagination.total }} kayit</p><div class=\"flex gap-2\"><button @click=\"pagination.page > 1 and (pagination.page--, loadPozList())\" :disabled=\"pagination.page <= 1\" class=\"btn btn-sm btn-ghost\">Onceki</button><button @click=\"pagination.page * pagination.pageSize < pagination.total and (pagination.page++, loadPozList())\" :disabled=\"pagination.page * pagination.pageSize >= pagination.total\" class=\"btn btn-sm btn-ghost\">Sonraki</button></div></div>\n")
f.write("      </div>\n")
f.write("    </div>\n")
f.write("    <div v-if=\"selectedPoz\" class=\"fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4\">\n")
f.write("      <div class=\"bg-white rounded-lg max-w-2xl w-full max-h-[90vh] overflow-hidden\">\n")
f.write("        <div class=\"p-4 border-b flex justify-between items-center\"><h3 class=\"text-lg font-bold\">{{ selectedPoz.poz_no }} - {{ selectedPoz.ad }}</h3><button @click=\"selectedPoz = null\" class=\"text-gray-500 hover:text-gray-700\">X</button></div>\n")
f.write("        <div class=\"p-4 overflow-y-auto max-h-[70vh]\">\n")
f.write("          <div class=\"grid grid-cols-1 md:grid-cols-2 gap-4 mb-4\"><div><strong>Poz No:</strong> {{ selectedPoz.poz_no }}</div><div><strong>Ad:</strong> {{ selectedPoz.ad }}</div><div><strong>Grup Kodu:</strong> {{ selectedPoz.grup_kodu }}</div><div><strong>Grup Adi:</strong> {{ selectedPoz.grup_adi }}</div><div><strong>Birim:</strong> {{ selectedPoz.birim }}</div><div><strong>Degisim Turu:</strong> <span class=\"badge\" :class=\"degisimClass(selectedPoz.degisim_turu)\">{{ selectedPoz.degisim_turu }}</span></div><div><strong>Eski Birim Fiyat:</strong> {{ formatCurrency(selectedPoz.eski_birim_fiyat) }}</div><div><strong>Yeni Birim Fiyat:</strong> {{ formatCurrency(selectedPoz.yeni_birim_fiyat) }}</div><div><strong>Fark:</strong> <span :class=\"selectedPoz.fark > 0 ? 'text-red-600' : selectedPoz.fark < 0 ? 'text-green-600' : ''\">{{ formatCurrency(selectedPoz.fark) }}</span></div><div><strong>Fark %:</strong> <span :class=\"selectedPoz.fark_yuzde > 0 ? 'text-red-600' : selectedPoz.fark_yuzde < 0 ? 'text-green-600' : ''\">{{ selectedPoz.fark_yuzde }}%</span></div><div><strong>Yil:</strong> {{ selectedPoz.yil }}</div><div><strong>Kaynak:</strong> {{ selectedPoz.kaynak }}</div></div>\n")
f.write("        </div>\n")
f.write("      </div>\n")
f.write("    </div>\n")
f.write("  </div>\n")
f.write("</template>\n")
f.close()
print("Part 2 done")