import os
views_dir = r"c:\proje\emlakpython\frontend\src\views\insaat\yfk"
f = open(os.path.join(views_dir, "AnalizGuncelle.vue"), "a", encoding="utf-8")
f.write("\n<script setup>\n")
f.write("import { ref, reactive, computed, onMounted } from 'vue'\n")
f.write("import { useInsaatStore } from '@/stores/insaat'\n")
f.write("import { useToast } from '@/composables/useToast'\n")
f.write("import LoadingSpinner from '@/components/ui/LoadingSpinner.vue'\n\n")
f.write("const insaatStore = useInsaatStore()\n")
f.write("const toast = useToast()\n\n")
f.write("const loading = ref(false)\n")
f.write("const importForm = reactive({\n")
f.write("  yil: new Date().getFullYear(),\n")
f.write("  donem: null,\n")
f.write("  kaynak: '',\n")
f.write("  kaynak_url: '',\n")
f.write("})\n")
f.write("const selectedFile = ref(null)\n")
f.write("const importResult = ref(null)\n\n")
f.write("const analizList = ref([])\n")
f.write("const searchQuery = ref('')\n")
f.write("const filterYil = ref('')\n")
f.write("const filterTip = ref('')\n")
f.write("const selectedAnaliz = ref(null)\n")
f.write("const availableYears = ref([])\n")
f.write("const pagination = reactive({ page: 1, pageSize: 20, total: 0 })\n\n")
f.write("const filteredAnalizList = computed(() => {\n")
f.write("  let result = analizList.value\n")
f.write("  if (searchQuery.value) {\n")
f.write("    const q = searchQuery.value.toLowerCase()\n")
f.write("    result = result.filter(a => a.poz_no.toLowerCase().includes(q) || a.malzeme_kodu.toLowerCase().includes(q) || a.malzeme_adi.toLowerCase().includes(q))\n")
f.write("  }\n")
f.write("  if (filterYil.value) result = result.filter(a => a.yil == filterYil.value)\n")
f.write("  if (filterTip.value) result = result.filter(a => a.malzeme_tipi == filterTip.value)\n")
f.write("  return result\n")
f.write("})\n\n")
f.close()
print("Script part 1 done")