import os
views_dir = r"c:\proje\emlakpython\frontend\src\views\insaat\yfk"
f = open(os.path.join(views_dir, "GuncellemeGecmisi.vue"), "a", encoding="utf-8")
f.write("\n<script setup>\n")
f.write("import { ref, reactive, computed, onMounted } from 'vue'\n")
f.write("import { useInsaatStore } from '@/stores/insaat'\n")
f.write("import { useToast } from '@/composables/useToast'\n\n")
f.write("const insaatStore = useInsaatStore()\n")
f.write("const toast = useToast()\n\n")
f.write("const loading = ref(false)\n")
f.write("const gecmisList = ref([])\n")
f.write("const searchQuery = ref('')\n")
f.write("const filterYil = ref('')\n")
f.write("const filterIslem = ref('')\n")
f.write("const availableYears = ref([])\n")
f.write("const pagination = reactive({ page: 1, pageSize: 20, total: 0 })\n\n")
f.write("const filteredGecmisList = computed(() => {\n")
f.write("  let result = gecmisList.value\n")
f.write("  if (searchQuery.value) {\n")
f.write("    const q = searchQuery.value.toLowerCase()\n")
f.write("    result = result.filter(g => g.poz_no.toLowerCase().includes(q) || g.ad.toLowerCase().includes(q) || g.aciklama.toLowerCase().includes(q) || g.islem_turu.toLowerCase().includes(q))\n")
f.write("  }\n")
f.write("  if (filterYil.value) result = result.filter(g => g.yil == filterYil.value)\n")
f.write("  if (filterIslem.value) result = result.filter(g => g.islem_turu == filterIslem.value)\n")
f.write("  return result\n")
f.write("})\n\n")
f.write("const islemClass = (tur) => {\n")
f.write("  const map = { IMPORT: 'badge-primary', MANUEL: 'badge-success', IPTAL: 'badge-error' }\n")
f.write("  return map[tur] || 'badge-secondary'\n")
f.write("}\n")
f.write("const formatDateTime = (val) => {\n")
f.write("  if (!val) return '-'\n")
f.write("  return new Date(val).toLocaleString('tr-TR')\n")
f.write("}\n\n")
f.write("onMounted(async () => {\n")
f.write("  await loadGecmisList()\n")
f.write("  await loadAvailableYears()\n")
f.write("})\n\n")
f.write("async function loadGecmisList() {\n")
f.write("  loading.value = true\n")
f.write("  try {\n")
f.write("    const res = await insaatStore.fetchYfkGuncellemeGecmisi({ page: pagination.page, page_size: pagination.pageSize, yil: filterYil.value || undefined, islem_turu: filterIslem.value || undefined, search: searchQuery.value || undefined })\n")
f.write("    gecmisList.value = res.results || res\n")
f.write("    pagination.total = res.count || res.length\n")
f.write("  } catch (e) {\n")
f.write("    toast.error('Guncelleme gecmisi yuklenemedi')\n")
f.write("  } finally {\n")
f.write("    loading.value = false\n")
f.write("  }\n")
f.write("}\n\n")
f.write("async function loadAvailableYears() {\n")
f.write("  try {\n")
f.write("    const res = await insaatStore.fetchYfkGuncellemeGecmisi({ page_size: 1000 })\n")
f.write("    const years = [...new Set((res.results || res).map(g => g.yil).filter(Boolean))].sort((a, b) => b - a)\n")
f.write("    availableYears.value = years\n")
f.write("  } catch (e) {}\n")
f.write("}\n\n")
f.write("const Math = window.Math\n")
f.write("</script>\n")
f.close()
print("Script section done")