import os
views_dir = r"c:\proje\emlakpython\frontend\src\views\insaat\yfk"
f = open(os.path.join(views_dir, "AylikFiyatGuncelle.vue"), "a", encoding="utf-8")
f.write("      <div class=\"card-body p-0\">\n")
f.write("        <div class=\"overflow-x-auto\"><table class=\"table w-full\"><thead><tr><th>Poz No</th><th>Ad</th><th>Birim</th><th>Grup</th><th>Yil</th><th>Donem</th><th>Birim Fiyat</th><th>Kaynak</th><th>Yayin Tarihi</th><th>Gecerlilik</th><th>Islemler</th></tr></thead><tbody>\n")
f.write("          <tr v-for=\"f in filteredFiyatList\" :key=\"f.id\"><td class=\"font-mono\">{{ f.poz_no }}</td><td>{{ f.ad }}</td><td>{{ f.birim }}</td><td>{{ f.grup_kodu }} - {{ f.grup_adi }}</td><td>{{ f.yil }}</td><td>{{ f.donem }}</td><td class=\"font-mono\">{{ formatCurrency(f.birim_fiyat) }}</td><td>{{ f.kaynak }}</td><td>{{ f.yayin_tarihi or '-' }}</td><td>{{ f.gecerlilik_tarihi or '-' }}</td><td><button @click=\"showFiyatDetail(f)\" class=\"btn btn-sm btn-ghost\">Detay</button></td></tr>\n")
f.write("          <tr v-if=\"filteredFiyatList.length === 0\"><td colspan=\"11\" class=\"text-center py-8 text-gray-500\">Kayit bulunamadi</td></tr>\n")
f.write("        </tbody></table></div>\n")
f.write("        <div class=\"p-4 border-t flex justify-between items-center\" v-if=\"pagination.total > 0\"><p class=\"text-sm text-gray-600\"> {{ (pagination.page - 1) * pagination.pageSize + 1 }} - {{ Math.min(pagination.page * pagination.pageSize, pagination.total) }} / {{ pagination.total }} kayit</p><div class=\"flex gap-2\"><button @click=\"pagination.page > 1 and (pagination.page--, loadFiyatList())\" :disabled=\"pagination.page <= 1\" class=\"btn btn-sm btn-ghost\">Onceki</button><button @click=\"pagination.page * pagination.pageSize < pagination.total and (pagination.page++, loadFiyatList())\" :disabled=\"pagination.page * pagination.pageSize >= pagination.total\" class=\"btn btn-sm btn-ghost\">Sonraki</button></div></div>\n")
f.write("      </div>\n")
f.write("    </div>\n")
f.write("    <div v-if=\"selectedFiyat\" class=\"fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4\">\n")
f.write("      <div class=\"bg-white rounded-lg max-w-2xl w-full max-h-[90vh] overflow-hidden\">\n")
f.write("        <div class=\"p-4 border-b flex justify-between items-center\"><h3 class=\"text-lg font-bold\">{{ selectedFiyat.poz_no }} - {{ selectedFiyat.ad }} ({{ selectedFiyat.yil }}/{{ selectedFiyat.donem }})</h3><button @click=\"selectedFiyat = null\" class=\"text-gray-500 hover:text-gray-700\">X</button></div>\n")
f.write("        <div class=\"p-4 overflow-y-auto max-h-[70vh]\">\n")
f.write("          <div class=\"grid grid-cols-1 md:grid-cols-2 gap-4 mb-4\"><div><strong>Poz No:</strong> {{ selectedFiyat.poz_no }}</div><div><strong>Ad:</strong> {{ selectedFiyat.ad }}</div><div><strong>Birim:</strong> {{ selectedFiyat.birim }}</div><div><strong>Grup:</strong> {{ selectedFiyat.grup_kodu }} - {{ selectedFiyat.grup_adi }}</div><div><strong>Yil:</strong> {{ selectedFiyat.yil }}</div><div><strong>Donem:</strong> {{ selectedFiyat.donem }}</div><div><strong>Birim Fiyat:</strong> {{ formatCurrency(selectedFiyat.birim_fiyat) }}</div><div><strong>Kaynak:</strong> {{ selectedFiyat.kaynak }}</div><div><strong>Yayin Tarihi:</strong> {{ selectedFiyat.yayin_tarihi or '-' }}</div><div><strong>Gecerlilik:</strong> {{ selectedFiyat.gecerlilik_tarihi or '-' }}</div></div>\n")
f.write("        </div>\n")
f.write("      </div>\n")
f.write("    </div>\n")
f.write("  </div>\n")
f.write("</template>\n")
f.close()
print("Part 3 done")