import os
views_dir = r"c:\proje\emlakpython\frontend\src\views\insaat\yfk"
f = open(os.path.join(views_dir, "AylikFiyatGuncelle.vue"), "a", encoding="utf-8")
f.write("          <div class=\"mb-4\">\n")
f.write("            <label class=\"block text-sm font-medium mb-1\">CSV Dosyasi *</label>\n")
f.write("            <input ref=\"fileInput\" type=\"file\" accept=\".csv\" @change=\"onFileSelect\" class=\"input w-full\" required />\n")
f.write("            <p class=\"text-sm text-gray-500 mt-1\">CSV sutunlari: poz_no, ad, birim, grup_kodu, grup_adi, birim_fiyat, kaynak, kaynak_url, yayin_tarihi, gecerlilik_tarihi</p>\n")
f.write("          </div>\n")
f.write("          <div class=\"flex gap-2\">\n")
f.write("            <button type=\"submit\" :disabled=\"loading\" class=\"btn btn-primary\"><LoadingSpinner v-if=\"loading\" class=\"mr-2 h-4 w-4\" />{{ loading ? 'Ice Aktariliyor...' : 'CSV Ice Aktar' }}</button>\n")
f.write("            <button type=\"button\" @click=\"downloadTemplate\" class=\"btn btn-secondary\">Sablon Indir</button>\n")
f.write("          </div>\n")
f.write("        </form>\n")
f.write("        <div v-if=\"importResult\" class=\"mt-4 p-4 rounded\" :class=\"importResult.success ? 'bg-green-50 border border-green-200' : 'bg-red-50 border border-red-200'\">\n")
f.write("          <h4 class=\"font-medium\" :class=\"importResult.success ? 'text-green-800' : 'text-red-800'\">{{ importResult.success ? 'OK Ice Aktarma Basarili' : 'ERR Ice Aktarma Basarisiz' }}</h4>\n")
f.write("          <ul class=\"mt-2 text-sm space-y-1\">\n")
f.write("            <li v-for=\"(value, key) in importResult.stats\" :key=\"key\"><strong>{{ formatStatKey(key) }}:</strong> {{ value }}</li>\n")
f.write("            <li v-if=\"importResult.errors and importResult.errors.length\"><strong>Hatalar:</strong><ul class=\"ml-4 list-disc\"><li v-for=\"(err, idx) in importResult.errors\" :key=\"idx\" class=\"text-red-600\">{{ err }}</li></ul></li>\n")
f.write("          </ul>\n")
f.write("        </div>\n")
f.write("      </div>\n")
f.write("    </div>\n")
f.write("    <div class=\"card\">\n")
f.write("      <div class=\"card-header flex justify-between items-center\">\n")
f.write("        <h3 class=\"card-title\">YFK Aylik Fiyatlar ({{ fiyatList.length }})</h3>\n")
f.write("        <div class=\"flex gap-2\"><input v-model=\"searchQuery\" type=\"text\" placeholder=\"Poz no, ad veya grup kodu ile ara...\" class=\"input w-64\" /><select v-model=\"filterYil\" class=\"input w-32\"><option value=\"\">Tum Yillar</option><option v-for=\"y in availableYears\" :key=\"y\" :value=\"y\">{{ y }}</option></select><select v-model=\"filterDonem\" class=\"input w-32\"><option value=\"\">Tum Donemler</option><option v-for=\"n in 12\" :key=\"n\" :value=\"n\">{{ n }}</option></select></div>\n")
f.write("      </div>\n")
f.close()
print("Part 2 done")