import os
views_dir = r"c:\proje\emlakpython\frontend\src\views\insaat\yfk"
f = open(os.path.join(views_dir, "AnalizGuncelle.vue"), "a", encoding="utf-8")
f.write("const tipClass = (tip) => {\n")
f.write("  const map = { MALZEME: 'badge-primary', ISCILIK: 'badge-success', NAKLIYE: 'badge-warning', MAKINE: 'badge-info' }\n")
f.write("  return map[tip] || 'badge-secondary'\n")
f.write("}\n")
f.write("const formatCurrency = (val) => {\n")
f.write("  if (!val) return '-'\n")
f.write("  return new Intl.NumberFormat('tr-TR', { style: 'currency', currency: 'TRY', minimumFractionDigits: 2 }).format(val)\n")
f.write("}\n")
f.write("const formatStatKey = (key) => {\n")
f.write("  const map = { created: 'Olusturulan', updated: 'Guncellenen', skipped: 'Atlanan', errors: 'Hatali' }\n")
f.write("  return map[key] || key\n")
f.write("}\n\n")
f.write("onMounted(async () => {\n")
f.write("  await loadAnalizList()\n")
f.write("  await loadAvailableYears()\n")
f.write("})\n\n")
f.write("async function loadAnalizList() {\n")
f.write("  loading.value = true\n")
f.write("  try {\n")
f.write("    const res = await insaatStore.fetchYfkAnalizler({ page: pagination.page, page_size: pagination.pageSize, yil: filterYil.value || undefined, malzeme_tipi: filterTip.value || undefined, search: searchQuery.value || undefined })\n")
f.write("    analizList.value = res.results || res\n")
f.write("    pagination.total = res.count || res.length\n")
f.write("  } catch (e) {\n")
f.write("    toast.error('Analiz listesi yuklenemedi')\n")
f.write("  } finally {\n")
f.write("    loading.value = false\n")
f.write("  }\n")
f.write("}\n\n")
f.write("async function loadAvailableYears() {\n")
f.write("  try {\n")
f.write("    const res = await insaatStore.fetchYfkAnalizler({ page_size: 1000 })\n")
f.write("    const years = [...new Set((res.results || res).map(a => a.yil).filter(Boolean))].sort((a, b) => b - a)\n")
f.write("    availableYears.value = years\n")
f.write("  } catch (e) {}\n")
f.write("}\n\n")
f.close()
print("Script part 2 done")