# Generated by Django 6.1.1 on 2026-09-17 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('construction', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hakedis',
            name='onaylayan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan'),
        ),
        migrations.AddField(
            model_name='hakedis',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='hakedissatiri',
            name='hakedis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satirlar', to='construction.hakedis', verbose_name='Hakediş'),
        ),
        migrations.AddField(
            model_name='kalitekabulteminati',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kabul_teminati_kayitlari', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AddField(
            model_name='kalitekabulteminati',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='kalitekontrol',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kalite_kontrolleri', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kalitekontrol',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='kirasozlesi',
            name='ada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kiralik_sozlesi', to='construction.ada', verbose_name='Ada'),
        ),
        migrations.AddField(
            model_name='kirasozlesi',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='leaseassistance',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='malzeme',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='malzemetedarikciiliskisi',
            name='malzeme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tedarikci_kalemleri', to='construction.malzeme', verbose_name='Malzeme'),
        ),
        migrations.AddField(
            model_name='malzemetedarikciiliskisi',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='parsel',
            name='ada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parseller', to='construction.ada', verbose_name='Ada'),
        ),
        migrations.AddField(
            model_name='parsel',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='kirasozlesi',
            name='parsell',
            field=models.ManyToManyField(blank=True, related_name='kiralik_sozlesi', to='construction.parsel', verbose_name='Parseller'),
        ),
        migrations.AddField(
            model_name='poz',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='kalitekontrol',
            name='poz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kalite_kontrolleri', to='construction.poz'),
        ),
        migrations.AddField(
            model_name='kalitekabulteminati',
            name='poz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kabul_teminati', to='construction.poz', verbose_name='Poz'),
        ),
        migrations.AddField(
            model_name='hakedissatiri',
            name='poz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hakedis_satirlari', to='construction.poz', verbose_name='Poz'),
        ),
        migrations.AddField(
            model_name='pozfiyat',
            name='poz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiyatlar', to='construction.poz', verbose_name='Poz'),
        ),
        migrations.AddField(
            model_name='pozfiyat',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='pozgrubu',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='pozgrubu',
            name='ust_grup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alt_gruplar', to='construction.pozgrubu', verbose_name='Üst Grup'),
        ),
        migrations.AddField(
            model_name='poz',
            name='grup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pozlar', to='construction.pozgrubu', verbose_name='Poz Grubu'),
        ),
        migrations.AddField(
            model_name='pozmalzemeiliskisi',
            name='malzeme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='poz_kalemleri', to='construction.malzeme', verbose_name='Malzeme'),
        ),
        migrations.AddField(
            model_name='pozmalzemeiliskisi',
            name='poz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='malzeme_kalemleri', to='construction.poz', verbose_name='Poz'),
        ),
        migrations.AddField(
            model_name='pozmalzemeiliskisi',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='pozplan',
            name='poz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='poz_planlari', to='construction.poz', verbose_name='Poz'),
        ),
        migrations.AddField(
            model_name='pozplan',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='proje',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='pozplan',
            name='proje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poz_planlari', to='construction.proje', verbose_name='Proje'),
        ),
        migrations.AddField(
            model_name='leaseassistance',
            name='proje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lease_assistances', to='construction.proje', verbose_name='Proje'),
        ),
        migrations.AddField(
            model_name='kirasozlesi',
            name='proje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kiralik_sozlesi', to='construction.proje', verbose_name='Proje'),
        ),
        migrations.AddField(
            model_name='kalitekontrol',
            name='proje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kalite_kontrolleri', to='construction.proje'),
        ),
        migrations.AddField(
            model_name='kalitekabulteminati',
            name='proje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kabul_teminati', to='construction.proje', verbose_name='Proje'),
        ),
        migrations.AddField(
            model_name='hakedis',
            name='proje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hakedisler', to='construction.proje', verbose_name='Proje'),
        ),
        migrations.AddField(
            model_name='ada',
            name='proje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adas', to='construction.proje', verbose_name='Proje'),
        ),
        migrations.AddField(
            model_name='riskliyapı',
            name='ada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='riskli_yapilar', to='construction.ada', verbose_name='Ada'),
        ),
        migrations.AddField(
            model_name='riskliyapı',
            name='parsell',
            field=models.ManyToManyField(blank=True, related_name='riskli_yapilar', to='construction.parsel', verbose_name='Parseller'),
        ),
        migrations.AddField(
            model_name='riskliyapı',
            name='proje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='riskli_yapilar', to='construction.proje', verbose_name='Proje'),
        ),
        migrations.AddField(
            model_name='riskliyapı',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='riskstructure',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='santiyegunlugu',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='santiye_gunlukleri', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='santiyegunlugu',
            name='proje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gunlukler', to='construction.proje'),
        ),
        migrations.AddField(
            model_name='santiyegunlugu',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='sözlesentemplate',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='tahliyesuresi',
            name='kirasozlesi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tahliye_suresi', to='construction.kirasozlesi', verbose_name='Kira Sözleşmesi'),
        ),
        migrations.AddField(
            model_name='tahliyesuresi',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='taseronsozlesi',
            name='proje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taseron_sozlesi', to='construction.proje', verbose_name='Proje'),
        ),
        migrations.AddField(
            model_name='taseronsozlesi',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='tedarikci',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='malzemetedarikciiliskisi',
            name='tedarikci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='malzeme_kalemleri', to='construction.tedarikci', verbose_name='Tedarikçi'),
        ),
        migrations.AddField(
            model_name='yapisinifibirimmaliyet',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='proje',
            name='yapisinif_maliyet',
            field=models.ForeignKey(blank=True, help_text='Tebliğ yılı + yapı sınıfı seçimi (tüm değer snapshot olarak korunur).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projeler', to='construction.yapisinifibirimmaliyet', verbose_name='Yapı Sınıfı Birim Maliyeti'),
        ),
        migrations.AddConstraint(
            model_name='malzeme',
            constraint=models.UniqueConstraint(fields=('tenant', 'malzeme_kodu'), name='uniq_malzeme_tenant_kod'),
        ),
        migrations.AddConstraint(
            model_name='parsel',
            constraint=models.UniqueConstraint(fields=('ada', 'no'), name='uniq_parsel_ada_no'),
        ),
        migrations.AddConstraint(
            model_name='hakedissatiri',
            constraint=models.UniqueConstraint(fields=('hakedis', 'poz'), name='uniq_hakedis_satir_hakedis_poz'),
        ),
        migrations.AddConstraint(
            model_name='pozfiyat',
            constraint=models.UniqueConstraint(fields=('tenant', 'poz', 'yil'), name='uniq_poz_fiyat_yil'),
        ),
        migrations.AddConstraint(
            model_name='pozgrubu',
            constraint=models.UniqueConstraint(fields=('tenant', 'kod'), name='uniq_pozgrubu_tenant_kod'),
        ),
        migrations.AddConstraint(
            model_name='poz',
            constraint=models.UniqueConstraint(fields=('tenant', 'poz_no'), name='uniq_poz_tenant_no'),
        ),
        migrations.AddConstraint(
            model_name='pozmalzemeiliskisi',
            constraint=models.UniqueConstraint(fields=('tenant', 'poz', 'malzeme'), name='uniq_poz_malzeme_tenant'),
        ),
        migrations.AddConstraint(
            model_name='pozmalzemeiliskisi',
            constraint=models.CheckConstraint(condition=models.Q(('miktar__gt', 0)), name='check_poz_malzeme_miktar_pozitif'),
        ),
        migrations.AddConstraint(
            model_name='pozplan',
            constraint=models.UniqueConstraint(fields=('tenant', 'proje', 'poz', 'yil'), name='uniq_poz_plan_tenant_proje_poz_yil'),
        ),
        migrations.AddConstraint(
            model_name='pozplan',
            constraint=models.CheckConstraint(condition=models.Q(('gercek_miktar__gte', 0)), name='check_poz_plan_gercek_pozitif'),
        ),
        migrations.AddConstraint(
            model_name='pozplan',
            constraint=models.CheckConstraint(condition=models.Q(('planlanan_baslangic__isnull', True), ('planlanan_bitis__isnull', True), ('planlanan_bitis__gte', models.F('planlanan_baslangic')), _connector='OR'), name='check_poz_plan_tarih_sirasi'),
        ),
        migrations.AddConstraint(
            model_name='kalitekabulteminati',
            constraint=models.UniqueConstraint(fields=('tenant', 'proje', 'tarih'), name='uniq_tenant_proje_tarih_kabul'),
        ),
        migrations.AddConstraint(
            model_name='hakedis',
            constraint=models.UniqueConstraint(fields=('tenant', 'proje', 'donem'), name='uniq_hakedis_tenant_proje_donem'),
        ),
        migrations.AddConstraint(
            model_name='ada',
            constraint=models.UniqueConstraint(fields=('tenant', 'kod'), name='uniq_ada_tenant_kod'),
        ),
        migrations.AddConstraint(
            model_name='santiyegunlugu',
            constraint=models.UniqueConstraint(fields=('tenant', 'proje', 'tarih'), name='uniq_gunluk_tenant_proje_tarih'),
        ),
        migrations.AddConstraint(
            model_name='taseronsozlesi',
            constraint=models.UniqueConstraint(fields=('tenant', 'proje'), name='uniq_tenant_proje_sozlesi'),
        ),
        migrations.AddConstraint(
            model_name='tedarikci',
            constraint=models.UniqueConstraint(fields=('tenant', 'firma_kodu'), name='uniq_tenant_firma_kodu'),
        ),
        migrations.AddConstraint(
            model_name='malzemetedarikciiliskisi',
            constraint=models.UniqueConstraint(fields=('tenant', 'malzeme', 'tedarikci'), name='uniq_malzeme_tedarikci_tenant'),
        ),
        migrations.AddConstraint(
            model_name='yapisinifibirimmaliyet',
            constraint=models.UniqueConstraint(fields=('tenant', 'sinif_kodu', 'yil'), name='uniq_yapi_sinifi_yil_tenant'),
        ),
        migrations.AddConstraint(
            model_name='proje',
            constraint=models.UniqueConstraint(fields=('tenant', 'proje_kodu'), name='uniq_proje_tenant_kod'),
        ),
    ]
