# Generated by Django 6.1.1 on 2026-09-17 22:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('cari', '0001_initial'),
        ('construction', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hakedis',
            options={'ordering': ['-donem_baslangic', '-id'], 'verbose_name': 'Hakediş', 'verbose_name_plural': 'Hakedişler'},
        ),
        migrations.AlterModelOptions(
            name='kalitekontrol',
            options={'ordering': ['-tarih', '-id'], 'verbose_name': 'Kalite Kontrol', 'verbose_name_plural': 'Kalite Kontrolleri'},
        ),
        migrations.AlterModelOptions(
            name='santiyegunlugu',
            options={'ordering': ['-tarih', '-id'], 'verbose_name': 'Şantiye Günlüğü', 'verbose_name_plural': 'Şantiye Günlükleri'},
        ),
        migrations.RemoveConstraint(
            model_name='hakedis',
            name='uniq_hakedis_tenant_proje_donem',
        ),
        migrations.RemoveField(
            model_name='kalitekontrol',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='kalitekontrol',
            name='kontrol_turu',
        ),
        migrations.RemoveField(
            model_name='kalitekontrol',
            name='sonuc',
        ),
        migrations.RemoveField(
            model_name='santiyegunlugu',
            name='ekip',
        ),
        migrations.RemoveField(
            model_name='santiyegunlugu',
            name='yapilan_is',
        ),
        migrations.AddField(
            model_name='hakedis',
            name='donem_baslangic',
            field=models.DateField(default='2026-01-01', verbose_name='Dönem Başlangıç'),
        ),
        migrations.AddField(
            model_name='hakedis',
            name='donem_bitis',
            field=models.DateField(default='2026-01-31', verbose_name='Dönem Bitiş'),
        ),
        migrations.AddField(
            model_name='hakedis',
            name='hakedis_no',
            field=models.CharField(default='HKD-0001', max_length=50, verbose_name='Hakediş No'),
        ),
        migrations.AddField(
            model_name='hakedis',
            name='kesinti_toplam',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Kesinti Toplamı'),
        ),
        migrations.AddField(
            model_name='hakedis',
            name='muhasebe_durumu',
            field=models.CharField(choices=[('bekliyor', 'Bekliyor'), ('nakledildi', 'Nakledildi'), ('hata', 'Hata'), ('iptal', 'İptal')], default='bekliyor', max_length=20, verbose_name='Muhasebe Durumu'),
        ),
        migrations.AddField(
            model_name='hakedis',
            name='net_tutar',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Net Tutar'),
        ),
        migrations.AddField(
            model_name='hakedis',
            name='toplam_tutar',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Toplam Tutar'),
        ),
        migrations.AddField(
            model_name='hakedissatiri',
            name='bu_donem_miktar',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Bu Dönem Miktar'),
        ),
        migrations.AddField(
            model_name='hakedissatiri',
            name='kumulatif_miktar',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Kümülatif Miktar'),
        ),
        migrations.AddField(
            model_name='hakedissatiri',
            name='onceki_miktar',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Önceki Miktar'),
        ),
        migrations.AddField(
            model_name='kalitekontrol',
            name='beklenen_deger',
            field=models.CharField(blank=True, max_length=255, verbose_name='Beklenen Değer'),
        ),
        migrations.AddField(
            model_name='kalitekontrol',
            name='durum',
            field=models.CharField(choices=[('beklemede', 'Beklemede'), ('gecti', 'Geçti'), ('kaldi', 'Kaldı'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi')], default='beklemede', max_length=20, verbose_name='Durum'),
        ),
        migrations.AddField(
            model_name='kalitekontrol',
            name='ek_gorseller',
            field=models.JSONField(blank=True, default=list, verbose_name='Ek Görseller'),
        ),
        migrations.AddField(
            model_name='kalitekontrol',
            name='kontrol_eden',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='kalite_kontrol_eden', to=settings.AUTH_USER_MODEL, verbose_name='Kontrol Eden'),
        ),
        migrations.AddField(
            model_name='kalitekontrol',
            name='kontrol_tipi',
            field=models.CharField(choices=[('malzeme', 'Malzeme Kontrolü'), ('iscilik', 'İşçilik Kontrolü'), ('boyut', 'Boyut Ölçümü'), ('test', 'Test/Analiz'), ('goruntuleme', 'Görsel İnceleme'), ('diger', 'Diğer')], default='malzeme', max_length=20, verbose_name='Kontrol Tipi'),
        ),
        migrations.AddField(
            model_name='kalitekontrol',
            name='olculen_deger',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ölçülen Değer'),
        ),
        migrations.AddField(
            model_name='kalitekontrol',
            name='onay_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Onay Tarihi'),
        ),
        migrations.AddField(
            model_name='kalitekontrol',
            name='onaylayan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kalite_kontrol_onaylayan', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan'),
        ),
        migrations.AddField(
            model_name='kalitekontrol',
            name='tolerek_aralik',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tolerans Aralığı'),
        ),
        migrations.AddField(
            model_name='santiyegunlugu',
            name='calisma_saati',
            field=models.PositiveIntegerField(default=8, verbose_name='Çalışma Saati'),
        ),
        migrations.AddField(
            model_name='santiyegunlugu',
            name='ekipmanlar',
            field=models.TextField(blank=True, verbose_name='Ekipmanlar'),
        ),
        migrations.AddField(
            model_name='santiyegunlugu',
            name='isci_sayisi',
            field=models.PositiveIntegerField(default=0, verbose_name='İşçi Sayısı'),
        ),
        migrations.AddField(
            model_name='santiyegunlugu',
            name='isci_tipi',
            field=models.CharField(choices=[('usta', 'Usta'), ('cirak', 'Çırak'), ('genel', 'Genel İşçi'), ('makine_operatoru', 'Makine Operatörü'), ('muhendis', 'Mühendis'), ('tekniker', 'Teknisyen'), ('guvenlik', 'Güvenlik')], default='genel', max_length=20, verbose_name='İşçi Tipi'),
        ),
        migrations.AddField(
            model_name='santiyegunlugu',
            name='malzeme_cikis',
            field=models.TextField(blank=True, verbose_name='Malzeme Çıkış'),
        ),
        migrations.AddField(
            model_name='santiyegunlugu',
            name='malzeme_giris',
            field=models.TextField(blank=True, verbose_name='Malzeme Giriş'),
        ),
        migrations.AddField(
            model_name='santiyegunlugu',
            name='sicaklik_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sıcaklık Max (°C)'),
        ),
        migrations.AddField(
            model_name='santiyegunlugu',
            name='sicaklik_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sıcaklık Min (°C)'),
        ),
        migrations.AddField(
            model_name='santiyegunlugu',
            name='yapilan_isler',
            field=models.TextField(default='', verbose_name='Yapılan İşler'),
        ),
        migrations.AlterField(
            model_name='hakedis',
            name='cari',
            field=models.ForeignKey(blank=True, help_text='Taşeron/yüklenici cari kartı (onayda Cari Hareket buraya işlenir).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hakedisler', to='cari.cari', verbose_name='Taşeron / Cari'),
        ),
        migrations.AlterField(
            model_name='hakedis',
            name='durum',
            field=models.CharField(choices=[('taslak', 'Taslak'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi'), ('odendi', 'Ödendi')], default='taslak', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='kalitekontrol',
            name='aciklama',
            field=models.TextField(blank=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='kalitekontrol',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma'),
        ),
        migrations.AlterField(
            model_name='kalitekontrol',
            name='duzeltici_faaliyet',
            field=models.TextField(blank=True, verbose_name='Düzeltici Faaliyet'),
        ),
        migrations.AlterField(
            model_name='kalitekontrol',
            name='kriter',
            field=models.CharField(max_length=255, verbose_name='Kriter'),
        ),
        migrations.AlterField(
            model_name='kalitekontrol',
            name='poz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kalite_kontrolleri', to='construction.poz', verbose_name='Poz'),
        ),
        migrations.AlterField(
            model_name='kalitekontrol',
            name='proje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kalite_kontrolleri', to='construction.proje', verbose_name='Proje'),
        ),
        migrations.AlterField(
            model_name='kalitekontrol',
            name='tarih',
            field=models.DateField(default='2026-01-01', verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='kalitekontrol',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme'),
        ),
        migrations.AlterField(
            model_name='santiyegunlugu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma'),
        ),
        migrations.AlterField(
            model_name='santiyegunlugu',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='santiye_gunlukleri', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AlterField(
            model_name='santiyegunlugu',
            name='hava_durumu',
            field=models.CharField(choices=[('gunesli', 'Güneşli'), ('parcali_bulutlu', 'Parçalı Bulutlu'), ('bulutlu', 'Bulutlu'), ('yagmurlu', 'Yağmurlu'), ('saganak', 'Sağanak'), ('karli', 'Karlı'), ('sisli', 'Sisli')], default='gunesli', max_length=20, verbose_name='Hava Durumu'),
        ),
        migrations.AlterField(
            model_name='santiyegunlugu',
            name='notlar',
            field=models.TextField(blank=True, verbose_name='Notlar'),
        ),
        migrations.AlterField(
            model_name='santiyegunlugu',
            name='proje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gunlukler', to='construction.proje', verbose_name='Proje'),
        ),
        migrations.AlterField(
            model_name='santiyegunlugu',
            name='sorunlar',
            field=models.TextField(blank=True, verbose_name='Sorunlar'),
        ),
        migrations.AlterField(
            model_name='santiyegunlugu',
            name='tarih',
            field=models.DateField(default='2026-01-01', verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='santiyegunlugu',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme'),
        ),
        migrations.AddConstraint(
            model_name='hakedis',
            constraint=models.UniqueConstraint(fields=('tenant', 'hakedis_no'), name='uniq_hakedis_tenant_no'),
        ),
        migrations.RemoveField(
            model_name='hakedis',
            name='donem',
        ),
    ]
