# Generated by Django 6.1.1 on 2026-09-18 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0006_tedarikciteklifi'),
    ]

    operations = [
        migrations.CreateModel(
            name="EKB",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("belge_no", models.CharField(max_length=100, verbose_name="Belge Numarası")),
                ("durum", models.CharField(choices=[("taslak", "Taslak"), ("basvuru", "Başvuru Yapıldı"), ("inceleme", "İncelemede"), ("onaylandi", "Onaylandı"), ("reddedildi", "Reddedildi"), ("yenileme", "Yenileme Gerekli")], default="taslak", max_length=20)),
                ("enerji_sinifi", models.CharField(blank=True, choices=[("A+", "A+"), ("A", "A"), ("B", "B"), ("C", "C"), ("D", "D"), ("E", "E"), ("F", "F"), ("G", "G")], max_length=2)),
                ("duzenlenme_tarihi", models.DateField(blank=True, null=True, verbose_name="Düzenlenme Tarihi")),
                ("gecerlilik_tarihi", models.DateField(blank=True, null=True, verbose_name="Geçerlilik Tarihi")),
                ("duzenleyen", models.CharField(blank=True, max_length=255, verbose_name="Düzenleyen")),
                ("notlar", models.TextField(blank=True, verbose_name="Notlar")),
                ("dokuman_referansi", models.CharField(blank=True, max_length=500, verbose_name="Doküman Referansı")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Güncellenme")),
                ("proje", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ekb_belgeleri", to="construction.proje", verbose_name="Proje")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="tenants.tenant", verbose_name="Tenant")),
            ],
            options={"ordering": ["-gecerlilik_tarihi", "proje"], "verbose_name": "Enerji Kimlik Belgesi", "verbose_name_plural": "Enerji Kimlik Belgeleri"},
        ),
        migrations.AddConstraint(
            model_name="ekb",
            constraint=models.UniqueConstraint(fields=("tenant", "belge_no"), name="uniq_ekb_tenant_belge_no"),
        ),
        migrations.AddConstraint(
            model_name="ekb",
            constraint=models.CheckConstraint(condition=models.Q(("gecerlilik_tarihi__isnull", True)) | models.Q(("duzenlenme_tarihi__isnull", True)) | models.Q(("gecerlilik_tarihi__gt", models.F("duzenlenme_tarihi"))), name="check_ekb_gecerlilik_duzenlenme_sonrasi"),
        ),
    ]
