# Generated by Django 6.1.1 on 2026-09-21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0020_pozfiyat_source_fields'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjePozFiyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil', models.PositiveSmallIntegerField(verbose_name='Yıl')),
                ('birim_fiyat', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Birim Fiyat (₺)')),
                ('kaynak', models.CharField(blank=True, default='', help_text='Örn. Proje özel teklif, tedarikçi fiyatı', max_length=100, verbose_name='Kaynak')),
                ('kaynak_url', models.URLField(blank=True, max_length=250, verbose_name='Kaynak URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('poz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proje_fiyatlari', to='construction.poz', verbose_name='Poz')),
                ('proje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poz_fiyatlari', to='construction.proje', verbose_name='Proje')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Proje Poz Fiyatı',
                'verbose_name_plural': 'Proje Poz Fiyatları',
                'ordering': ['proje__proje_kodu', 'poz__poz_no', '-yil'],
            },
        ),
        migrations.AddConstraint(
            model_name='projepozfiyat',
            constraint=models.UniqueConstraint(fields=('tenant', 'proje', 'poz', 'yil'), name='uniq_proje_poz_fiyat_tenant_proje_poz_yil', violation_error_message='Aynı proje ve poz için aynı yılda yalnızca bir fiyat kaydı olabilir.'),
        ),
    ]