# Generated by Django 6.1.1 on 2026-09-21 11:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cari', '0006_reconcile_carihareket_fatura_schema'),
        ('construction', '0022_faz2_malzeme_sistemi'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ada',
            name='uniq_ada_tenant_kod',
        ),
        migrations.RemoveField(
            model_name='riskliyapı',
            name='ada',
        ),
        migrations.RemoveField(
            model_name='kirasozlesi',
            name='ada',
        ),
        migrations.RemoveField(
            model_name='kirasozlesi',
            name='parsell',
        ),
        migrations.RemoveField(
            model_name='kirasozlesi',
            name='proje',
        ),
        migrations.RemoveField(
            model_name='kirasozlesi',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='tahliyesuresi',
            name='kirasozlesi',
        ),
        migrations.RemoveConstraint(
            model_name='parsel',
            name='uniq_parsel_ada_no',
        ),
        migrations.RemoveField(
            model_name='riskliyapı',
            name='parsell',
        ),
        migrations.RemoveField(
            model_name='riskliyapı',
            name='proje',
        ),
        migrations.RemoveField(
            model_name='riskliyapı',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='sözlesentemplate',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='tahliyesuresi',
            name='tenant',
        ),
        migrations.AlterModelOptions(
            name='hakedis',
            options={'ordering': ['-donem', 'proje__proje_kodu'], 'verbose_name': 'Hakediş', 'verbose_name_plural': 'Hakedişler'},
        ),
        migrations.AlterModelOptions(
            name='kalitekabulteminati',
            options={'ordering': ['-tarih', '-id'], 'verbose_name': 'Kalite Kabul Teminatı', 'verbose_name_plural': 'Kalite Kaufmanninatı'},
        ),
        migrations.AlterModelOptions(
            name='nakliyemesafe',
            options={'ordering': ['proje', 'poz']},
        ),
        migrations.AlterModelOptions(
            name='pozanaliz',
            options={'ordering': ['poz', 'satir_no', 'id']},
        ),
        migrations.AlterModelOptions(
            name='pozfiyat',
            options={'ordering': ['-yil', 'donem'], 'verbose_name': 'Poz Birim Fiyatı', 'verbose_name_plural': 'Poz Birim Fiyatları'},
        ),
        migrations.RemoveConstraint(
            model_name='pozfiyat',
            name='uniq_poz_fiyat_yil',
        ),
        migrations.AlterField(
            model_name='hakedis',
            name='cari',
            field=models.ForeignKey(blank=True, help_text='Taşeron/yüklenici cari kartı (onayda Cari Hareket buraya işlenir).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hakedisler', to='cari.cari', verbose_name='Yüklenici / Cari'),
        ),
        migrations.AlterField(
            model_name='hakedis',
            name='donem',
            field=models.CharField(help_text='Hakediş dönemi, örn. 2026-03.', max_length=7, verbose_name='Dönem (YYYY-MM)'),
        ),
        migrations.AlterField(
            model_name='hakedis',
            name='durum',
            field=models.CharField(choices=[('taslak', 'Taslak'), ('onaylandi', 'Onaylandı'), ('iptal', 'İptal')], default='taslak', max_length=10, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='ifcimportjob',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ifc_import_jobs', to='construction.proje', verbose_name='Proje'),
        ),
        migrations.AlterField(
            model_name='ifcimportjob',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='ifcquantitydraft',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='kalitekontrol',
            name='kontrol_eden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kalite_kontrol_eden', to=settings.AUTH_USER_MODEL, verbose_name='Kontrol Eden'),
        ),
        migrations.AlterField(
            model_name='kalitekontrol',
            name='tarih',
            field=models.DateField(verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='nakliyemesafe',
            name='k_katsayisi',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='nakliyemesafe',
            name='mesafe_km',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='pozanaliz',
            name='miktar',
            field=models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
        migrations.AlterField(
            model_name='pozfiyat',
            name='gecerlilik_tarihi',
            field=models.DateField(blank=True, help_text='Fiyatın geçerli olduğu tarih (örn. fatura tarihi)', null=True, verbose_name='Geçerlilik Tarihi'),
        ),
        migrations.AlterField(
            model_name='pozfiyat',
            name='ice_aktarma_tarihi',
            field=models.DateTimeField(auto_now_add=True, help_text='Kayıt sisteme eklenme tarihi', verbose_name='İçe Aktarma Tarihi'),
        ),
        migrations.AlterField(
            model_name='pozfiyat',
            name='kaynak',
            field=models.CharField(blank=True, default='', help_text='Örn. ÇŞİDB 2026 tebliği', max_length=100, verbose_name='Kaynak'),
        ),
        migrations.AlterField(
            model_name='pozfiyat',
            name='kaynak_url',
            field=models.URLField(blank=True, help_text='Fiyatın duyurulduğu bağlantı', max_length=250, verbose_name='Kaynak URL'),
        ),
        migrations.AlterField(
            model_name='pozfiyat',
            name='yayin_tarihi',
            field=models.DateField(blank=True, help_text='Fiyatın yayımlanadığı tarih', null=True, verbose_name='Yayın Tarihi'),
        ),
        migrations.AlterField(
            model_name='santiyegunlugu',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='santiye_gunlukleri', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AlterField(
            model_name='santiyegunlugu',
            name='tarih',
            field=models.DateField(verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='santiyegunlugu',
            name='yapilan_isler',
            field=models.TextField(verbose_name='Yapılan İşler'),
        ),
        migrations.AlterField(
            model_name='tedarikci',
            name='firma_kodu',
            field=models.CharField(max_length=30, unique=True, verbose_name='Firma Kodu'),
        ),
        migrations.AddConstraint(
            model_name='pozfiyat',
            constraint=models.UniqueConstraint(fields=('tenant', 'poz', 'yil', 'donem'), name='uniq_poz_fiyat_yil_donem', violation_error_message='Aynı poz için aynı yıl ve dönemde yalnızca bir fiyat kaydı olabilir.'),
        ),
        migrations.RemoveField(
            model_name='ada',
            name='proje',
        ),
        migrations.RemoveField(
            model_name='ada',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='Kirasozlesi',
        ),
        migrations.RemoveField(
            model_name='parsel',
            name='ada',
        ),
        migrations.RemoveField(
            model_name='parsel',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='RiskliYapı',
        ),
        migrations.DeleteModel(
            name='SözlesenTemplate',
        ),
        migrations.DeleteModel(
            name='TahliyeSuresi',
        ),
        migrations.DeleteModel(
            name='Ada',
        ),
        migrations.DeleteModel(
            name='Parsel',
        ),
    ]
