# Generated by Django 6.1.1 on 2026-09-21 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0023_remove_ada_uniq_ada_tenant_kod_remove_riskliyapı_ada_and_more'),
    ]

    # STABILIZASYON (2026-09-22): 0004_hakedis_donem_compatibility hakedis_no
    # kolonunu dusurdugunde PostgreSQL bu kolona bagli uniq_hakedis_tenant_no
    # constraint'ini otomatik kaldirdi. State'te ise kayit kaldi. Sifirdan
    # kurulumda (test DB) ve mevcut dev DB'de constraint zaten yok; normal
    # RemoveConstraint "does not exist" hatasi veriyordu. State duzeltmesi
    # korunup DB operasyonu no-op yapildi; veri kaybi yoktur, --fake yok.
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='hakedis',
                    name='uniq_hakedis_tenant_no',
                ),
            ],
            database_operations=[],
        ),
    ]
