# Generated by Django 6.1.1 on 2026-09-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0024_remove_hakedis_uniq_hakedis_tenant_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tedarikci',
            name='firma_kodu',
            field=models.CharField(max_length=30, verbose_name='Firma Kodu'),
        ),
    ]
