# Generated by Django 6.1.1 on 2026-09-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0025_alter_tedarikci_firma_kodu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tedarikci',
            name='firma_kodu',
            field=models.CharField(max_length=30, unique=True, verbose_name='Firma Kodu'),
        ),
    ]
