# Generated by Django 6.1.1 on 2026-09-22
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('cari', '0006_reconcile_carihareket_fatura_schema'),
        ('construction', '0022_faz2_malzeme_sistemi'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Create missing tables if they don't exist using raw SQL
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS construction_malzeme_fiyat (
                id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                yil smallint NOT NULL,
                birim_fiyat numeric(14,2) NOT NULL CHECK (birim_fiyat >= 0.01),
                para_birimi varchar(3) NOT NULL DEFAULT 'TRY',
                kaynak varchar(100) NOT NULL DEFAULT '',
                kaynak_url varchar(250) NOT NULL DEFAULT '',
                is_active boolean NOT NULL DEFAULT TRUE,
                created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                malzeme_id bigint NOT NULL REFERENCES construction_malzeme(id),
                tenant_id bigint NOT NULL REFERENCES tenants_tenant(id)
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS construction_malzeme_fiyat;",
        ),
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS construction_proje_poz_malzeme (
                id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                proje_id bigint NOT NULL REFERENCES construction_proje(id),
                poz_id bigint NOT NULL REFERENCES construction_poz(id),
                kaynak_malzeme_id bigint NOT NULL REFERENCES construction_malzeme(id),
                etkin_malzeme_id bigint NOT NULL REFERENCES construction_malzeme(id),
                miktar_override numeric(14,4),
                aciklama text,
                is_active boolean NOT NULL DEFAULT TRUE,
                created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                tenant_id bigint NOT NULL REFERENCES tenants_tenant(id)
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS construction_proje_poz_malzeme;",
        ),
        # Add unique constraints if missing
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uniq_malzeme_fiyat_tenant_malzeme_yil') THEN
                    ALTER TABLE construction_malzeme_fiyat
                        ADD CONSTRAINT uniq_malzeme_fiyat_tenant_malzeme_yil UNIQUE (tenant_id, malzeme_id, yil);
                END IF;
            END $$;
            """,
            reverse_sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uniq_malzebe_fiyat_tenant_malzebe_yil') THEN
                    ALTER TABLE construction_malzebe_fiyat
                        DROP CONSTRAINT uniq_malzebe_fiyat_tenant_malzebe_yil;
                END IF;
            END $$;
            """,
        ),
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uniq_proje_poz_malzeme_tenant_proje_poz_kaynak') THEN
                    ALTER TABLE construction_proje_poz_malzeme
                        ADD CONSTRAINT uniq_proje_poz_malzeme_tenant_proje_poz_kaynak UNIQUE (tenant_id, proje_id, poz_id, kaynak_malzeme_id);
                END IF;
            END $$;
            """,
            reverse_sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uniq_proje_poz_malzeme_tenant_proje_poz_kaynak') THEN
                    ALTER TABLE construction_proje_poz_malzeme
                        DROP CONSTRAINT uniq_proje_poz_malzeme_tenant_proje_poz_kaynak;
                END IF;
            END $$;
            """,
        ),
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'check_proje_poz_malzeme_kaynak_etkin_farkli') THEN
                    ALTER TABLE construction_proje_poz_malzeme
                        ADD CONSTRAINT check_proje_poz_malzeme_kaynak_etkin_farkli
                        CHECK (kaynak_malzeme_id <> etkin_malzebe_id);
                END IF;
            END $$;
            """,
            reverse_sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'check_proje_poz_malzeme_kaynak_etkin_farkli') THEN
                    ALTER TABLE construction_proje_poz_malzeme
                        DROP CONSTRAINT check_proje_poz_malzeme_kaynak_etkin_farkli;
                END IF;
            END $$;
            """,
        ),
        # TODO: Append the operations from migrations 0023-0026 here,
        # converting deletions to SeparateDatabaseAndState(state_only).
]