# Generated by Django 6.1.1 on 2026-09-21 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0026_alter_tedarikci_firma_kodu'),
        ('construction', '0027_reconcile_missing_tables'),
    ]

    operations = [
    ]
