# Generated by Django 6.1.1 on 2026-09-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0028_merge_20260922_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='santiyegunlugu',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
    ]
