# Generated by Django 6.1.1 on 2026-09-22 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cari', '0006_reconcile_carihareket_fatura_schema'),
        ('construction', '0029_santiyegunlugu_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tedarikci',
            name='cari',
            field=models.ForeignKey(blank=True, help_text='Satın alma faturası bu cari karta işlenir (FAZ 4).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tedarikciler', to='cari.cari', verbose_name='Cari Kart'),
        ),
    ]
