# Generated by Django 6.1.1 on 2026-09-22 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0030_tedarikci_cari'),
    ]

    operations = [
        migrations.AddField(
            model_name='pozplan',
            name='metraj',
            field=models.ForeignKey(blank=True, help_text='Gerçekleşen miktar bir metrajdan alındıysa bağlantı (FAZ 5).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poz_planlari', to='construction.metraj', verbose_name='Kaynak Metraj'),
        ),
        migrations.AddField(
            model_name='yaklasikmaliyetsatiri',
            name='metraj',
            field=models.ForeignKey(blank=True, help_text='Satır bir metrajdan üretildiyse bağlantı (FAZ 5).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maliyet_satirlari', to='construction.metraj', verbose_name='Kaynak Metraj'),
        ),
    ]
