# Generated by Django 6.1.1 on 2026-09-17 19:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HesapPlani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=20, verbose_name='Hesap Kodu')),
                ('ad', models.CharField(max_length=200, verbose_name='Hesap Adı')),
                ('tip', models.CharField(choices=[('aktif', 'Aktif'), ('pasif', 'Pasif'), ('gelir', 'Gelir'), ('gider', 'Gider'), ('nazim', 'Nazım')], default='aktif', max_length=10, verbose_name='Hesap Tipi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Hesap Planı',
                'verbose_name_plural': 'Hesap Planı',
                'ordering': ['kod'],
            },
        ),
        migrations.CreateModel(
            name='MuhasebeFisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fis_no', models.CharField(max_length=30, verbose_name='Fiş No')),
                ('fis_tarihi', models.DateField(verbose_name='Fiş Tarihi')),
                ('aciklama', models.CharField(blank=True, max_length=255, verbose_name='Açıklama')),
                ('durum', models.CharField(choices=[('taslak', 'Taslak'), ('kayitli', 'Kayıtlı'), ('iptal', 'İptal')], default='taslak', max_length=10, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Muhasebe Fişi',
                'verbose_name_plural': 'Muhasebe Fişleri',
                'ordering': ['-fis_tarihi', 'fis_no'],
            },
        ),
        migrations.CreateModel(
            name='FisSatiri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borc', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Borç (₺)')),
                ('alacak', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Alacak (₺)')),
                ('aciklama', models.CharField(blank=True, max_length=255, verbose_name='Açıklama')),
                ('hesap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='satirlar', to='accounting.hesapplani', verbose_name='Hesap')),
                ('fis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='satirlar', to='accounting.muhasebefisi', verbose_name='Fiş')),
            ],
            options={
                'verbose_name': 'Fiş Satırı',
                'verbose_name_plural': 'Fiş Satırları',
            },
        ),
        migrations.AddConstraint(
            model_name='hesapplani',
            constraint=models.UniqueConstraint(fields=('tenant', 'kod'), name='uniq_hesap_tenant_kod'),
        ),
        migrations.AddConstraint(
            model_name='muhasebefisi',
            constraint=models.UniqueConstraint(fields=('tenant', 'fis_no'), name='uniq_fis_tenant_no'),
        ),
    ]
