from django.db import migrations


TDHP_HESAPLARI = [
    # kod, ad, tip, normal bakiye
    ("1", "Dönen Varlıklar", "aktif", "borc"),
    ("10", "Hazır Değerler", "aktif", "borc"),
    ("100", "Kasa", "aktif", "borc"),
    ("101", "Alınan Çekler", "aktif", "borc"),
    ("102", "Bankalar", "aktif", "borc"),
    ("103", "Verilen Çekler ve Ödeme Emirleri (-)", "aktif", "alacak"),
    ("108", "Diğer Hazır Değerler", "aktif", "borc"),
    ("11", "Menkul Kıymetler", "aktif", "borc"),
    ("110", "Hisse Senetleri", "aktif", "borc"),
    ("111", "Özel Kesim Tahvil, Senet ve Bonoları", "aktif", "borc"),
    ("112", "Kamu Kesimi Tahvil, Senet ve Bonoları", "aktif", "borc"),
    ("118", "Diğer Menkul Kıymetler", "aktif", "borc"),
    ("119", "Menkul Kıymetler Değer Düşüklüğü Karşılığı (-)", "aktif", "alacak"),
    ("12", "Ticari Alacaklar", "aktif", "borc"),
    ("120", "Alıcılar", "aktif", "borc"),
    ("121", "Alacak Senetleri", "aktif", "borc"),
    ("122", "Alacak Senetleri Reeskontu (-)", "aktif", "alacak"),
    ("126", "Verilen Depozito ve Teminatlar", "aktif", "borc"),
    ("128", "Şüpheli Ticari Alacaklar", "aktif", "borc"),
    ("129", "Şüpheli Ticari Alacaklar Karşılığı (-)", "aktif", "alacak"),
    ("13", "Diğer Alacaklar", "aktif", "borc"),
    ("131", "Ortaklardan Alacaklar", "aktif", "borc"),
    ("135", "Personelden Alacaklar", "aktif", "borc"),
    ("136", "Diğer Çeşitli Alacaklar", "aktif", "borc"),
    ("139", "Şüpheli Diğer Alacaklar Karşılığı (-)", "aktif", "alacak"),
    ("15", "Stoklar", "aktif", "borc"),
    ("150", "İlk Madde ve Malzeme", "aktif", "borc"),
    ("151", "Yarı Mamuller - Üretim", "aktif", "borc"),
    ("152", "Mamuller", "aktif", "borc"),
    ("153", "Ticari Mallar", "aktif", "borc"),
    ("157", "Diğer Stoklar", "aktif", "borc"),
    ("158", "Stok Değer Düşüklüğü Karşılığı (-)", "aktif", "alacak"),
    ("18", "Gelecek Aylara Ait Giderler ve Gelir Tahakkukları", "aktif", "borc"),
    ("180", "Gelecek Aylara Ait Giderler", "aktif", "borc"),
    ("181", "Gelir Tahakkukları", "aktif", "borc"),
    ("19", "Diğer Dönen Varlıklar", "aktif", "borc"),
    ("190", "Devreden KDV", "aktif", "borc"),
    ("191", "İndirilecek KDV", "aktif", "borc"),
    ("192", "Diğer KDV", "aktif", "borc"),
    ("193", "Peşin Ödenen Vergiler ve Fonlar", "aktif", "borc"),
    ("196", "Personel Avansları", "aktif", "borc"),
    ("197", "Sayım ve Tesellüm Noksanları", "aktif", "borc"),
    ("2", "Duran Varlıklar", "aktif", "borc"),
    ("22", "Ticari Alacaklar", "aktif", "borc"),
    ("220", "Alıcılar", "aktif", "borc"),
    ("226", "Verilen Depozito ve Teminatlar", "aktif", "borc"),
    ("24", "Mali Duran Varlıklar", "aktif", "borc"),
    ("240", "Bağlı Menkul Kıymetler", "aktif", "borc"),
    ("242", "İştirakler", "aktif", "borc"),
    ("245", "Bağlı Ortaklıklar", "aktif", "borc"),
    ("25", "Maddi Duran Varlıklar", "aktif", "borc"),
    ("250", "Arazi ve Arsalar", "aktif", "borc"),
    ("251", "Yeraltı ve Yerüstü Düzenleri", "aktif", "borc"),
    ("252", "Binalar", "aktif", "borc"),
    ("253", "Tesis, Makine ve Cihazlar", "aktif", "borc"),
    ("254", "Taşıtlar", "aktif", "borc"),
    ("255", "Demirbaşlar", "aktif", "borc"),
    ("257", "Birikmiş Amortismanlar (-)", "aktif", "alacak"),
    ("258", "Yapılmakta Olan Yatırımlar", "aktif", "borc"),
    ("26", "Maddi Olmayan Duran Varlıklar", "aktif", "borc"),
    ("260", "Haklar", "aktif", "borc"),
    ("264", "Özel Maliyetler", "aktif", "borc"),
    ("267", "Diğer Maddi Olmayan Duran Varlıklar", "aktif", "borc"),
    ("268", "Birikmiş Amortismanlar (-)", "aktif", "alacak"),
    ("27", "Özel Tükenmeye Tabi Varlıklar", "aktif", "borc"),
    ("28", "Gelecek Yıllara Ait Giderler ve Gelir Tahakkukları", "aktif", "borc"),
    ("29", "Diğer Duran Varlıklar", "aktif", "borc"),
    ("3", "Kısa Vadeli Yabancı Kaynaklar", "pasif", "alacak"),
    ("30", "Mali Borçlar", "pasif", "alacak"),
    ("300", "Banka Kredileri", "pasif", "alacak"),
    ("303", "Uzun Vadeli Kredilerin Anapara Taksitleri ve Faizleri", "pasif", "alacak"),
    ("32", "Ticari Borçlar", "pasif", "alacak"),
    ("320", "Satıcılar", "pasif", "alacak"),
    ("321", "Borç Senetleri", "pasif", "alacak"),
    ("322", "Borç Senetleri Reeskontu (-)", "pasif", "borc"),
    ("326", "Alınan Depozito ve Teminatlar", "pasif", "alacak"),
    ("33", "Diğer Borçlar", "pasif", "alacak"),
    ("335", "Personele Borçlar", "pasif", "alacak"),
    ("336", "Diğer Çeşitli Borçlar", "pasif", "alacak"),
    ("34", "Alınan Avanslar", "pasif", "alacak"),
    ("340", "Alınan Sipariş Avansları", "pasif", "alacak"),
    ("36", "Ödenecek Vergi ve Diğer Yükümlülükler", "pasif", "alacak"),
    ("360", "Ödenecek Vergi ve Fonlar", "pasif", "alacak"),
    ("361", "Ödenecek Sosyal Güvenlik Kesintileri", "pasif", "alacak"),
    ("368", "Vadesi Geçmiş, Ertelenmiş veya Taksitlendirilmiş Vergi ve Diğer Yükümlülükler", "pasif", "alacak"),
    ("37", "Borç ve Gider Karşılıkları", "pasif", "alacak"),
    ("370", "Dönem Kârı Vergi ve Diğer Yasal Yükümlülük Karşılıkları", "pasif", "alacak"),
    ("38", "Gelecek Aylara Ait Gelirler ve Gider Tahakkukları", "pasif", "alacak"),
    ("380", "Gelecek Aylara Ait Gelirler", "pasif", "alacak"),
    ("381", "Gider Tahakkukları", "pasif", "alacak"),
    ("39", "Diğer Kısa Vadeli Yabancı Kaynaklar", "pasif", "alacak"),
    ("4", "Uzun Vadeli Yabancı Kaynaklar", "pasif", "alacak"),
    ("40", "Mali Borçlar", "pasif", "alacak"),
    ("400", "Banka Kredileri", "pasif", "alacak"),
    ("42", "Ticari Borçlar", "pasif", "alacak"),
    ("420", "Satıcılar", "pasif", "alacak"),
    ("43", "Diğer Borçlar", "pasif", "alacak"),
    ("44", "Alınan Avanslar", "pasif", "alacak"),
    ("47", "Borç ve Gider Karşılıkları", "pasif", "alacak"),
    ("472", "Kıdem Tazminatı Karşılığı", "pasif", "alacak"),
    ("48", "Gelecek Yıllara Ait Gelirler ve Gider Tahakkukları", "pasif", "alacak"),
    ("49", "Diğer Uzun Vadeli Yabancı Kaynaklar", "pasif", "alacak"),
    ("5", "Öz Kaynaklar", "pasif", "alacak"),
    ("50", "Ödenmiş Sermaye", "pasif", "alacak"),
    ("500", "Sermaye", "pasif", "alacak"),
    ("501", "Ödenmemiş Sermaye (-)", "pasif", "borc"),
    ("52", "Sermaye Yedekleri", "pasif", "alacak"),
    ("520", "Hisse Senedi İhraç Primleri", "pasif", "alacak"),
    ("54", "Kâr Yedekleri", "pasif", "alacak"),
    ("540", "Yasal Yedekler", "pasif", "alacak"),
    ("542", "Olağanüstü Yedekler", "pasif", "alacak"),
    ("57", "Geçmiş Yıllar Kârları", "pasif", "alacak"),
    ("570", "Geçmiş Yıllar Kârları", "pasif", "alacak"),
    ("58", "Geçmiş Yıllar Zararları", "pasif", "borc"),
    ("580", "Geçmiş Yıllar Zararları (-)", "pasif", "borc"),
    ("59", "Dönem Net Kârı (Zararı)", "pasif", "alacak"),
    ("590", "Dönem Net Kârı", "pasif", "alacak"),
    ("591", "Dönem Net Zararı (-)", "pasif", "borc"),
    ("6", "Gelir Tablosu Hesapları", "gelir", "alacak"),
    ("60", "Brüt Satışlar", "gelir", "alacak"),
    ("600", "Yurtiçi Satışlar", "gelir", "alacak"),
    ("601", "Yurtdışı Satışlar", "gelir", "alacak"),
    ("602", "Diğer Gelirler", "gelir", "alacak"),
    ("61", "Satış İndirimleri (-)", "gelir", "borc"),
    ("610", "Satıştan İadeler (-)", "gelir", "borc"),
    ("611", "Satış İskontoları (-)", "gelir", "borc"),
    ("62", "Satışların Maliyeti (-)", "gider", "borc"),
    ("620", "Satılan Mamuller Maliyeti (-)", "gider", "borc"),
    ("621", "Satılan Ticari Mallar Maliyeti (-)", "gider", "borc"),
    ("622", "Satılan Hizmet Maliyeti (-)", "gider", "borc"),
    ("63", "Faaliyet Giderleri (-)", "gider", "borc"),
    ("630", "Araştırma ve Geliştirme Giderleri (-)", "gider", "borc"),
    ("631", "Pazarlama, Satış ve Dağıtım Giderleri (-)", "gider", "borc"),
    ("632", "Genel Yönetim Giderleri (-)", "gider", "borc"),
    ("64", "Diğer Faaliyetlerden Olağan Gelir ve Kârlar", "gelir", "alacak"),
    ("640", "İştiraklerden Temettü Gelirleri", "gelir", "alacak"),
    ("642", "Faiz Gelirleri", "gelir", "alacak"),
    ("645", "Menkul Kıymetler Satış Kârları", "gelir", "alacak"),
    ("646", "Kambiyo Kârları", "gelir", "alacak"),
    ("649", "Diğer Olağan Gelir ve Kârlar", "gelir", "alacak"),
    ("65", "Diğer Faaliyetlerden Olağan Gider ve Zararlar (-)", "gider", "borc"),
    ("653", "Komisyon Giderleri (-)", "gider", "borc"),
    ("654", "Karşılık Giderleri (-)", "gider", "borc"),
    ("656", "Kambiyo Zararları (-)", "gider", "borc"),
    ("659", "Diğer Olağan Gider ve Zararlar (-)", "gider", "borc"),
    ("66", "Finansman Giderleri (-)", "gider", "borc"),
    ("660", "Kısa Vadeli Borçlanma Giderleri (-)", "gider", "borc"),
    ("67", "Olağandışı Gelir ve Kârlar", "gelir", "alacak"),
    ("679", "Diğer Olağandışı Gelir ve Kârlar", "gelir", "alacak"),
    ("68", "Olağandışı Gider ve Zararlar (-)", "gider", "borc"),
    ("689", "Diğer Olağandışı Gider ve Zararlar (-)", "gider", "borc"),
    ("69", "Dönem Net Kârı (Zararı)", "gelir", "alacak"),
    ("690", "Dönem Kârı veya Zararı", "gelir", "alacak"),
    ("691", "Dönem Kârı Vergi ve Diğer Yasal Yükümlülük Karşılıkları (-)", "gider", "borc"),
    ("7", "Maliyet Hesapları", "gider", "borc"),
    ("70", "Maliyet Muhasebesi Bağlantı Hesapları", "gider", "borc"),
    ("71", "Direkt İlk Madde ve Malzeme Giderleri", "gider", "borc"),
    ("710", "Direkt İlk Madde ve Malzeme Giderleri", "gider", "borc"),
    ("72", "Direkt İşçilik Giderleri", "gider", "borc"),
    ("720", "Direkt İşçilik Giderleri", "gider", "borc"),
    ("73", "Genel Üretim Giderleri", "gider", "borc"),
    ("730", "Genel Üretim Giderleri", "gider", "borc"),
    ("74", "Hizmet Üretim Maliyeti", "gider", "borc"),
    ("740", "Hizmet Üretim Maliyeti", "gider", "borc"),
    ("75", "Araştırma ve Geliştirme Giderleri", "gider", "borc"),
    ("750", "Araştırma ve Geliştirme Giderleri", "gider", "borc"),
    ("76", "Pazarlama, Satış ve Dağıtım Giderleri", "gider", "borc"),
    ("760", "Pazarlama, Satış ve Dağıtım Giderleri", "gider", "borc"),
    ("77", "Genel Yönetim Giderleri", "gider", "borc"),
    ("770", "Genel Yönetim Giderleri", "gider", "borc"),
    ("78", "Finansman Giderleri", "gider", "borc"),
    ("780", "Finansman Giderleri", "gider", "borc"),
    ("79", "Üretim Maliyeti Hesapları", "gider", "borc"),
    ("790", "İlk Madde ve Malzeme Giderleri", "gider", "borc"),
    ("791", "Direkt İşçilik Giderleri", "gider", "borc"),
    ("792", "Genel Üretim Giderleri", "gider", "borc"),
    ("8", "Serbest Hesaplar", "gider", "borc"),
    ("9", "Nazım Hesaplar", "nazim", "borc"),
    ("900", "Teminat Mektupları", "nazim", "borc"),
    ("901", "Teminat Mektupları Karşılığı", "nazim", "alacak"),
    ("910", "Kanunen Kabul Edilmeyen Giderler", "nazim", "borc"),
    ("911", "Kanunen Kabul Edilmeyen Giderler Karşılığı", "nazim", "alacak"),
]


def _tip_icin_detay(kod):
    return len(kod) >= 3


def yukle_td_hp(apps, schema_editor):
    HesapPlani = apps.get_model("accounting", "HesapPlani")
    Tenant = apps.get_model("tenants", "Tenant")
    hesaplar = {kod: (ad, tip, normal) for kod, ad, tip, normal in TDHP_HESAPLARI}

    for tenant in Tenant.objects.all().iterator():
        for kod, (ad, tip, normal) in hesaplar.items():
            ust_kod = kod[:-1] if len(kod) == 3 else (kod[:-1] if len(kod) == 2 else None)
            ust_hesap = HesapPlani.objects.filter(tenant=tenant, kod=ust_kod).first() if ust_kod else None
            HesapPlani.objects.update_or_create(
                tenant=tenant,
                kod=kod,
                defaults={
                    "ad": ad,
                    "tip": tip,
                    "ust_hesap": ust_hesap,
                    "seviye": len(kod),
                    "normal_bakiye": normal,
                    "detay_hesap_mi": _tip_icin_detay(kod),
                    "is_active": True,
                },
            )


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0002_hesap_hiyerarsisi"),
    ]

    operations = [
        migrations.RunPython(yukle_td_hp, migrations.RunPython.noop),
    ]
