from django.db import migrations


# 0003'teki listeye ek olarak TDHP'de yer alan eksik grup ve ana hesaplar.
# Yardımcı alt hesaplar (ör. 100.01) işletmeye göre değiştiği için seed edilmez.
EK_TDHP_HESAPLARI = [
    ("104", "Kambiyo Senetleri", "aktif", "borc"),
    ("105", "Bankalararası Takas Hesabı", "aktif", "borc"),
    ("106", "Kambiyo Senetleri Karşılığı", "aktif", "alacak"),
    ("107", "Diğer Hazır Değerler", "aktif", "borc"),
    ("109", "Diğer Hazır Değerler", "aktif", "borc"),
    ("123", "Bankalar", "aktif", "borc"),
    ("124", "Kazanılmamış Finansal Kiralama Faiz Gelirleri (-)", "aktif", "alacak"),
    ("125", "Kazanılmamış Finansal Kiralama Faiz Gelirleri", "aktif", "alacak"),
    ("127", "Diğer Ticari Alacaklar", "aktif", "borc"),
    ("132", "İştiraklerden Alacaklar", "aktif", "borc"),
    ("133", "Bağlı Ortaklıklardan Alacaklar", "aktif", "borc"),
    ("134", "Personelden Alacaklar", "aktif", "borc"),
    ("137", "Diğer Alacak Senetleri Reeskontu (-)", "aktif", "alacak"),
    ("138", "Şüpheli Diğer Alacaklar", "aktif", "borc"),
    ("140", "Devreden KDV", "aktif", "borc"),
    ("150", "İlk Madde ve Malzeme", "aktif", "borc"),
    ("170", "Yıllara Yaygın İnşaat ve Onarım Maliyetleri", "aktif", "borc"),
    ("171", "Yıllara Yaygın İnşaat ve Onarım Maliyetleri", "aktif", "borc"),
    ("172", "Yıllara Yaygın İnşaat ve Onarım Maliyetleri", "aktif", "borc"),
    ("173", "Yıllara Yaygın İnşaat ve Onarım Maliyetleri", "aktif", "borc"),
    ("174", "Yıllara Yaygın İnşaat ve Onarım Maliyetleri", "aktif", "borc"),
    ("175", "Yıllara Yaygın İnşaat ve Onarım Maliyetleri", "aktif", "borc"),
    ("176", "Yıllara Yaygın İnşaat ve Onarım Maliyetleri", "aktif", "borc"),
    ("177", "Yıllara Yaygın İnşaat ve Onarım Maliyetleri", "aktif", "borc"),
    ("178", "Yıllara Yaygın İnşaat ve Onarım Maliyetleri", "aktif", "borc"),
    ("179", "Taşeronlara Verilen Avanslar", "aktif", "borc"),
    ("198", "Diğer Çeşitli Dönen Varlıklar", "aktif", "borc"),
    ("199", "Diğer Dönen Varlıklar Karşılığı (-)", "aktif", "alacak"),
    ("221", "Alacak Senetleri", "aktif", "borc"),
    ("222", "Alacak Senetleri Reeskontu (-)", "aktif", "alacak"),
    ("223", "Borçlu Cari Hesaplar", "aktif", "borc"),
    ("224", "Kazanılmamış Finansal Kiralama Faiz Gelirleri (-)", "aktif", "alacak"),
    ("227", "Diğer Ticari Alacaklar", "aktif", "borc"),
    ("228", "Şüpheli Ticari Alacaklar", "aktif", "borc"),
    ("229", "Şüpheli Ticari Alacaklar Karşılığı (-)", "aktif", "alacak"),
    ("243", "İştiraklere Sermaye Taahhütleri (-)", "aktif", "borc"),
    ("244", "İştirakler Sermaye Payları Değer Düşüklüğü Karşılığı (-)", "aktif", "alacak"),
    ("246", "Bağlı Ortaklıklara Sermaye Taahhütleri (-)", "aktif", "borc"),
    ("247", "Bağlı Ortaklıklar Sermaye Payları Değer Düşüklüğü Karşılığı (-)", "aktif", "alacak"),
    ("259", "Verilen Avanslar", "aktif", "borc"),
    ("261", "Şerefiye", "aktif", "borc"),
    ("262", "Kuruluş ve Örgütlenme Giderleri", "aktif", "borc"),
    ("263", "Araştırma ve Geliştirme Giderleri", "aktif", "borc"),
    ("265", "Özel Maliyetler", "aktif", "borc"),
    ("269", "Birikmiş Amortismanlar (-)", "aktif", "alacak"),
    ("271", "Arama Giderleri", "aktif", "borc"),
    ("272", "Hazırlık ve Geliştirme Giderleri", "aktif", "borc"),
    ("277", "Diğer Özel Tükenmeye Tabi Varlıklar", "aktif", "borc"),
    ("278", "Birikmiş Tükenme Payları (-)", "aktif", "alacak"),
    ("280", "Gelecek Yıllara Ait Giderler", "aktif", "borc"),
    ("281", "Gelir Tahakkukları", "aktif", "borc"),
    ("290", "Gelecek Yıllarda İndirilecek KDV", "aktif", "borc"),
    ("291", "Gelecek Yıllarda İndirilecek KDV", "aktif", "borc"),
    ("292", "Diğer KDV", "aktif", "borc"),
    ("293", "Gelecek Yıllar İhtiyacı Stoklar", "aktif", "borc"),
    ("294", "Elden Çıkarılacak Stoklar ve Maddi Duran Varlıklar", "aktif", "borc"),
    ("297", "Diğer Çeşitli Duran Varlıklar", "aktif", "borc"),
    ("298", "Stok Değer Düşüklüğü Karşılığı (-)", "aktif", "alacak"),
    ("299", "Birikmiş Amortismanlar (-)", "aktif", "alacak"),
    ("301", "Finansal Borçlar", "pasif", "alacak"),
    ("302", "Finansal Kiralama İşlemlerinden Borçlar", "pasif", "alacak"),
    ("304", "Tahvil Anapara Borç Taksit ve Faizleri", "pasif", "alacak"),
    ("305", "Çıkarılmış Bonolar ve Senetler", "pasif", "alacak"),
    ("306", "Çıkarılmış Diğer Menkul Kıymetler", "pasif", "alacak"),
    ("308", "Menkul Kıymetler İhraç Farkları (-)", "pasif", "borc"),
    ("309", "Diğer Mali Borçlar", "pasif", "alacak"),
    ("323", "Borç Senetleri", "pasif", "alacak"),
    ("324", "Borç Senetleri Reeskontu (-)", "pasif", "borc"),
    ("329", "Diğer Ticari Borçlar", "pasif", "alacak"),
    ("331", "Ortaklara Borçlar", "pasif", "alacak"),
    ("332", "İştiraklere Borçlar", "pasif", "alacak"),
    ("333", "Bağlı Ortaklıklara Borçlar", "pasif", "alacak"),
    ("337", "Diğer Borç Senetleri Reeskontu (-)", "pasif", "borc"),
    ("339", "Diğer Çeşitli Borçlar", "pasif", "alacak"),
    ("349", "Alınan Diğer Avanslar", "pasif", "alacak"),
    ("350", "Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri", "pasif", "alacak"),
    ("351", "Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri", "pasif", "alacak"),
    ("352", "Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri", "pasif", "alacak"),
    ("353", "Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri", "pasif", "alacak"),
    ("354", "Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri", "pasif", "alacak"),
    ("355", "Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri", "pasif", "alacak"),
    ("356", "Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri", "pasif", "alacak"),
    ("357", "Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri", "pasif", "alacak"),
    ("358", "Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri", "pasif", "alacak"),
    ("359", "Alınan Diğer Avanslar", "pasif", "alacak"),
    ("362", "Ödenecek Emeklilik Kesintileri", "pasif", "alacak"),
    ("369", "Ödenecek Diğer Yükümlülükler", "pasif", "alacak"),
    ("371", "Dönem Kârının Peşin Ödenen Vergi ve Diğer Yükümlülükleri (-)", "pasif", "borc"),
    ("372", "Kıdem Tazminatı Karşılığı", "pasif", "alacak"),
    ("373", "Maliyet Giderleri Karşılığı", "pasif", "alacak"),
    ("379", "Diğer Borç ve Gider Karşılıkları", "pasif", "alacak"),
    ("387", "Gelecek Aylara Ait Giderler", "pasif", "alacak"),
    ("389", "Diğer Borç ve Gider Karşılıkları", "pasif", "alacak"),
    ("391", "Hesaplanan KDV", "pasif", "alacak"),
    ("392", "Diğer KDV", "pasif", "alacak"),
    ("393", "Merkez ve Şubeler Cari Hesabı", "pasif", "alacak"),
    ("397", "Sayım ve Tesellüm Fazlaları", "pasif", "alacak"),
    ("399", "Diğer Çeşitli Yabancı Kaynaklar", "pasif", "alacak"),
    ("401", "Finansal Borçlar", "pasif", "alacak"),
    ("402", "Finansal Kiralama İşlemlerinden Borçlar", "pasif", "alacak"),
    ("405", "Çıkarılmış Tahviller", "pasif", "alacak"),
    ("407", "Çıkarılmış Diğer Menkul Kıymetler", "pasif", "alacak"),
    ("408", "Menkul Kıymetler İhraç Farkları (-)", "pasif", "borc"),
    ("409", "Diğer Mali Borçlar", "pasif", "alacak"),
    ("431", "Ortaklara Borçlar", "pasif", "alacak"),
    ("432", "İştiraklere Borçlar", "pasif", "alacak"),
    ("433", "Bağlı Ortaklıklara Borçlar", "pasif", "alacak"),
    ("437", "Diğer Borç Senetleri Reeskontu (-)", "pasif", "borc"),
    ("439", "Diğer Çeşitli Borçlar", "pasif", "alacak"),
    ("440", "Alınan Sipariş Avansları", "pasif", "alacak"),
    ("449", "Alınan Diğer Avanslar", "pasif", "alacak"),
    ("470", "Yıllara Yaygın İnşaat ve Onarım Maliyetleri", "pasif", "alacak"),
    ("471", "Yıllara Yaygın İnşaat ve Onarım Maliyetleri", "pasif", "alacak"),
    ("473", "Yıllara Yaygın İnşaat ve Onarım Maliyetleri", "pasif", "alacak"),
    ("474", "Yıllara Yaygın İnşaat ve Onarım Maliyetleri", "pasif", "alacak"),
    ("479", "Diğer Borç ve Gider Karşılıkları", "pasif", "alacak"),
    ("481", "Gelecek Yıllara Ait Gelirler", "pasif", "alacak"),
    ("482", "Gider Tahakkukları", "pasif", "alacak"),
    ("492", "Gelecek Yıllara Ertelenen veya Terkin Edilen KDV", "pasif", "alacak"),
    ("493", "Tesise Katılma Payları", "pasif", "alacak"),
    ("499", "Diğer Çeşitli Uzun Vadeli Yabancı Kaynaklar", "pasif", "alacak"),
    ("521", "Hisse Senedi İhraç Primleri", "pasif", "alacak"),
    ("522", "Maddi Duran Varlık Yeniden Değerleme Artışları", "pasif", "alacak"),
    ("523", "İştirakler Yeniden Değerleme Artışları", "pasif", "alacak"),
    ("529", "Diğer Sermaye Yedekleri", "pasif", "alacak"),
    ("541", "Statü Yedekleri", "pasif", "alacak"),
    ("548", "Diğer Kâr Yedekleri", "pasif", "alacak"),
    ("549", "Özel Fonlar", "pasif", "alacak"),
    ("603", "Diğer Gelirler", "gelir", "alacak"),
    ("604", "Konusu Kalmayan Karşılıklar", "gelir", "alacak"),
    ("605", "Enflasyon Düzeltmesi Kârları", "gelir", "alacak"),
    ("606", "Diğer Olağandışı Gelir ve Kârlar", "gelir", "alacak"),
    ("612", "Diğer İndirimler (-)", "gelir", "borc"),
    ("613", "Diğer İndirimler (-)", "gelir", "borc"),
    ("623", "Diğer Satışların Maliyeti (-)", "gider", "borc"),
    ("633", "Diğer Faaliyet Giderleri (-)", "gider", "borc"),
    ("661", "Uzun Vadeli Borçlanma Giderleri (-)", "gider", "borc"),
    ("671", "Önceki Dönem Gelir ve Kârları", "gelir", "alacak"),
    ("681", "Önceki Dönem Gider ve Zararları (-)", "gider", "borc"),
    ("692", "Dönem Net Kârı veya Zararı", "gelir", "alacak"),
    ("701", "Maliyet Muhasebesi Yansıtma Hesabı", "gider", "borc"),
    ("702", "Maliyet Muhasebesi Yansıtma Hesabı", "gider", "borc"),
    ("711", "Direkt İlk Madde ve Malzeme Giderleri Yansıtma", "gider", "alacak"),
    ("712", "Direkt İlk Madde ve Malzeme Fiyat Farkı", "gider", "borc"),
    ("713", "Direkt İlk Madde ve Malzeme Miktar Farkı", "gider", "borc"),
    ("721", "Direkt İşçilik Giderleri Yansıtma", "gider", "alacak"),
    ("722", "Direkt İşçilik Ücret Farkları", "gider", "borc"),
    ("731", "Genel Üretim Giderleri Yansıtma", "gider", "alacak"),
    ("732", "Genel Üretim Giderleri Bütçe Farkları", "gider", "borc"),
    ("733", "Genel Üretim Giderleri Verimlilik Farkları", "gider", "borc"),
    ("741", "Hizmet Üretim Maliyeti Yansıtma", "gider", "alacak"),
    ("742", "Hizmet Üretim Maliyeti Farkları", "gider", "borc"),
    ("751", "Araştırma ve Geliştirme Giderleri Yansıtma", "gider", "alacak"),
    ("761", "Pazarlama, Satış ve Dağıtım Giderleri Yansıtma", "gider", "alacak"),
    ("771", "Genel Yönetim Giderleri Yansıtma", "gider", "alacak"),
    ("781", "Finansman Giderleri Yansıtma", "gider", "alacak"),
    ("793", "Dışarıdan Sağlanan Fayda ve Hizmetler", "gider", "borc"),
    ("794", "Çeşitli Giderler", "gider", "borc"),
    ("795", "Vergi, Resim ve Harçlar", "gider", "borc"),
    ("796", "Amortismanlar ve Tükenme Payları", "gider", "borc"),
    ("797", "Finansman Giderleri", "gider", "borc"),
    ("798", "Gider Çeşitleri Yansıtma Hesabı", "gider", "alacak"),
    ("799", "Üretim Maliyet Hesabı", "gider", "borc"),
]


def yukle_ek_td_hp(apps, schema_editor):
    HesapPlani = apps.get_model("accounting", "HesapPlani")
    Tenant = apps.get_model("tenants", "Tenant")

    hesaplar = {kod: (ad, tip, normal) for kod, ad, tip, normal in EK_TDHP_HESAPLARI}
    for tenant in Tenant.objects.all().iterator():
        for kod, (ad, tip, normal) in sorted(hesaplar.items(), key=lambda item: (len(item[0]), item[0])):
            ust_kod = kod[:-1] if len(kod) in (2, 3) else None
            ust_hesap = (
                HesapPlani.objects.filter(tenant=tenant, kod=ust_kod).first()
                if ust_kod
                else None
            )
            HesapPlani.objects.update_or_create(
                tenant=tenant,
                kod=kod,
                defaults={
                    "ad": ad,
                    "tip": tip,
                    "ust_hesap": ust_hesap,
                    "seviye": len(kod),
                    "normal_bakiye": normal,
                    "detay_hesap_mi": len(kod) >= 3,
                    "is_active": True,
                },
            )


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0003_td_hesaplari"),
    ]

    operations = [
        migrations.RunPython(yukle_ek_td_hp, migrations.RunPython.noop),
    ]
